// 歌曲清单（自动生成，请勿手动修改）
const songFiles = [
    { id: 1, title: "重复犯错", artist: "古巨基", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/重复犯错.js" },
    { id: 2, title: "喜欢你", artist: "Beyond", lyricist: "黄家驹", composer: "黄家驹", file: "lyrics/喜欢你.js" },
    { id: 3, title: "海阔天空", artist: "Beyond", lyricist: "黄家驹", composer: "黄家驹", file: "lyrics/海阔天空.js" },
    { id: 4, title: "富士山下", artist: "陈奕迅", lyricist: "林夕", composer: "Christopher Chak", file: "lyrics/富士山下.js" },
    { id: 5, title: "明年今日", artist: "陈奕迅", lyricist: "林夕", composer: "陈小霞", file: "lyrics/明年今日.js" },
    { id: 6, title: "千千阙歌", artist: "陈慧娴", lyricist: "林振强", composer: "Makaino Koji", file: "lyrics/千千阙歌.js" },
    { id: 7, title: "必杀技", artist: "古巨基", lyricist: "林夕", composer: "林健华", file: "lyrics/必杀技.js" },
    { id: 8, title: "爱与诚", artist: "古巨基", lyricist: "林夕", composer: "曹雪芬", file: "lyrics/爱与诚.js" },
    { id: 9, title: "爱得太迟", artist: "古巨基", lyricist: "林夕", composer: "杨镇邦", file: "lyrics/爱得太迟.js" },
    { id: 10, title: "友共情", artist: "古巨基", lyricist: "周礼茂", composer: "陈光荣", file: "lyrics/友共情.js" },
    { id: 11, title: "欢乐今宵", artist: "古巨基", lyricist: "黄伟文", composer: "黄丹仪", file: "lyrics/欢乐今宵.js" },
    { id: 12, title: "时代", artist: "古巨基", lyricist: "林夕", composer: "谢国维", file: "lyrics/时代.js" },
    { id: 13, title: "用背脊唱情歌", artist: "汤令山", lyricist: "黄伟文", composer: "汤令山", file: "lyrics/用背脊唱情歌.js" },
    { id: 14, title: "告别我的恋人们", artist: "古巨基", lyricist: "黄伟文", composer: "郭文纬", file: "lyrics/告别我的恋人们.js" },
    { id: 15, title: "紧急联络人", artist: "汤令山", lyricist: "黄伟文", composer: "汤令山/叶崇恩", file: "lyrics/紧急联络人.js" },
    { id: 16, title: "爱神", artist: "古巨基", lyricist: "林夕", composer: "雷颂德", file: "lyrics/爱神.js" },
    { id: 17, title: "心跳回忆", artist: "古巨基", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/心跳回忆.js" },
    { id: 18, title: "第二最爱", artist: "古巨基", lyricist: "黄伟文", composer: "张佳添", file: "lyrics/第二最爱.js" },
    { id: 19, title: "罗马假期", artist: "古巨基", lyricist: "林家敏", composer: "张佳添", file: "lyrics/罗马假期.js" },
    { id: 20, title: "一生何求(live)", artist: "古巨基", lyricist: "林夕", composer: "陈志豪", file: "lyrics/一生何求(live).js" },
    { id: 21, title: "一生何求", artist: "古巨基", lyricist: "林夕", composer: "陈志豪", file: "lyrics/一生何求.js" },
    { id: 22, title: "圆", artist: "江海迦(AGA)", lyricist: "林若宁", composer: "褚镇东", file: "lyrics/圆.js" },
    { id: 23, title: "还", artist: "郑融", lyricist: "陈少琪", composer: "邓智伟", file: "lyrics/还.js" },
    { id: 24, title: "借", artist: "郑融", lyricist: "陈少琪", composer: "邓智伟", file: "lyrics/借.js" },
    { id: 25, title: "致少年时代", artist: "古巨基", lyricist: "林夕", composer: "方皓玟", file: "lyrics/致少年时代.js" },
    { id: 26, title: "粤语残片", artist: "陈奕迅", lyricist: "周博贤", composer: "江志仁/陈奕迅", file: "lyrics/粤语残片.js" },
    { id: 27, title: "游乐场", artist: "谢霆锋", lyricist: "林夕", composer: "谢霆锋", file: "lyrics/游乐场.js" },
    { id: 28, title: "黑暗中漫舞", artist: "陈奕迅", lyricist: "林夕", composer: "陈小霞", file: "lyrics/黑暗中漫舞.js" },
    { id: 29, title: "喜帖街", artist: "谢安琪", lyricist: "黄伟文", composer: "郭伟亮", file: "lyrics/喜帖街.js" },
    { id: 30, title: "呼吸有害", artist: "莫文蔚", lyricist: "罗健成", composer: "邓智伟", file: "lyrics/呼吸有害.js" },
    { id: 32, title: "天之骄女", artist: "容祖儿", lyricist: "林夕", composer: "曾奕文", file: "lyrics/天之骄女.js" },
    { id: 33, title: "忍", artist: "林欣彤", lyricist: "林夕", composer: "黄思律/Larry Wong", file: "lyrics/忍.js" },
    { id: 34, title: "恋无可恋", artist: "古巨基", lyricist: "林夕", composer: "方皓玟", file: "lyrics/恋无可恋.js" },
    { id: 35, title: "美中不足", artist: "许志安", lyricist: "黄伟文", composer: "雷颂德", file: "lyrics/美中不足.js" },
    { id: 36, title: "追风筝的孩子", artist: "张敬轩", lyricist: "林若宁", composer: "季中平", file: "lyrics/追风筝的孩子.js" },
    { id: 37, title: "Medley：赤子+愿(Live)", artist: "古巨基", lyricist: "林夕", composer: "罗大佑/黄伟年/许愿", file: "lyrics/Medley：赤子+愿(Live).js" },
    { id: 38, title: "习惯失恋", artist: "容祖儿", lyricist: "林夕", composer: "舒文", file: "lyrics/习惯失恋.js" },
    { id: 39, title: "十面埋伏", artist: "陈奕迅", lyricist: "黄伟文", composer: "Eric Kwok", file: "lyrics/十面埋伏.js" },
    { id: 145, title: "Medley：密友+损友+心甘命抵+早有预谋+罪魁+借过+我也不想这样（live）", artist: "容祖儿", lyricist: "", composer: "", file: "lyrics/Medley：密友+损友+心甘命抵+早有预谋+罪魁+借过+我也不想这样（live）.js" },
    { id: 158, title: "Medley：再见我的初恋+痛爱+逃避你+谁来爱我+损友+抱抱+想得太远+习惯失恋+一拍两散+心淡（live）", artist: "容祖儿", lyricist: "", composer: "", file: "lyrics/Medley：再见我的初恋+痛爱+逃避你+谁来爱我+损友+抱抱+想得太远+习惯失恋+一拍两散+心淡（live）.js" },
    { id: 183, title: "Medley：还+借（live）", artist: "郑融", lyricist: "陈少琪", composer: "邓智伟", file: "lyrics/Medley：还+借（live）.js" },
    { id: 202, title: "嫁妆", artist: "陈慧琳", lyricist: "黄伟文", composer: "陈光荣", file: "lyrics/嫁妆.js" },
    { id: 205, title: "寂寞夜晚(live)", artist: "陈奕迅", lyricist: "潘伟源", composer: "周治平", file: "lyrics/寂寞夜晚(live).js" },
    { id: 210, title: "樱花树下", artist: "张敬轩", lyricist: "林若宁", composer: "伍卓贤", file: "lyrics/樱花树下.js" },
    { id: 214, title: "笑忘书", artist: "张敬轩", lyricist: "林若宁", composer: "伍卓贤", file: "lyrics/笑忘书.js" },
    { id: 232, title: "世上只有", artist: "容祖儿", lyricist: "黄伟文", composer: "陈光荣", file: "lyrics/世上只有.js" },
    { id: 237, title: "失乐园（live）", artist: "容祖儿", lyricist: "黄伟文", composer: "周初晨", file: "lyrics/失乐园（live）.js" },
    { id: 239, title: "垃圾（live）", artist: "陈奕迅", lyricist: "黄伟文", composer: "陈辉阳", file: "lyrics/垃圾（live）.js" },
    { id: 291, title: "Medley：垃圾+绝+失乐园+大开眼戒(Live)", artist: "张敬轩", lyricist: "", composer: "", file: "lyrics/Medley：垃圾+绝+失乐园+大开眼戒(Live).js" },
    { id: 299, title: "抱拥这分钟", artist: "陈奕迅", lyricist: "潘源良", composer: "李振权", file: "lyrics/抱拥这分钟.js" },
    { id: 301, title: "黑夜不再来（live）", artist: "陈奕迅", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/黑夜不再来（live）.js" },
    { id: 303, title: "约定（live）", artist: "陈奕迅", lyricist: "林夕", composer: "陈小霞", file: "lyrics/约定（live）.js" },
    { id: 305, title: "七百年后", artist: "陈奕迅", lyricist: "林若宁", composer: "柳重言", file: "lyrics/七百年后.js" },
    { id: 327, title: "火鸟", artist: "杨千嬅", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/火鸟.js" },
    { id: 329, title: "假如让我说下去", artist: "杨千嬅", lyricist: "林夕", composer: "于逸尧", file: "lyrics/假如让我说下去.js" },
    { id: 331, title: "少女的祈祷", artist: "杨千嬅", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/少女的祈祷.js" },
    { id: 340, title: "数你", artist: "杨千嬅", lyricist: "林夕", composer: "蔡德才", file: "lyrics/数你.js" },
    { id: 343, title: "野孩子", artist: "杨千嬅", lyricist: "黄伟文", composer: "雷颂德", file: "lyrics/野孩子.js" },
    { id: 346, title: "河童", artist: "杨千嬅", lyricist: "林夕", composer: "黄丹仪", file: "lyrics/河童.js" },
    { id: 355, title: "可惜我是水瓶座", artist: "杨千嬅", lyricist: "黄伟文", composer: "雷颂德", file: "lyrics/可惜我是水瓶座.js" },
    { id: 357, title: "小星星", artist: "杨千嬅", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/小星星.js" },
    { id: 359, title: "再见二丁目", artist: "杨千嬅", lyricist: "林夕", composer: "于逸尧", file: "lyrics/再见二丁目.js" },
    { id: 361, title: "一千零一个", artist: "杨千嬅", lyricist: "林夕", composer: "陈韵如", file: "lyrics/一千零一个.js" },
    { id: 363, title: "飞女正传", artist: "杨千嬅", lyricist: "林夕", composer: "蔡德才", file: "lyrics/飞女正传.js" },
    { id: 365, title: "咬唇", artist: "杨千嬅", lyricist: "黄伟文", composer: "伍乐城", file: "lyrics/咬唇.js" },
    { id: 367, title: "姊妹", artist: "杨千嬅", lyricist: "林夕", composer: "C.Y.Kong", file: "lyrics/姊妹.js" },
    { id: 369, title: "悲歌之王", artist: "杨千嬅", lyricist: "林若宁", composer: "林一峰", file: "lyrics/悲歌之王.js" },
    { id: 371, title: "寒舍", artist: "杨千嬅", lyricist: "于逸尧", composer: "伍乐城", file: "lyrics/寒舍.js" },
    { id: 373, title: "笑中有泪", artist: "杨千嬅", lyricist: "林夕", composer: "于逸尧", file: "lyrics/笑中有泪.js" },
    { id: 375, title: "杨千嬅", artist: "杨千嬅", lyricist: "林夕", composer: "Eric Kwok", file: "lyrics/杨千嬅.js" },
    { id: 379, title: "最后的歌", artist: "杨千嬅", lyricist: "陈辉阳", composer: "陈辉阳", file: "lyrics/最后的歌.js" },
    { id: 381, title: "爱人", artist: "杨千嬅", lyricist: "林夕", composer: "于逸尧", file: "lyrics/爱人.js" },
    { id: 383, title: "冰点", artist: "杨千嬅", lyricist: "林夕", composer: "于逸尧", file: "lyrics/冰点.js" },
    { id: 418, title: "沙龙", artist: "陈奕迅", lyricist: "黄伟文", composer: "陈奕迅", file: "lyrics/沙龙.js" },
    { id: 445, title: "烈女", artist: "杨千嬅", lyricist: "林夕", composer: "雷颂德", file: "lyrics/烈女.js" },
    { id: 458, title: "炼金术", artist: "杨千嬅", lyricist: "黄伟文", composer: "伍乐城", file: "lyrics/炼金术.js" },
    { id: 470, title: "可人儿", artist: "杨千嬅", lyricist: "黄伟文", composer: "黄丹仪", file: "lyrics/可人儿.js" },
    { id: 475, title: "无人知道双子座（live）", artist: "容祖儿", lyricist: "黄伟文", composer: "Cousin Fung", file: "lyrics/无人知道双子座（live）.js" },
    { id: 477, title: "我杯茶", artist: "容祖儿", lyricist: "林若宁", composer: "冯彦中", file: "lyrics/我杯茶.js" },
    { id: 483, title: "东京人寿（live）", artist: "容祖儿", lyricist: "黄伟文", composer: "容祖儿/翁厚梁", file: "lyrics/东京人寿（live）.js" },
    { id: 485, title: "Medley：最后胜利+呼天不应+爱怪物的你+贪嗔痴+麻烦你+借过+罪魁（live）", artist: "容祖儿", lyricist: "", composer: "", file: "lyrics/Medley：最后胜利+呼天不应+爱怪物的你+贪嗔痴+麻烦你+借过+罪魁（live）.js" },
    { id: 491, title: "空港（live）", artist: "容祖儿", lyricist: "黄伟文", composer: "Skot Suyama/梁永泰", file: "lyrics/空港（live）.js" },
    { id: 497, title: "啜泣（live）", artist: "容祖儿", lyricist: "林夕", composer: "舒文", file: "lyrics/啜泣（live）.js" },
    { id: 504, title: "争气", artist: "容祖儿", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/争气.js" },
    { id: 508, title: "黄色大门（live）", artist: "容祖儿", lyricist: "黄伟文", composer: "王双骏", file: "lyrics/黄色大门（live）.js" },
    { id: 510, title: "华丽邂逅（live）", artist: "容祖儿", lyricist: "黄伟文", composer: "Eric Kwok", file: "lyrics/华丽邂逅（live）.js" },
    { id: 516, title: "特别嘉宾", artist: "容祖儿", lyricist: "林夕", composer: "Barry Chung", file: "lyrics/特别嘉宾.js" },
    { id: 520, title: "最好时光（live）", artist: "容祖儿", lyricist: "Kevin Kern/冯正", composer: "Kevin Kern", file: "lyrics/最好时光（live）.js" },
    { id: 522, title: "心之科学", artist: "容祖儿", lyricist: "黄伟文", composer: "翁厚梁/林家谦", file: "lyrics/心之科学.js" },
    { id: 537, title: "稀客", artist: "杨千嬅", lyricist: "黄伟文", composer: "雷颂德", file: "lyrics/稀客.js" },
    { id: 552, title: "好歌献给你(live)", artist: "陈奕迅", lyricist: "郑国江", composer: "马饲野康二", file: "lyrics/好歌献给你(live).js" },
    { id: 579, title: "一个灵魂的独白", artist: "陈奕迅", lyricist: "潘源良", composer: "江海迦", file: "lyrics/一个灵魂的独白.js" },
    { id: 589, title: "幸福摩天轮（live）", artist: "陈奕迅", lyricist: "林夕", composer: "Eric Kwok", file: "lyrics/幸福摩天轮（live）.js" },
    { id: 596, title: "渐渐", artist: "陈奕迅", lyricist: "陈咏谦", composer: "张杰邦", file: "lyrics/渐渐.js" },
    { id: 609, title: "葡萄成熟时", artist: "陈奕迅", lyricist: "黄伟文", composer: "周炳辉/Anfernee Cheung", file: "lyrics/葡萄成熟时.js" },
    { id: 613, title: "防不胜防", artist: "陈奕迅", lyricist: "黄伟文", composer: "张继聪", file: "lyrics/防不胜防.js" },
    { id: 617, title: "打回原形", artist: "陈奕迅", lyricist: "黄伟文", composer: "阿飞", file: "lyrics/打回原形.js" },
    { id: 619, title: "黄金时代", artist: "陈奕迅", lyricist: "林夕", composer: "柳重言", file: "lyrics/黄金时代.js" },
    { id: 623, title: "我的快乐时代（live）", artist: "陈奕迅", lyricist: "林夕", composer: "林健华", file: "lyrics/我的快乐时代（live）.js" },
    { id: 627, title: "阿牛", artist: "陈奕迅", lyricist: "林夕", composer: "雷颂德", file: "lyrics/阿牛.js" },
    { id: 631, title: "月球上的人", artist: "陈奕迅", lyricist: "林若宁", composer: "苏耀宗", file: "lyrics/月球上的人.js" },
    { id: 635, title: "孤儿仔（live）", artist: "陈奕迅/苦荣", lyricist: "李竣一", composer: "李竣一", file: "lyrics/孤儿仔（live）.js" },
    { id: 643, title: "漂流教室", artist: "古巨基", lyricist: "林夕", composer: "张佳添", file: "lyrics/漂流教室.js" },
    { id: 686, title: "日与夜", artist: "林忆莲", lyricist: "黄伟文", composer: "陈辉阳", file: "lyrics/日与夜.js" },
    { id: 690, title: "情意结", artist: "陈慧娴", lyricist: "林夕", composer: "陈辉阳", file: "lyrics/情意结.js" },
    { id: 701, title: "吴哥窟（live）", artist: "张敬轩", lyricist: "林若宁", composer: "陈珀", file: "lyrics/吴哥窟（live）.js" },
    { id: 705, title: "好好恋爱", artist: "方力申", lyricist: "方杰", composer: "雷颂德", file: "lyrics/好好恋爱.js" },
    { id: 709, title: "电灯胆", artist: "邓丽欣", lyricist: "李竣一", composer: "李竣一", file: "lyrics/电灯胆.js" },
    { id: 711, title: "你在何地", artist: "张国荣", lyricist: "潘源良", composer: "卢冠廷", file: "lyrics/你在何地.js" },
];
