// 歌曲：Medely：井+留白（live）

(function() {
    const song = {
        id: 977,
        title: "Medely：井+留白（live）",
        titleJyutping: ["","","","","","","","zeng2","","lau4","baak6","","","","","",""],
        artist: "张敬轩/王菀之",
        artistJyutping: ["zoeng1","ging3","hin1","","wong4","jyun2","zi1"],
        lyricist: "黄伟文/林夕",
        lyricistJyutping: ["wong4","wai5","man4","","lam4","zik6"],
        composer: "张敬轩/常石磊",
        composerJyutping: ["zoeng1","ging3","hin1","","soeng4","sek6","leoi5"],
        lyrics: [
            { chars: ["《","井","》"], jp: ["","zeng2",""] },
            { chars: ["填","词","：","黄","伟","文"], jp: ["tin4","ci4","","wong4","wai5","man4"] },
            { chars: ["作","曲","：","张","敬","轩"], jp: ["zok3","kuk1","","zoeng1","ging3","hin1"] },
            { paragraphBreak: true },
            { chars: ["越","来","越","冷"], jp: ["jyut6","loi4","jyut6","laang5"] },
            { chars: ["越","来","越","湿"], jp: ["jyut6","loi4","jyut6","sap1"] },
            { chars: ["越","来","越","黑"], jp: ["jyut6","loi4","jyut6","hak1"] },
            { chars: ["井","底","的","眼","睛"], jp: ["zeng2","dai2","dik1","ngaan5","zing1"] },
            { chars: ["抬","望","宇","宙","陨","落","碎","星"], jp: ["toi4","mong6","jyu5","zau6","wan5","lok6","seoi3","sing1"] },
            { chars: ["越","来","越","远","越","来","越","虚"], jp: ["jyut6","loi4","jyut6","jyun5","jyut6","loi4","jyut6","heoi1"] },
            { chars: ["越","来","越","轻"], jp: ["jyut6","loi4","jyut6","hing1"] },
            { chars: ["我","愿","为","情"], jp: ["ngo5","jyun6","wai4","cing4"] },
            { chars: ["黄","泉","下","畅","泳"], jp: ["wong4","cyun4","haa6","coeng3","wing6"] },
            { chars: ["你","没","有","心","领"], jp: ["nei5","mut6","jau5","sam1","ling5"] },
            { paragraphBreak: true },
            { chars: ["呼","吸","一","闭","起"], jp: ["fu1","kap1","jat1","bai3","hei2"] },
            { chars: ["仿","佛","可","以","飞"], jp: ["fong2","fat6","ho2","ji5","fei1"] },
            { chars: ["飘","上","天","际","空","气"], jp: ["piu1","soeng6","tin1","zai3","hung1","hei3"] },
            { chars: ["最","后","蓦","然","回","头","望","这","地","发","现","已","死"], jp: ["zeoi3","hau6","mak6","jin4","wui4","tau4","mong6","ze5","dei6","faat3","jin6","ji5","sei2"] },
            { chars: ["怎","么","苦","恋","到","死"], jp: ["zam2","mo1","fu2","lyun2","dou3","sei2"] },
            { chars: ["先","想","起","转","机"], jp: ["sin1","soeng2","hei2","zyun2","gei1"] },
            { chars: ["不","必","这","样","收","尾"], jp: ["bat1","bit1","ze5","joeng6","sau1","mei1"] },
            { chars: ["我","要","是","为","情","能","沉","下","去"], jp: ["ngo5","jiu3","si6","wai4","cing4","nang4","cam4","haa6","heoi3"] },
            { chars: ["便","有","勇","气","一","力"], jp: ["bin6","jau5","jung5","hei3","jat1","lik6"] },
            { chars: ["爬","起"], jp: ["paa4","hei2"] },
            { paragraphBreak: true },
            { chars: ["《","留","白","》"], jp: ["","lau4","baak6",""] },
            { chars: ["填","词","：","林","夕"], jp: ["tin4","ci4","","lam4","zik6"] },
            { chars: ["作","曲","：","常","石","磊"], jp: ["zok3","kuk1","","soeng4","sek6","leoi5"] },
            { paragraphBreak: true },
            { chars: ["白","日","梦","内","白","风","光"], jp: ["baak6","jat6","mung6","noi6","baak6","fung1","gwong1"] },
            { chars: ["将","光","阴","停","下"], jp: ["zoeng1","gwong1","jam1","ting4","haa6"] },
            { chars: ["白","受","罪","后","白","开","心"], jp: ["baak6","sau6","zeoi6","hau6","baak6","hoi1","sam1"] },
            { chars: ["将","心","瓣","埋","下"], jp: ["zoeng1","sam1","faan2","maai4","haa6"] },
            { chars: ["O","o","h","-","o","o","h","采","菊","东","篱","下"], jp: ["","","","","","","","coi2","guk1","dung1","lei4","haa6"] },
            { chars: ["H","o","o","-","o","o","h"," ","以","退","为","进","化"], jp: ["","","","","","","","","ji5","teoi3","wai4","zeon3","faa3"] },
            { paragraphBreak: true },
            { chars: ["《","井","》"], jp: ["","zeng2",""] },
            { chars: ["呼","吸","一","闭","起"], jp: ["fu1","kap1","jat1","bai3","hei2"] },
            { chars: ["仿","佛","可","以","飞"], jp: ["fong2","fat6","ho2","ji5","fei1"] },
            { chars: ["飘","上","天","际","空","气"], jp: ["piu1","soeng6","tin1","zai3","hung1","hei3"] },
            { chars: ["最","后","蓦","然","回","头","望","这","地","发","现","已","死"], jp: ["zeoi3","hau6","mak6","jin4","wui4","tau4","mong6","ze5","dei6","faat3","jin6","ji5","sei2"] },
            { chars: ["怎","么","苦","恋","到","死"], jp: ["zam2","mo1","fu2","lyun2","dou3","sei2"] },
            { chars: ["先","想","起","转","机"], jp: ["sin1","soeng2","hei2","zyun2","gei1"] },
            { chars: ["不","必","这","样","收","尾"], jp: ["bat1","bit1","ze5","joeng6","sau1","mei1"] },
            { chars: ["我","要","是","为","情","能","沉","下","去"], jp: ["ngo5","jiu3","si6","wai4","cing4","nang4","cam4","haa6","heoi3"] },
            { chars: ["便","有","勇","气","一","力"], jp: ["bin6","jau5","jung5","hei3","jat1","lik6"] },
            { chars: ["爬","起"], jp: ["paa4","hei2"] },
            { paragraphBreak: true },
            { chars: ["《","留","白","》"], jp: ["","lau4","baak6",""] },
            { chars: ["白","日","梦","内","白","风","光"], jp: ["baak6","jat6","mung6","noi6","baak6","fung1","gwong1"] },
            { chars: ["将","光","阴","停","下"], jp: ["zoeng1","gwong1","jam1","ting4","haa6"] },
            { chars: ["白","受","罪","后","白","开","心"], jp: ["baak6","sau6","zeoi6","hau6","baak6","hoi1","sam1"] },
            { chars: ["将","心","瓣","埋","下"], jp: ["zoeng1","sam1","faan2","maai4","haa6"] },
            { chars: ["O","o","h","-","o","o","h","采","菊","东","篱","下"], jp: ["","","","","","","","coi2","guk1","dung1","lei4","haa6"] },
            { chars: ["H","e","y","-","a","y"," ","以","退","为","进","化"], jp: ["","","","","","","","ji5","teoi3","wai4","zeon3","faa3"] },
            { paragraphBreak: true },
            { chars: ["白","石","画","下","白","开","水"], jp: ["baak6","sek6","waak6","haa6","baak6","hoi1","seoi2"] },
            { chars: ["将","色","彩","埋","下"], jp: ["zoeng1","sik1","coi2","maai4","haa6"] },
            { chars: ["白","袜","踏","乱","白","身","影"], jp: ["baak6","mat6","daap6","lyun6","baak6","san1","jing2"] },
            { chars: ["将","身","躯","除","下"], jp: ["zoeng1","san1","keoi1","ceoi4","haa6"] },
            { chars: ["Y","e","a","h"," ","将","阴","影","留","白"], jp: ["","","","","","zoeng1","jam1","jing2","lau4","baak6"] },
            { chars: ["Y","e","a","h"," ","向","透","明","进","化"], jp: ["","","","","","hoeng3","tau3","ming4","zeon3","faa3"] },
            { paragraphBreak: true },
            { chars: ["白","日","白","望","白","烟","花"], jp: ["baak6","jat6","baak6","mong6","baak6","jin1","faa1"] },
            { chars: ["将","感","官","遗","下"], jp: ["zoeng1","gam2","gun1","wai4","haa6"] },
            { chars: ["日","画","夜","画","画","疮","疤"], jp: ["jat6","waak6","je6","waak6","waak6","cong1","baa1"] },
            { chars: ["将","画","笔","扔","下"], jp: ["zoeng1","waak6","bat1","jing4","haa6"] },
            { chars: ["H","a","h","-","y","e","a","h"," ","将","天","色","留","白"], jp: ["","","","","","","","","","zoeng1","tin1","sik1","lau4","baak6"] },
            { chars: ["H","e","y","-","h","e","y"," ","世","界","无","界","吗"], jp: ["","","","","","","","","sai3","gaai3","mou4","gaai3","maa1"] },
            { paragraphBreak: true },
            { chars: ["白","鹭","白","撞","白","乌","鸦"], jp: ["baak6","lou6","baak6","zong6","baak6","wu1","aa1"] },
            { chars: ["好","丑","分","明","吧"], jp: ["hou2","cau2","fan1","ming4","baa6"] },
            { chars: ["日","画","夜","画","什","么","画"], jp: ["jat6","waak6","je6","waak6","sap6","mo1","waak6"] },
            { chars: ["将","画","框","除","下"], jp: ["zoeng1","waak6","kwaang1","ceoi4","haa6"] },
            { chars: ["Y","e","a","h"," ","给","阴","影","留","白"], jp: ["","","","","","kap1","jam1","jing2","lau4","baak6"] },
            { chars: ["Y","e","a","h"," ","向","透","明","进","化"], jp: ["","","","","","hoeng3","tau3","ming4","zeon3","faa3"] },
            { paragraphBreak: true },
            { chars: ["画","日","画","夜","画","青","空"], jp: ["waak6","jat6","waak6","je6","waak6","cing1","hung1"] },
            { chars: ["空","虚","不","能","画"], jp: ["hung1","heoi1","bat1","nang4","waak6"] },
            { chars: ["日","画","夜","画","什","么","画"], jp: ["jat6","waak6","je6","waak6","sap6","mo1","waak6"] },
            { chars: ["将","画","框","除","下"], jp: ["zoeng1","waak6","kwaang1","ceoi4","haa6"] },
            { chars: ["H","e","y","-","a","y"," ","将","心","迹","留","白"], jp: ["","","","","","","","zoeng1","sam1","zik1","lau4","baak6"] },
            { chars: ["H","e","y","-","a","y"," ","世","界","纯","洁","吗"], jp: ["","","","","","","","sai3","gaai3","seon4","git3","maa1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
