// 歌曲：Medley：最后胜利+呼天不应+爱怪物的你+贪嗔痴+麻烦你+借过+罪魁（live）

(function() {
    const song = {
        id: 485,
        title: "Medley：最后胜利+呼天不应+爱怪物的你+贪嗔痴+麻烦你+借过+罪魁（live）",
        titleJyutping: ["","","","","","","","zeoi3","hau6","sing3","lei6","","fu1","tin1","bat1","jing3","","ngoi3","gwaai3","mat6","dik1","nei5","","taam1","can1","ci1","","maa4","faan4","nei5","","ze3","gwo3","","zeoi6","fui1","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "",
        lyricistJyutping: [],
        composer: "",
        composerJyutping: [],
        lyrics: [
            { chars: ["《","最","后","胜","利","》"], jp: ["","zeoi3","hau6","sing3","lei6",""] },
            { chars: ["填","词","：","黄","伟","文"], jp: ["tin4","ci4","","wong4","wai5","man4"] },
            { chars: ["作","曲","：","谢","杰"], jp: ["zok3","kuk1","","ze6","git6"] },
            { paragraphBreak: true },
            { chars: ["你","有","背","叛","我","吗"], jp: ["nei5","jau5","bui3","bun6","ngo5","maa1"] },
            { chars: ["你","有","秘","密","见","她"], jp: ["nei5","jau5","bei3","mat6","gin3","taa1"] },
            { chars: ["不","过","你","不","敢","认","吗"], jp: ["bat1","gwo3","nei5","bat1","gam2","jing6","maa1"] },
            { chars: ["我","要","信","直","觉","吗"], jp: ["ngo5","jiu3","seon3","zik6","gok3","maa1"] },
            { chars: ["我","两","个","就","散","吗"], jp: ["ngo5","loeng5","go3","zau6","saan3","maa1"] },
            { chars: ["因","你","会","拣","她","是","吗"], jp: ["jan1","nei5","wui6","gaan2","taa1","si6","maa1"] },
            { chars: ["爱","到","担","惊","受","怕"], jp: ["ngoi3","dou3","daam1","ging1","sau6","paa3"] },
            { chars: ["谁","人","也","欢","迎","的","你"], jp: ["seoi4","jan4","jaa5","fun1","jing4","dik1","nei5"] },
            { chars: ["可","爱","得","太","可","怕"], jp: ["ho2","ngoi3","dak1","taai3","ho2","paa3"] },
            { paragraphBreak: true },
            { chars: ["你","要","去"], jp: ["nei5","jiu3","heoi3"] },
            { chars: ["难","道","我","追"], jp: ["naan4","dou6","ngo5","zeoi1"] },
            { chars: ["追","得","到"], jp: ["zeoi1","dak1","dou3"] },
            { chars: ["我","共","你","都","太","累"], jp: ["ngo5","gung6","nei5","dou1","taai3","leoi6"] },
            { chars: ["我","只","想","跟","你","做","对"], jp: ["ngo5","zi2","soeng2","gan1","nei5","zou6","deoi3"] },
            { chars: ["最","稳","固","伴","侣"], jp: ["zeoi3","wan2","gu3","bun6","leoi5"] },
            { paragraphBreak: true },
            { chars: ["时","常","在","发","着","恶","梦","有","人","抢","去","你"], jp: ["si4","soeng4","zoi6","faat3","zoek6","ok3","mung6","jau5","jan4","coeng2","heoi3","nei5"] },
            { chars: ["其","实","我","很","怕","当","你","感","情","的","后","备"], jp: ["kei4","sat6","ngo5","han2","paa3","dong1","nei5","gam2","cing4","dik1","hau6","bei6"] },
            { chars: ["太","保","护","你"], jp: ["taai3","bou2","wu6","nei5"] },
            { chars: ["拦","着","双","臂"], jp: ["laan4","zoek6","soeng1","bei3"] },
            { chars: ["避","免","跟","我","争","你","的","人","碰","到","你"], jp: ["bei6","min5","gan1","ngo5","zang1","nei5","dik1","jan4","pung3","dou3","nei5"] },
            { chars: ["谁","能","料","最","后","我","亦","可","能","不","爱","你"], jp: ["seoi4","nang4","liu6","zeoi3","hau6","ngo5","jik6","ho2","nang4","bat1","ngoi3","nei5"] },
            { chars: ["但","最","初","我","犹","如","冒","了","死","去","争","这","啖","气"], jp: ["daan6","zeoi3","co1","ngo5","jau4","jyu4","mou6","liu5","sei2","heoi3","zang1","ze5","daam6","hei3"] },
            { chars: ["到","最","尾","我","胜","利"], jp: ["dou3","zeoi3","mei5","ngo5","sing3","lei6"] },
            { chars: ["我","得","到","你"], jp: ["ngo5","dak1","dou3","nei5"] },
            { chars: ["为","何","又","害","怕","一","世","一","生","对","住","你"], jp: ["wai4","ho4","jau6","hoi6","paa3","jat1","sai3","jat1","sang1","deoi3","zyu6","nei5"] },
            { chars: ["尚","要","百","般","迁","就","你"], jp: ["soeng6","jiu3","baak3","bun1","cin1","zau6","nei5"] },
            { paragraphBreak: true },
            { chars: ["《","呼","天","不","应","》"], jp: ["","fu1","tin1","bat1","jing3",""] },
            { chars: ["填","词","：","黄","伟","文"], jp: ["tin4","ci4","","wong4","wai5","man4"] },
            { chars: ["作","曲","：","王","菀","之"], jp: ["zok3","kuk1","","wong4","jyun2","zi1"] },
            { paragraphBreak: true },
            { chars: ["受","苦","皆","因","深","爱","起"], jp: ["sau6","fu2","gaai1","jan1","sam1","ngoi3","hei2"] },
            { chars: ["如","果","哀","求","你"], jp: ["jyu4","gwo2","oi1","kau4","nei5"] },
            { chars: ["可","又","会","念","我","谦","卑"], jp: ["ho2","jau6","wui6","nim6","ngo5","him1","bei1"] },
            { chars: ["留","下","些","生","机"], jp: ["lau4","haa6","se1","sang1","gei1"] },
            { paragraphBreak: true },
            { chars: ["假","使","天","你","有","灵","开","恩","赏","赐","我","一","段","情"], jp: ["gaa2","si2","tin1","nei5","jau5","ling4","hoi1","jan1","soeng2","ci3","ngo5","jat1","dyun6","cing4"] },
            { chars: ["等","一","生","所","爱","变","成","等","天","打","救","这","种","绝","境"], jp: ["dang2","jat1","sang1","so2","ngoi3","bin3","sing4","dang2","tin1","daa2","gau3","ze5","zung2","zyut6","ging2"] },
            { chars: ["我","似","变","得","透","明"], jp: ["ngo5","ci5","bin3","dak1","tau3","ming4"] },
            { chars: ["舞","会","里"], jp: ["mou5", "wui6", "leoi5"] },
            { chars: ["谁","也","不","认","领"], jp: ["seoi4","jaa5","bat1","jing6","ling5"] },
            { chars: ["经","已","认","了","输"], jp: ["ging1","ji5","jing6","liu5","syu1"] },
            { chars: ["你","听","见","难","道","没","有","反","应"], jp: ["nei5","ting1","gin3","naan4","dou6","mut6","jau5","faan2","jing3"] },
            { paragraphBreak: true },
            { chars: ["可","惜","一","再","证","明"], jp: ["ho2","sik1","jat1","zoi3","zing3","ming4"] },
            { chars: ["呼","天","不","应","也","不","动","情"], jp: ["fu1","tin1","bat1","jing3","jaa5","bat1","dung6","cing4"] },
            { chars: ["兜","兜","转","转","的","挣","扎","过","程","花","的","心","血","你","都","望","清"], jp: ["dau1","dau1","zyun2","zyun2","dik1","zang1","zaat3","gwo3","cing4","faa1","dik1","sam1","hyut3","nei5","dou1","mong6","cing1"] },
            { chars: ["无","人","能","做","公","正"], jp: ["mou4","jan4","nang4","zou6","gung1","zing3"] },
            { chars: ["假","使","天","你","怜","悯","这","耐","性"], jp: ["gaa2","si2","tin1","nei5","lin4","man5","ze5","noi6","sing3"] },
            { chars: ["给","我","命","里","天","使"], jp: ["kap1", "ngo5", "ming6", "leoi5", "tin1", "si2"] },
            { chars: ["赐","我","后","劲"], jp: ["ci3","ngo5","hau6","ging6"] },
            { paragraphBreak: true },
            { chars: ["有","美","满","的","爱","情"], jp: ["jau5","mei5","mun5","dik1","ngoi3","cing4"] },
            { chars: ["我","怎","会","傻","到","这","样","求","你"], jp: ["ngo5","zam2","wui6","so4","dou3","ze5","joeng6","kau4","nei5"] },
            { chars: ["这","些","说","话","要","是","求","天","亦","不","应"], jp: ["ze5","se1","syut3","waa6","jiu3","si6","kau4","tin1","jik6","bat1","jing3"] },
            { chars: ["大","概","没","有","人","愿","听"], jp: ["daai6","koi3","mut6","jau5","jan4","jyun6","ting1"] },
            { paragraphBreak: true },
            { chars: ["《","爱","怪","物","的","你","》"], jp: ["","ngoi3","gwaai3","mat6","dik1","nei5",""] },
            { chars: ["填","词","：","林","若","宁"], jp: ["tin4","ci4","","lam4","joek6","ning4"] },
            { chars: ["作","曲","：","冯","颖","琪"], jp: ["zok3","kuk1","","fung4","wing6","kei4"] },
            { paragraphBreak: true },
            { chars: ["生","性","古","怪","缺","点","这","样","多"], jp: ["sang1","sing3","gu2","gwaai3","kyut3","dim2","ze5","joeng6","do1"] },
            { chars: ["长","满","尖","刺","人","人","离","弃","我"], jp: ["coeng4","mun5","zim1","ci3","jan4","jan4","lei4","hei3","ngo5"] },
            { chars: ["但","你"," ","不","管","旁","人","诸","多","的","教","唆"], jp: ["daan6","nei5","","bat1","gun2","pong4","jan4","zyu1","do1","dik1","gaau3","so1"] },
            { chars: ["亦","浪","费","岁","月","陪","我","渡","过"], jp: ["jik6","long6","fai3","seoi3","jyut6","pui4","ngo5","dou6","gwo3"] },
            { chars: ["错","配","的","一","个"], jp: ["co3","pui3","dik1","jat1","go3"] },
            { chars: ["饶","恕","我","出","于","贪","欢","远","比","恋","爱","多"], jp: ["jiu4","syu3","ngo5","ceot1","jyu1","taam1","fun1","jyun5","bei2","lyun2","ngoi3","do1"] },
            { paragraphBreak: true },
            { chars: ["越","是","诚","恳","对","待"], jp: ["jyut6","si6","sing4","han2","deoi3","doi6"] },
            { chars: ["越","是","成","为","良","心","障","碍"], jp: ["jyut6","si6","sing4","wai4","loeng4","sam1","zoeng3","ngoi6"] },
            { chars: ["任","别","人","歧","视","因","我","累","你","遇","上","白","眼"], jp: ["jam6","bit6","jan4","kei4","si6","jan1","ngo5","leoi6","nei5","jyu6","soeng6","baak6","ngaan5"] },
            { chars: ["你","都","百","般","宠","爱","是","种","幸","福","的","虐","待"], jp: ["nei5","dou1","baak3","bun1","cung2","ngoi3","si6","zung2","hang6","fuk1","dik1","joek6","doi6"] },
            { chars: ["长","期","地","拖","你","越","耐","越","会","有","害"], jp: ["coeng4","kei4","dei6","to1","nei5","jyut6","noi6","jyut6","wui6","jau5","hoi6"] },
            { chars: ["自","责","对","你","抱","歉","爱","不","出","爱"], jp: ["zi6","zaak3","deoi3","nei5","pou5","hip3","ngoi3","bat1","ceot1","ngoi3"] },
            { chars: ["拥","抱","你","也","带","着","感","慨"], jp: ["jung2","pou5","nei5","jaa5","daai3","zoek6","gam2","koi3"] },
            { chars: ["情","侣","到","底","未","活","过","来"], jp: ["cing4","leoi5","dou3","dai2","mei6","wut6","gwo3","loi4"] },
            { paragraphBreak: true },
            { chars: ["你","纵","容","我"], jp: ["nei5","zung3","jung4","ngo5"] },
            { chars: ["带","有","私","心"], jp: ["daai3","jau5","si1","sam1"] },
            { chars: ["分","给","你","这","种","温","馨","折","磨"], jp: ["fan1","kap1","nei5","ze5","zung2","wan1","hing1","zit3","mo4"] },
            { chars: ["时","间","不","能","拖"], jp: ["si4","gaan1","bat1","nang4","to1"] },
            { chars: ["明","白","我","只","不","过"], jp: ["ming4","baak6","ngo5","zi2","bat1","gwo3"] },
            { chars: ["寂","寞","便","惹","祸"], jp: ["zik6","mok6","bin6","je5","wo6"] },
            { chars: ["不","必","死","心","塌","地"], jp: ["bat1","bit1","sei2","sam1","taap3","dei6"] },
            { paragraphBreak: true },
            { chars: ["会","有","害"], jp: ["wui6","jau5","hoi6"] },
            { chars: ["分","开","都","不","要","视","作","意","外"], jp: ["fan1","hoi1","dou1","bat1","jiu3","si6","zok3","ji3","ngoi6"] },
            { chars: ["我","意","内"], jp: ["ngo5","ji3","noi6"] },
            { chars: ["扮","若","无","其","事","将","你","扮","做","伴","侣","礼","待"], jp: ["baan6","joek6","mou4","kei4","si6","zoeng1","nei5","baan6","zou6","bun6","leoi5","lai5","doi6"] },
            { chars: ["但","我","勉","强","报","答","你","的","慷","慨"], jp: ["daan6","ngo5","min5","koeng4","bou3","daap3","nei5","dik1","kong2","koi3"] },
            { chars: ["只","有","变","做","感","慨"], jp: ["zi2","jau5","bin3","zou6","gam2","koi3"] },
            { chars: ["施","舍","不","会","变","做","恋","爱"], jp: ["si1","se3","bat1","wui6","bin3","zou6","lyun2","ngoi3"] },
            { chars: ["这","种","恋","爱","怪","兽"], jp: ["ze5","zung2","lyun2","ngoi3","gwaai3","sau3"] },
            { chars: ["应","走","进","无","人","国","自","爱"], jp: ["jing3","zau2","zeon3","mou4","jan4","gwok3","zi6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["《","贪","嗔","痴","》"], jp: ["","taam1","can1","ci1",""] },
            { chars: ["填","词","：","林","夕"], jp: ["tin4","ci4","","lam4","zik6"] },
            { chars: ["作","曲","：","张","家","诚"], jp: ["zok3","kuk1","","zoeng1","gaa1","sing4"] },
            { paragraphBreak: true },
            { chars: ["你","爱","他"], jp: ["nei5","ngoi3","taa1"] },
            { chars: ["便","该","亲","手","放","开","他"], jp: ["bin6","goi1","can1","sau2","fong3","hoi1","taa1"] },
            { chars: ["大","报","复","还","有","用","吗"], jp: ["daai6","bou3","fuk6","waan4","jau5","jung6","maa1"] },
            { chars: ["假","使","他","无","情"], jp: ["gaa2","si2","taa1","mou4","cing4"] },
            { chars: ["才","不","因","你","惊","讶"], jp: ["coi4","bat1","jan1","nei5","ging1","ngaa6"] },
            { paragraphBreak: true },
            { chars: ["何","必","想"], jp: ["ho4","bit1","soeng2"] },
            { chars: ["一","起","两","败","与","俱","伤"], jp: ["jat1","hei2","loeng5","baai6","jyu5","keoi1","soeng1"] },
            { chars: ["要","勉","强","留","下","是","一","尊","蜡","像"], jp: ["jiu3","min5","koeng4","lau4","haa6","si6","jat1","zyun1","laap6","zoeng6"] },
            { chars: ["何","必","想"], jp: ["ho4","bit1","soeng2"] },
            { chars: ["想","他","去","内","疚","一","生"], jp: ["soeng2","taa1","heoi3","noi6","gau3","jat1","sang1"] },
            { chars: ["凭","狂","迷","被","铭","记","并","没","有","奖"], jp: ["pang4","kong4","mai4","bei6","ming4","gei3","bing6","mut6","jau5","zoeng2"] },
            { paragraphBreak: true },
            { chars: ["傻","到","令","人","愤","怒"], jp: ["so4","dou3","ling6","jan4","fan5","nou6"] },
            { chars: ["情","感","怎","去","追","讨"], jp: ["cing4","gam2","zam2","heoi3","zeoi1","tou2"] },
            { chars: ["一","失","去","便","惹","事"], jp: ["jat1","sat1","heoi3","bin6","je5","si6"] },
            { chars: ["何","其","恐","布"], jp: ["ho4","kei4","hung2","bou3"] },
            { chars: ["你","继","续","沦","落","也","为","了","他"], jp: ["nei5","gai3","zuk6","leon4","lok6","jaa5","wai4","liu5","taa1"] },
            { chars: ["以","后","难","做"], jp: ["ji5","hau6","naan4","zou6"] },
            { chars: ["最","初","的","深","爱"], jp: ["zeoi3","co1","dik1","sam1","ngoi3"] },
            { chars: ["晚","节","都","不","保"], jp: ["maan5","zit3","dou1","bat1","bou2"] },
            { chars: ["傻","到","自","寻","血","路"], jp: ["so4","dou3","zi6","cam4","hyut3","lou6"] },
            { chars: ["连","青","春","也","虚","耗"], jp: ["lin4","cing1","ceon1","jaa5","heoi1","hou3"] },
            { chars: ["假","使","这","是","爱"], jp: ["gaa2","si2","ze5","si6","ngoi3"] },
            { chars: ["人","类","爱","心","都","不","过","值","两","毫"], jp: ["jan4","leoi6","ngoi3","sam1","dou1","bat1","gwo3","zik6","loeng5","hou4"] },
            { chars: ["情","人","要","分","手","怎","起","诉"], jp: ["cing4","jan4","jiu3","fan1","sau2","zam2","hei2","sou3"] },
            { chars: ["难","受","对","姊","妹","最","多","哭","诉"], jp: ["naan4","sau6","deoi3","zi2","mui6","zeoi3","do1","huk1","sou3"] },
            { paragraphBreak: true },
            { chars: ["《","麻","烦","你","》"], jp: ["","maa4","faan4","nei5",""] },
            { chars: ["填","词","：","冯","颖","琪"], jp: ["tin4","ci4","","fung4","wing6","kei4"] },
            { chars: ["作","曲","：","冯","颖","琪"], jp: ["zok3","kuk1","","fung4","wing6","kei4"] },
            { paragraphBreak: true },
            { chars: ["麻","烦","说","多","一","次"], jp: ["maa4","faan4","syut3","do1","jat1","ci3"] },
            { chars: ["证","实","已","经","不","可","以"], jp: ["zing3","sat6","ji5","ging1","bat1","ho2","ji5"] },
            { chars: ["麻","烦","你","多","一","次"], jp: ["maa4","faan4","nei5","do1","jat1","ci3"] },
            { chars: ["数","我","缺","点"], jp: ["sou3","ngo5","kyut3","dim2"] },
            { chars: ["这","一","晚","是","多","么","易"], jp: ["ze5", "jat1", "maan5", "si6", "do1", "mo1", "ji6"] },
            { chars: ["自","由","地","说","我","那","样","随","便"], jp: ["zi6","jau4","dei6","syut3","ngo5","naa5","joeng6","ceoi4","bin6"] },
            { chars: ["如","是","铁","般","事","实"], jp: ["jyu4","si6","tit3","bun1","si6","sat6"] },
            { chars: ["尽","情","坦","白"], jp: ["zeon6","cing4","taan2","baak6"] },
            { chars: ["请","染","污","再","一","点"], jp: ["cing2","jim5","wu1","zoi3","jat1","dim2"] },
            { paragraphBreak: true },
            { chars: ["麻","烦","说","多","一","次"], jp: ["maa4","faan4","syut3","do1","jat1","ci3"] },
            { chars: ["只","怪","是","我","没","经","验"], jp: ["zi2","gwaai3","si6","ngo5","mut6","ging1","jim6"] },
            { chars: ["多","得","你","使","得","心","窝"], jp: ["do1","dak1","nei5","si2","dak1","sam1","wo1"] },
            { chars: ["只","剩","余","碎","片"], jp: ["zi2","sing6","jyu4","seoi3","pin3"] },
            { chars: ["仍","然","陶","醉"], jp: ["jing4","jin4","tou4","zeoi3"] },
            { chars: ["你","狠","心","对","待"], jp: ["nei5","han2","sam1","deoi3","doi6"] },
            { chars: ["仍","然","很","冀","待"], jp: ["jing4","jin4","han2","kei3","doi6"] },
            { chars: ["肯","施","舍","你","爱"], jp: ["hang2","si1","se3","nei5","ngoi3"] },
            { chars: ["谁","又","够","我","想","得","开"], jp: ["seoi4","jau6","gau3","ngo5","soeng2","dak1","hoi1"] },
            { paragraphBreak: true },
            { chars: ["麻","烦","你","伤","我","心"], jp: ["maa4","faan4","nei5","soeng1","ngo5","sam1"] },
            { chars: ["麻","烦","你","使","我","再","下","沉"], jp: ["maa4","faan4","nei5","si2","ngo5","zoi3","haa6","cam4"] },
            { chars: ["麻","烦","你"], jp: ["maa4","faan4","nei5"] },
            { chars: ["用","心"," ","使","我","痛","哭","可","以","更","兴","奋"], jp: ["jung6","sam1","","si2","ngo5","tung3","huk1","ho2","ji5","gang1","hing1","fan5"] },
            { chars: ["麻","烦","你","使","我","更","伤"], jp: ["maa4","faan4","nei5","si2","ngo5","gang1","soeng1"] },
            { chars: ["谁","人","都","说","吃","得","苦","才","被","景","仰"], jp: ["seoi4","jan4","dou1","syut3","hek3","dak1","fu2","coi4","bei6","ging2","joeng5"] },
            { chars: ["倘","有","些","同","情","心","理"], jp: ["tong2","jau5","se1","tung4","cing4","sam1","lei5"] },
            { chars: ["麻","烦","你"], jp: ["maa4","faan4","nei5"] },
            { chars: ["尽","量","残","忍","给","我","福","气"], jp: ["zeon6","loeng4","caan4","jan2","kap1","ngo5","fuk1","hei3"] },
            { paragraphBreak: true },
            { chars: ["我","故","作","这","样","强"], jp: ["ngo5","gu3","zok3","ze5","joeng6","koeng4"] },
            { chars: ["可","否","终","于","给","我","好","收","场"], jp: ["ho2","fau2","zung1","jyu1","kap1","ngo5","hou2","sau1","coeng4"] },
            { chars: ["我","看","似","这","样","强"], jp: ["ngo5","hon3","ci5","ze5","joeng6","koeng4"] },
            { chars: ["可","否","多","一","点","赞","赏"], jp: ["ho2","fau2","do1","jat1","dim2","zaan3","soeng2"] },
            { paragraphBreak: true },
            { chars: ["《","借","过","》"], jp: ["","ze3","gwo3",""] },
            { chars: ["填","词","：","黄","伟","文"], jp: ["tin4","ci4","","wong4","wai5","man4"] },
            { chars: ["作","曲","：","黄","丹","仪"], jp: ["zok3","kuk1","","wong4","daan1","ji4"] },
            { paragraphBreak: true },
            { chars: ["伤","我","或","是","害","我","都","惨","不","过","教","我","记","得","一","起","幸","福","过"], jp: ["soeng1","ngo5","waak6","si6","hoi6","ngo5","dou1","caam2","bat1","gwo3","gaau3","ngo5","gei3","dak1","jat1","hei2","hang6","fuk1","gwo3"] },
            { chars: ["情","愿","我","听","不","清","楚","当","时","谁","人","口","口","声","声","不","会","掉","低","我"], jp: ["cing4","jyun6","ngo5","ting1","bat1","cing1","co2","dong1","si4","seoi4","jan4","hau2","hau2","sing1","sing1","bat1","wui6","diu6","dai1","ngo5"] },
            { chars: ["待","我","差","我","没","有","奈","何"], jp: ["doi6","ngo5","caa1","ngo5","mut6","jau5","noi6","ho4"] },
            { chars: ["为","何","扮","好","心","慰","问","很","挂","念","我","么"], jp: ["wai4", "ho4", "baan6", "hou2", "sam1", "wai3", "man6", "han2", "gwaa3", "nim6", "ngo5", "mo1"] },
            { chars: ["还","能","成","为","蜜","友","么"], jp: ["waan4", "nang4", "sing4", "wai4", "mat6", "jau5", "mo1"] },
            { chars: ["你","说","得","真","轻","松"], jp: ["nei5","syut3","dak1","zan1","hing1","cung4"] },
            { chars: ["不","爱","我"], jp: ["bat1","ngoi3","ngo5"] },
            { chars: ["别","拉","拖"], jp: ["bit6","laai1","to1"] },
            { paragraphBreak: true },
            { chars: ["是","对","我","好","就","请","躲","开"], jp: ["si6","deoi3","ngo5","hou2","zau6","cing2","do2","hoi1"] },
            { chars: ["求","你","让","我","安","静","行","过"], jp: ["kau4","nei5","joeng6","ngo5","on1","zing6","hang4","gwo3"] },
            { paragraphBreak: true },
            { chars: ["《","罪","魁","》"], jp: ["","zeoi6","fui1",""] },
            { chars: ["填","词","：","林","夕"], jp: ["tin4","ci4","","lam4","zik6"] },
            { chars: ["作","曲","：","伍","乐","城"], jp: ["zok3","kuk1","","ng5","lok6","sing4"] },
            { paragraphBreak: true },
            { chars: ["离","开"," ","只","懂","得","补","充","一","句","奈","何"], jp: ["lei4","hoi1","","zi2","dung2","dak1","bou2","cung1","jat1","geoi3","noi6","ho4"] },
            { chars: ["愉","快","少"], jp: ["jyu4","faai3","siu2"] },
            { chars: ["困","恼","多"], jp: ["kwan3","nou5","do1"] },
            { chars: ["要","放","弃","对","方","那","人","物","是","我","是","我"], jp: ["jiu3","fong3","hei3","deoi3","fong1","naa5","jan4","mat6","si6","ngo5","si6","ngo5"] },
            { chars: ["我","最","多"], jp: ["ngo5","zeoi3","do1"] },
            { chars: ["自","认","这","恋","爱","是","全","错"], jp: ["zi6","jing6","ze5","lyun2","ngoi3","si6","cyun4","co3"] },
            { chars: ["跟","爱","人","来","认","错"], jp: ["gan1","ngoi3","jan4","loi4","jing6","co3"] },
            { chars: ["不","太","愉","快","度","过"], jp: ["bat1","taai3","jyu4","faai3","dou6","gwo3"] },
            { chars: ["我","甚","至","不","认","识","我"], jp: ["ngo5","sam6","zi3","bat1","jing6","sik1","ngo5"] },
            { paragraphBreak: true },
            { chars: ["若","然","是","回","望","当","初"], jp: ["joek6","jin4","si6","wui4","mong6","dong1","co1"] },
            { chars: ["我","欺","骗","人"], jp: ["ngo5","hei1","pin3","jan4"] },
            { chars: ["我","可","以"], jp: ["ngo5","ho2","ji5"] },
            { chars: ["认","错"], jp: ["jing6","co3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
