// 歌曲：一个灵魂的独白

(function() {
    const song = {
        id: 579,
        title: "一个灵魂的独白",
        titleJyutping: ["jat1","go3","ling4","wan4","dik1","duk6","baak6"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "潘源良",
        lyricistJyutping: ["pun1","jyun4","loeng4"],
        composer: "江海迦",
        composerJyutping: ["gong1","hoi2","haai6"],
        lyrics: [
            { chars: ["好","比","玻","璃","突","然","破","碎"], jp: ["hou2","bei2","bo1","lei1","dat6","jin4","po3","seoi3"] },
            { chars: ["灵","魂","浮","游","随","风","吹"], jp: ["ling4","wan4","fau4","jau4","ceoi4","fung1","ceoi1"] },
            { chars: ["世","界","悄","悄","化","作","露","水"], jp: ["sai3","gaai3","ciu3","ciu3","faa3","zok3","lou6","seoi2"] },
            { chars: ["茫","茫","然","回","望","过","去"], jp: ["mong4","mong4","jin4","wui4","mong6","gwo3","heoi3"] },
            { chars: ["如","准","许"], jp: ["jyu4","zeon2","heoi2"] },
            { chars: ["错","或","对","可","否","再","追"], jp: ["co3","waak6","deoi3","ho2","fau2","zoi3","zeoi1"] },
            { paragraphBreak: true },
            { chars: ["大","地","绿","叶","白","云","清","水"], jp: ["daai6","dei6","luk6","jip6","baak6","wan4","cing1","seoi2"] },
            { chars: ["变","作","废","气","与","沙","堆"], jp: ["bin3","zok3","fai3","hei3","jyu5","saa1","deoi1"] },
            { chars: ["说","过","挽","救","却","似","默","许"], jp: ["syut3","gwo3","waan5","gau3","koek3","ci5","mak6","heoi2"] },
            { chars: ["现","在","若","离","开"], jp: ["jin6","zoi6","joek6","lei4","hoi1"] },
            { chars: ["终","于","讲","一","句"], jp: ["zung1","jyu1","gong2","jat1","geoi3"] },
            { chars: ["原","谅","我"], jp: ["jyun4","loeng6","ngo5"] },
            { chars: ["其","实","多","此","一","举"], jp: ["kei4","sat6","do1","ci2","jat1","geoi2"] },
            { paragraphBreak: true },
            { chars: ["双","亲","囝","囡","好","友","爱","侣"], jp: ["soeng1","can1","zai2","naam4","hou2","jau2","ngoi3","leoi5"] },
            { chars: ["有","过","笑","语","和","怨","怼"], jp: ["jau5","gwo3","siu3","jyu5","wo4","jyun3","deoi6"] },
            { chars: ["看","似","永","远","却","似","逝","水"], jp: ["hon3","ci5","wing5","jyun5","koek3","ci5","sai6","seoi2"] },
            { chars: ["回","头","时","凝","望","再","次"], jp: ["wui4","tau4","si4","jing4","mong6","zoi3","ci3"] },
            { chars: ["难","张","咀"], jp: ["naan4","zoeng1","zeoi2"] },
            { chars: ["吻","别","你","安","心","步","去"], jp: ["man5","bit6","nei5","on1","sam1","bou6","heoi3"] },
            { paragraphBreak: true },
            { chars: ["多","少","所","得","尽","情","争","取"], jp: ["do1","siu2","so2","dak1","zeon6","cing4","zang1","ceoi2"] },
            { chars: ["多","少","所","失","曾","唏","嘘"], jp: ["do1", "siu2", "so2", "sat1", "cang4", "hei1", "heoi1"] },
            { chars: ["到","了","这","晚","我","笑","人","类"], jp: ["dou3","liu5","ze5","maan5","ngo5","siu3","jan4","leoi6"] },
            { chars: ["没","极","限","名","利"], jp: ["mut6","gik6","haan6","ming4","lei6"] },
            { chars: ["终","于","将","失","去"], jp: ["zung1","jyu1","zoeng1","sat1","heoi3"] },
            { chars: ["时","日","里"], jp: ["si4","jat6","leoi5"] },
            { chars: ["是","寄","居","的","堡","垒"], jp: ["si6","gei3","geoi1","dik1","bou2","leoi5"] },
            { chars: ["多","干","脆"], jp: ["do1","gon1","ceoi3"] },
            { paragraphBreak: true },
            { chars: ["过","去","我","对","与","不","对"], jp: ["gwo3","heoi3","ngo5","deoi3","jyu5","bat1","deoi3"] },
            { chars: ["再","要","计","较","太","琐","碎"], jp: ["zoi3","jiu3","gai3","gaau3","taai3","so2","seoi3"] },
            { chars: ["我","却","要","说","爱","永","远","不","是","负","累"], jp: ["ngo5","koek3","jiu3","syut3","ngoi3","wing5","jyun5","bat1","si6","fu6","leoi6"] },
            { chars: ["那","怕","你","看","我","就","似","安","然","沉","睡"], jp: ["naa5","paa3","nei5","hon3","ngo5","zau6","ci5","on1","jin4","cam4","seoi6"] },
            { chars: ["一","分","半","秒","亦","无","力","追","随"], jp: ["jat1","fan1","bun3","miu5","jik6","mou4","lik6","zeoi1","ceoi4"] },
            { paragraphBreak: true },
            { chars: ["听","过","众","说","各","一","句"], jp: ["ting1","gwo3","zung3","syut3","gok3","jat1","geoi3"] },
            { chars: ["哲","理","似","永","远","相","对"], jp: ["zit3","lei5","ci5","wing5","jyun5","soeng1","deoi3"] },
            { chars: ["原","来","多","少","理","论","都","不","可","取"], jp: ["jyun4","loi4","do1","siu2","lei5","leon6","dou1","bat1","ho2","ceoi2"] },
            { chars: ["我","爱","你","也","爱","就","会","心","灵","重","聚"], jp: ["ngo5","ngoi3","nei5","jaa5","ngoi3","zau6","wui6","sam1","ling4","cung4","zeoi6"] },
            { chars: ["何","妨","相","处","数","十","岁"], jp: ["ho4","fong4","soeng1","cyu5","sou3","sap6","seoi3"] },
            { chars: ["终","须","化","飞","灰"], jp: ["zung1","seoi1","faa3","fei1","fui1"] },
            { paragraphBreak: true },
            { chars: ["过","去","我","对","与","不","对"], jp: ["gwo3","heoi3","ngo5","deoi3","jyu5","bat1","deoi3"] },
            { chars: ["再","要","计","较","太","琐","碎"], jp: ["zoi3","jiu3","gai3","gaau3","taai3","so2","seoi3"] },
            { chars: ["我","却","要","说","爱","永","远","不","是","负","累"], jp: ["ngo5","koek3","jiu3","syut3","ngoi3","wing5","jyun5","bat1","si6","fu6","leoi6"] },
            { chars: ["那","怕","你","看","我","就","似","安","然","沉","睡"], jp: ["naa5","paa3","nei5","hon3","ngo5","zau6","ci5","on1","jin4","cam4","seoi6"] },
            { chars: ["一","分","半","秒","亦","无","力","追","随"], jp: ["jat1","fan1","bun3","miu5","jik6","mou4","lik6","zeoi1","ceoi4"] },
            { paragraphBreak: true },
            { chars: ["听","过","众","说","各","一","句"], jp: ["ting1","gwo3","zung3","syut3","gok3","jat1","geoi3"] },
            { chars: ["哲","理","似","永","远","相","对"], jp: ["zit3","lei5","ci5","wing5","jyun5","soeng1","deoi3"] },
            { chars: ["原","来","多","少","理","论","都","不","可","取"], jp: ["jyun4","loi4","do1","siu2","lei5","leon6","dou1","bat1","ho2","ceoi2"] },
            { chars: ["我","爱","你","也","爱","就","会","心","灵","重","聚"], jp: ["ngo5","ngoi3","nei5","jaa5","ngoi3","zau6","wui6","sam1","ling4","cung4","zeoi6"] },
            { chars: ["何","妨","相","处","数","十","岁"], jp: ["ho4","fong4","soeng1","cyu5","sou3","sap6","seoi3"] },
            { chars: ["终","须","化","飞","灰"], jp: ["zung1","seoi1","faa3","fei1","fui1"] },
            { chars: ["终","须","化","飞","灰"], jp: ["zung1","seoi1","faa3","fei1","fui1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
