// 歌曲：与我常在

(function() {
    const song = {
        id: 969,
        title: "与我常在",
        titleJyutping: ["jyu5","ngo5","soeng4","zoi6"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "林健华",
        composerJyutping: ["lam4","gin6","waa4"],
        lyrics: [
            { chars: ["在","一","起","看","每","出","戏"], jp: ["zoi6","jat1","hei2","hon3","mui5","ceot1","hei3"] },
            { chars: ["在","一","起","叹","每","口","气"], jp: ["zoi6","jat1","hei2","taan3","mui5","hau2","hei3"] },
            { chars: ["再","细","尝"], jp: ["zoi3","sai3","soeng4"] },
            { chars: ["同","偕","到","老","的","况","味"], jp: ["tung4","gaai1","dou3","lou5","dik1","fong3","mei6"] },
            { paragraphBreak: true },
            { chars: ["每","分","钟","也","抱","紧","你"], jp: ["mui5","fan1","zung1","jaa5","pou5","gan2","nei5"] },
            { chars: ["没","有","一","秒","共","你","别","离"], jp: ["mut6","jau5","jat1","miu5","gung6","nei5","bit6","lei4"] },
            { chars: ["还","携","手","看","著","生","与","死"], jp: ["waan4","kwai4","sau2","hon3","zyu3","sang1","jyu5","sei2"] },
            { paragraphBreak: true },
            { chars: ["坐","著","卧","著","都","分","享"], jp: ["zo6","zyu3","ngo6","zyu3","dou1","fan1","hoeng2"] },
            { chars: ["日","日","夜","夜","也","为","彼","此","设","想"], jp: ["jat6","jat6","je6","je6","jaa5","wai4","bei2","ci2","cit3","soeng2"] },
            { chars: ["站","著","望","著","都","分","享"], jp: ["zaam6","zyu3","mong6","zyu3","dou1","fan1","hoeng2"] },
            { chars: ["就","在","梦","内","发","掘","这"], jp: ["zau6","zoi6","mung6","noi6","faat3","gwat6","ze5"] },
            { chars: ["真","相"], jp: ["zan1","soeng3"] },
            { paragraphBreak: true },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","与","我","常","在"], jp: ["coi4","ho2","jyu5","ngo5","soeng4","zoi6"] },
            { chars: ["一","个","人"], jp: ["jat1","go3","jan4"] },
            { chars: ["从","镜","内","发","展","恩","爱"], jp: ["cung4","geng3","noi6","faat3","zin2","jan1","ngoi3"] },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","昼","夜","同","在"], jp: ["coi4","ho2","zau3","je6","tung4","zoi6"] },
            { chars: ["恋","不","来"], jp: ["lyun2","bat1","loi4"] },
            { chars: ["从","厌","倦","里","面","偷","取"], jp: ["cung4","jim3","gyun6","leoi5","min6","tau1","ceoi2"] },
            { chars: ["恨","爱"], jp: ["han6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["在","一","起","与","你","工","作"], jp: ["zoi6","jat1","hei2","jyu5","nei5","gung1","zok3"] },
            { chars: ["在","一","起","与","你","摸","索"], jp: ["zoi6","jat1","hei2","jyu5","nei5","mo2","sok3"] },
            { chars: ["两","个","人"], jp: ["loeng5","go3","jan4"] },
            { chars: ["同","时","占","有","的","快","乐"], jp: ["tung4","si4","zim1","jau5","dik1","faai3","lok6"] },
            { paragraphBreak: true },
            { chars: ["每","分","钟","与","你","挥","霍"], jp: ["mui5","fan1","zung1","jyu5","nei5","fai1","fok3"] },
            { chars: ["没","有","一","秒","没","我","在","旁"], jp: ["mut6","jau5","jat1","miu5","mut6","ngo5","zoi6","pong4"] },
            { chars: ["还","携","手","看","著","天","空","黑","与","光"], jp: ["waan4","kwai4","sau2","hon3","zyu3","tin1","hung1","hak1","jyu5","gwong1"] },
            { paragraphBreak: true },
            { chars: ["坐","著","卧","著","都","分","享"], jp: ["zo6","zyu3","ngo6","zyu3","dou1","fan1","hoeng2"] },
            { chars: ["日","日","夜","夜","也","为","彼","此","设","想"], jp: ["jat6","jat6","je6","je6","jaa5","wai4","bei2","ci2","cit3","soeng2"] },
            { chars: ["站","著","望","著","都","分","享"], jp: ["zaam6","zyu3","mong6","zyu3","dou1","fan1","hoeng2"] },
            { chars: ["就","在","梦","内","发","掘","这"], jp: ["zau6","zoi6","mung6","noi6","faat3","gwat6","ze5"] },
            { chars: ["真","相"], jp: ["zan1","soeng3"] },
            { paragraphBreak: true },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","与","我","常","在"], jp: ["coi4","ho2","jyu5","ngo5","soeng4","zoi6"] },
            { chars: ["一","个","人"], jp: ["jat1","go3","jan4"] },
            { chars: ["从","镜","内","发","展","恩","爱"], jp: ["cung4","geng3","noi6","faat3","zin2","jan1","ngoi3"] },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","昼","夜","同","在"], jp: ["coi4","ho2","zau3","je6","tung4","zoi6"] },
            { chars: ["恋","不","来"], jp: ["lyun2","bat1","loi4"] },
            { chars: ["从","厌","倦","里","面","偷","取"], jp: ["cung4","jim3","gyun6","leoi5","min6","tau1","ceoi2"] },
            { chars: ["恨","爱"], jp: ["han6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","与","我","常","在"], jp: ["coi4","ho2","jyu5","ngo5","soeng4","zoi6"] },
            { chars: ["一","个","人"], jp: ["jat1","go3","jan4"] },
            { chars: ["从","镜","内","发","展","恩","爱"], jp: ["cung4","geng3","noi6","faat3","zin2","jan1","ngoi3"] },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","昼","夜","同","在"], jp: ["coi4","ho2","zau3","je6","tung4","zoi6"] },
            { chars: ["恋","不","来"], jp: ["lyun2","bat1","loi4"] },
            { chars: ["从","厌","倦","里","面","偷","取"], jp: ["cung4","jim3","gyun6","leoi5","min6","tau1","ceoi2"] },
            { chars: ["恨","爱"], jp: ["han6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","与","我","常","在"], jp: ["coi4","ho2","jyu5","ngo5","soeng4","zoi6"] },
            { chars: ["一","个","人"], jp: ["jat1","go3","jan4"] },
            { chars: ["从","镜","内","发","展","恩","爱"], jp: ["cung4","geng3","noi6","faat3","zin2","jan1","ngoi3"] },
            { chars: ["除","非","你","是","我"], jp: ["ceoi4","fei1","nei5","si6","ngo5"] },
            { chars: ["才","可","昼","夜","同","在"], jp: ["coi4","ho2","zau3","je6","tung4","zoi6"] },
            { chars: ["恋","不","来"], jp: ["lyun2","bat1","loi4"] },
            { chars: ["从","厌","倦","里","面","偷","取"], jp: ["cung4","jim3","gyun6","leoi5","min6","tau1","ceoi2"] },
            { chars: ["恨","爱"], jp: ["han6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["在","一","起","会","有","多","美"], jp: ["zoi6","jat1","hei2","wui6","jau5","do1","mei5"] },
            { chars: ["在","一","起","也","会","不","美"], jp: ["zoi6","jat1","hei2","jaa5","wui6","bat1","mei5"] },
            { chars: ["如","果","可","以"], jp: ["jyu4","gwo2","ho2","ji5"] },
            { chars: ["一","班","人"], jp: ["jat1","baan1","jan4"] },
            { chars: ["同","偕","到","老","不","靠","运","气"], jp: ["tung4","gaai1","dou3","lou5","bat1","kaau3","wan6","hei3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
