// 歌曲：东京人寿（live）

(function() {
    const song = {
        id: 483,
        title: "东京人寿（live）",
        titleJyutping: ["dung1","ging1","jan4","sau6","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "容祖儿/翁厚梁",
        composerJyutping: ["jung4","zou2","ji4","","jung1","hau5","loeng4"],
        lyrics: [
            { chars: ["花","了","它"], jp: ["faa1","liu5","taa1"] },
            { chars: ["手","边","经","已","没","储","蓄","吧"], jp: ["sau2","bin1","ging1","ji5","mut6","cyu5","cuk1","baa6"] },
            { chars: ["勒","停","吧"], jp: ["lak6","ting4","baa6"] },
            { chars: ["仙","境","可","以","逝","似","烟","霞"], jp: ["sin1","ging2","ho2","ji5","sai6","ci5","jin1","haa4"] },
            { chars: ["我","又","怕"], jp: ["ngo5","jau6","paa3"] },
            { chars: ["下","次","换","了","年","号"], jp: ["haa6","ci3","wun6","liu5","nin4","hou6"] },
            { chars: ["路","边","不","再","有","花"], jp: ["lou6","bin1","bat1","zoi3","jau5","faa1"] },
            { paragraphBreak: true },
            { chars: ["省","了","它"], jp: ["saang2","liu5","taa1"] },
            { chars: ["担","心","经","济"], jp: ["daam1","sam1","ging1","zai3"] },
            { chars: ["下","秒","更","差"], jp: ["haa6","miu5","gang1","caa1"] },
            { chars: ["讲","好","一","起","看","奥","运"], jp: ["gong2","hou2","jat1","hei2","hon3","ou3","wan6"] },
            { chars: ["都","怕","有","突","发"], jp: ["dou1","paa3","jau5","dat6","faat3"] },
            { chars: ["坏","事","件"], jp: ["waai6","si6","gin6"] },
            { chars: ["搁","误","着","韶","华"], jp: ["gok3","ng6","zoek6","siu4","waa4"] },
            { paragraphBreak: true },
            { chars: ["快","乐"," ","会","不","会","重","来"], jp: ["faai3","lok6","","wui6","bat1","wui6","cung5","loi4"] },
            { chars: ["这","刻","你","再","忍","一","下"], jp: ["ze5","hak1","nei5","zoi3","jan2","jat1","haa6"] },
            { chars: ["怎","会","毫","无","代","价"], jp: ["zam2", "wui6", "hou4", "mou4", "doi6", "gaa3"] },
            { paragraphBreak: true },
            { chars: ["明","年","保","了","寿","命"], jp: ["ming4","nin4","bou2","liu5","sau6","ming6"] },
            { chars: ["谁","说","一","定"], jp: ["seoi4","syut3","jat1","ding6"] },
            { chars: ["有","伴","侣","与","东","京"], jp: ["jau5","bun6","leoi5","jyu5","dung1","ging1"] },
            { chars: ["明","年","即","使","有","热","血"], jp: ["ming4","nin4","zik1","si2","jau5","jit6","hyut3"] },
            { chars: ["初","樱","初","雪"], jp: ["co1","jing1","co1","syut3"] },
            { chars: ["又","如","何","约","定"], jp: ["jau6","jyu4","ho4","joek3","ding6"] },
            { chars: ["趁","一","切"], jp: ["can3","jat1","cit3"] },
            { chars: ["都","正","好"], jp: ["dou1","zing3","hou2"] },
            { chars: ["撮","合","无","尽"], jp: ["cyut3","hap6","mou4","zeon6"] },
            { chars: ["的","偶","然","来","尽","兴"], jp: ["dik1","ngau5","jin4","loi4","zeon6","hing1"] },
            { chars: ["随","意","浪","费","着","美","景"], jp: ["ceoi4","ji3","long6","fai3","zoek6","mei5","ging2"] },
            { chars: ["才","是","对","它","不","敬"], jp: ["coi4","si6","deoi3","taa1","bat1","ging3"] },
        { paragraphBreak: true },
            { chars: ["没","有","资","格","说","感","性"], jp: ["mut6","jau5","zi1","gaak3","syut3","gam2","sing3"] },
            { chars: ["但","最","高","兴","那","刻","会","现","形"], jp: ["daan6","zeoi3","gou1","hing1","naa5","hak1","wui6","jin6","jing4"] },
            { chars: ["常","在","怀","疑","着"], jp: ["soeng4","zoi6","waai4","ji4","zoek6"] },
            { chars: ["以","后","是","重","重","逆","境"], jp: ["ji5","hau6","si6","cung5","cung5","jik6","ging2"] },
            { chars: ["所","以","这","样","拼"], jp: ["so2","ji5","ze5","joeng6","ping1"] },
            { chars: ["这","派","对","后"], jp: ["ze5","paai3","deoi3","hau6"] },
            { chars: ["难","道","你","知"], jp: ["naan4","dou6","nei5","zi1"] },
            { chars: ["在","哪","里","有","星"], jp: ["zoi6", "naa5", "leoi5", "jau5", "sing1"] },
            { paragraphBreak: true },
            { chars: ["明","年","保","了","寿","命"], jp: ["ming4","nin4","bou2","liu5","sau6","ming6"] },
            { chars: ["无","法","肯","定"], jp: ["mou4","faat3","hang2","ding6"] },
            { chars: ["有","力","气","有","憧","憬"], jp: ["jau5","lik6","hei3","jau5","cung1","ging2"] },
            { chars: ["明","年","的","签","证","未","过"], jp: ["ming4","nin4","dik1","cim1","zing3","mei6","gwo3"] },
            { chars: ["温","馨","小","店"], jp: ["wan1","hing1","siu2","dim3"] },
            { chars: ["或","游","人","过","剩"], jp: ["waak6","jau4","jan4","gwo3","sing6"] },
            { chars: ["有","风","吕"], jp: ["jau5","fung1","leoi5"] },
            { chars: ["跟","暖","酒"], jp: ["gan1","nyun5","zau2"] },
            { chars: ["你","就","无","谓"], jp: ["nei5","zau6","mou4","wai6"] },
            { chars: ["等","雪","溶","才","尽","兴"], jp: ["dang2","syut3","jung4","coi4","zeon6","hing1"] },
            { chars: ["完","美","在","这","夜","擦","肩"], jp: ["jyun4","mei5","zoi6","ze5","je6","caat3","gin1"] },
            { chars: ["难","道","你","可","补","领"], jp: ["naan4","dou6","nei5","ho2","bou2","ling5"] },
            { chars: ["还","说","下","次","做","更","好"], jp: ["waan4","syut3","haa6","ci3","zou6","gang1","hou2"] },
            { chars: ["谁","料","这","刻","是","尾","声"], jp: ["seoi4","liu6","ze5","hak1","si6","mei5","sing1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
