// 歌曲：争气

(function() {
    const song = {
        id: 504,
        title: "争气",
        titleJyutping: ["zang1","hei3"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "陈辉阳",
        composerJyutping: ["can4","fai1","joeng4"],
        lyrics: [
            { chars: ["难","得"," ","别","离","后"], jp: ["naan4","dak1","","bit6","lei4","hau6"] },
            { chars: ["仍","旧","早","睡","早","起"], jp: ["jing4","gau6","zou2","seoi6","zou2","hei2"] },
            { chars: ["都","够","运"], jp: ["dou1","gau3","wan6"] },
            { chars: ["而","你","却"], jp: ["ji4","nei5","koek3"] },
            { chars: ["算","着","我"], jp: ["syun3","zoek6","ngo5"] },
            { chars: ["滴","过","几","滴","眼","泪"], jp: ["dik6","gwo3","gei2","dik6","ngaan5","leoi6"] },
            { chars: ["才","甘","心"], jp: ["coi4","gam1","sam1"] },
            { chars: ["道","行","高","深"], jp: ["dou6","hang4","gou1","sam1"] },
            { chars: ["算","你","好","心","地"], jp: ["syun3","nei5","hou2","sam1","dei6"] },
            { chars: ["不","愿","伤","透","一","个","人"], jp: ["bat1","jyun6","soeng1","tau3","jat1","go3","jan4"] },
            { chars: ["我","问","良","心"], jp: ["ngo5","man6","loeng4","sam1"] },
            { chars: ["即","使","能","恨","你"], jp: ["zik1","si2","nang4","han6","nei5"] },
            { chars: ["但","放","手"], jp: ["daan6","fong3","sau2"] },
            { paragraphBreak: true },
            { chars: ["没","有","空"], jp: ["mut6","jau5","hung1"] },
            { chars: ["挂","念","你"], jp: ["gwaa3","nim6","nei5"] },
            { chars: ["若","我","口","齿"], jp: ["joek6","ngo5","hau2","ci2"] },
            { chars: ["极","伶","俐"], jp: ["gik6","ling4","lei6"] },
            { chars: ["大","概","早"], jp: ["daai6","koi3","zou2"] },
            { chars: ["已","经","单","打","单","到","你","受","不","起"], jp: ["ji5","ging1","daan1","daa2","daan1","dou3","nei5","sau6","bat1","hei2"] },
            { chars: ["难","道","你"], jp: ["naan4","dou6","nei5"] },
            { chars: ["挨","不","起"], jp: ["aai1","bat1","hei2"] },
            { chars: ["你","最","好"], jp: ["nei5","zeoi3","hou2"] },
            { chars: ["好","在","你"], jp: ["hou2","zoi6","nei5"] },
            { chars: ["仍","然","期","望"], jp: ["jing4","jin4","kei4","mong6"] },
            { chars: ["爱","人","变","知","己"], jp: ["ngoi3","jan4","bin3","zi1","gei2"] },
            { paragraphBreak: true },
            { chars: ["没","有","心","机"], jp: ["mut6","jau5","sam1","gei1"] },
            { chars: ["痛","恨","你"], jp: ["tung3","han6","nei5"] },
            { chars: ["做","你","知","己"], jp: ["zou6","nei5","zi1","gei2"] },
            { chars: ["没","名","利"], jp: ["mut6","ming4","lei6"] },
            { chars: ["大","个","女"], jp: ["daai6","go3","neoi5"] },
            { chars: ["纵","使","失","恋"], jp: ["zung3","si2","sat1","lyun2"] },
            { chars: ["工","作","至","上"], jp: ["gung1","zok3","zi3","soeng6"] },
            { chars: ["才","争","气"], jp: ["coi4","zang1","hei3"] },
            { chars: ["原","谅","我","小","气"], jp: ["jyun4","loeng6","ngo5","siu2","hei3"] },
            { chars: ["前","度","现","在","排","第","尾"], jp: ["cin4","dou6","jin6","zoi6","paai4","dai6","mei5"] },
            { chars: ["未","能","拿","出","空","档","来","受","气"], jp: ["mei6","nang4","naa4","ceot1","hung1","dong2","loi4","sau6","hei3"] },
            { paragraphBreak: true },
            { chars: ["别","扮","好","心"], jp: ["bit6","baan6","hou2","sam1"] },
            { chars: ["勉","强","说","分","手","都","是","好","友"], jp: ["min5","koeng4","syut3","fan1","sau2","dou1","si6","hou2","jau5"] },
            { chars: ["我","至","今"], jp: ["ngo5","zi3","gam1"] },
            { chars: ["只","得","你","这","敌","人"], jp: ["zi2","dak1","nei5","ze5","dik6","jan4"] },
            { chars: ["如","何","渡","过"], jp: ["jyu4","ho4","dou6","gwo3"] },
            { chars: ["下","半","生"], jp: ["haa6","bun3","sang1"] },
            { paragraphBreak: true },
            { chars: ["没","有","空"], jp: ["mut6","jau5","hung1"] },
            { chars: ["挂","念","你"], jp: ["gwaa3","nim6","nei5"] },
            { chars: ["若","我","口","齿"], jp: ["joek6","ngo5","hau2","ci2"] },
            { chars: ["极","伶","俐"], jp: ["gik6","ling4","lei6"] },
            { chars: ["大","概","早"], jp: ["daai6","koi3","zou2"] },
            { chars: ["已","经","单","打","单","到","你","受","不","起"], jp: ["ji5","ging1","daan1","daa2","daan1","dou3","nei5","sau6","bat1","hei2"] },
            { chars: ["难","道","你"], jp: ["naan4","dou6","nei5"] },
            { chars: ["挨","不","起"], jp: ["aai1","bat1","hei2"] },
            { chars: ["我","要","玩"], jp: ["ngo5","jiu3","wun6"] },
            { chars: ["不","受","理"], jp: ["bat1","sau6","lei5"] },
            { chars: ["没","人","缠","住"], jp: ["mut6","jan4","cin4","zyu6"] },
            { chars: ["你","是","好","福","气"], jp: ["nei5","si6","hou2","fuk1","hei3"] },
            { paragraphBreak: true },
            { chars: ["如","果"," ","天","都","迫","我","争","气"], jp: ["jyu4","gwo2","","tin1","dou1","baak1","ngo5","zang1","hei3"] },
            { chars: ["离","去"," ","大","概","不","会","死"], jp: ["lei4","heoi3","","daai6","koi3","bat1","wui6","sei2"] },
            { chars: ["我","退","出"], jp: ["ngo5","teoi3","ceot1"] },
            { chars: ["但","求","大","家","欢","喜"], jp: ["daan6","kau4","daai6","gaa1","fun1","hei2"] },
            { chars: ["无","谓","到","最","后"], jp: ["mou4","wai6","dou3","zeoi3","hau6"] },
            { chars: ["不","三","不","四"], jp: ["bat1","saam1","bat1","sei3"] },
            { paragraphBreak: true },
            { chars: ["没","有","空"], jp: ["mut6","jau5","hung1"] },
            { chars: ["挂","念","你"], jp: ["gwaa3","nim6","nei5"] },
            { chars: ["若","我","口","齿"], jp: ["joek6","ngo5","hau2","ci2"] },
            { chars: ["极","伶","俐"], jp: ["gik6","ling4","lei6"] },
            { chars: ["大","概","早"], jp: ["daai6","koi3","zou2"] },
            { chars: ["已","经","单","打","单","到","你","受","不","起"], jp: ["ji5","ging1","daan1","daa2","daan1","dou3","nei5","sau6","bat1","hei2"] },
            { chars: ["难","道","你"], jp: ["naan4","dou6","nei5"] },
            { chars: ["挨","不","起"], jp: ["aai1","bat1","hei2"] },
            { chars: ["你","最","好"], jp: ["nei5","zeoi3","hou2"] },
            { chars: ["好","在","你"], jp: ["hou2","zoi6","nei5"] },
            { chars: ["仍","然","期","望"], jp: ["jing4","jin4","kei4","mong6"] },
            { chars: ["爱","人","变","知","己"], jp: ["ngoi3","jan4","bin3","zi1","gei2"] },
            { paragraphBreak: true },
            { chars: ["没","有","心","机"], jp: ["mut6","jau5","sam1","gei1"] },
            { chars: ["痛","恨","你"], jp: ["tung3","han6","nei5"] },
            { chars: ["做","你","知","己"], jp: ["zou6","nei5","zi1","gei2"] },
            { chars: ["没","名","利"], jp: ["mut6","ming4","lei6"] },
            { chars: ["大","个","女"], jp: ["daai6","go3","neoi5"] },
            { chars: ["纵","使","失","恋"], jp: ["zung3","si2","sat1","lyun2"] },
            { chars: ["工","作","至","上"], jp: ["gung1","zok3","zi3","soeng6"] },
            { chars: ["才","争","气"], jp: ["coi4","zang1","hei3"] },
            { chars: ["原","谅","我","小","气"], jp: ["jyun4","loeng6","ngo5","siu2","hei3"] },
            { chars: ["前","度","现","在","排","第","尾"], jp: ["cin4","dou6","jin6","zoi6","paai4","dai6","mei5"] },
            { chars: ["未","能","拿","出","空","档","来","受","气"], jp: ["mei6","nang4","naa4","ceot1","hung1","dong2","loi4","sau6","hei3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
