// 歌曲：于心有愧

(function() {
    const song = {
        id: 820,
        title: "于心有愧",
        titleJyutping: ["jyu1","sam1","jau5","kwai5"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "钟达茵",
        composerJyutping: ["zung1","daat6","jan1"],
        lyrics: [
            { chars: ["如","果","我","听","歌","可","眼","红"], jp: ["jyu4","gwo2","ngo5","ting1","go1","ho2","ngaan5","hung4"] },
            { chars: ["何","以","待","你","好","偏","不","懂"], jp: ["ho4","ji5","doi6","nei5","hou2","pin1","bat1","dung2"] },
            { chars: ["自","细","做","过","多","少","美","梦"], jp: ["zi6","sai3","zou6","gwo3","do1","siu2","mei5","mung6"] },
            { chars: ["慈","悲","的","伟","论"], jp: ["ci4","bei1","dik1","wai5","leon6"] },
            { chars: ["连","乞","丐","喊","穷","心","也","痛"], jp: ["lin4","hat1","koi3","haam3","kung4","sam1","jaa5","tung3"] },
            { chars: ["竟","怕","放","怀","拥","抱","你"], jp: ["ging2","paa3","fong3","waai4","jung2","pou5","nei5"] },
            { chars: ["让","你","露","欢","容"], jp: ["joeng6","nei5","lou6","fun1","jung4"] },
            { chars: ["追","悔","无","用"], jp: ["zeoi1","fui3","mou4","jung6"] },
            { chars: ["转","眼","发","现"], jp: ["zyun2","ngaan5","faat3","jin6"] },
            { chars: ["你","失","踪"], jp: ["nei5","sat1","zung1"] },
            { paragraphBreak: true },
            { chars: ["曾","听","说","过"], jp: ["cang4","ting1","syut3","gwo3"] },
            { chars: ["你","某","夜","结","婚"], jp: ["nei5","mau5","je6","git3","fan1"] },
            { chars: ["未","曾","露","笑","容"], jp: ["mei6","cang4","lou6","siu3","jung4"] },
            { chars: ["实","在","不","敢","知","道","我","是","元","凶"], jp: ["sat6","zoi6","bat1","gam2","zi1","dou3","ngo5","si6","jyun4","hung1"] },
            { chars: ["大","概","当","初","我","未","懂","得","顾","忌"], jp: ["daai6","koi3","dong1","co1","ngo5","mei6","dung2","dak1","gu3","gei6"] },
            { chars: ["年","少","率","性","害","惨","你"], jp: ["nin4","siu3","seot1","sing3","hoi6","caam2","nei5"] },
            { chars: ["令","人","受","伤","滋","味"], jp: ["ling6","jan4","sau6","soeng1","zi1","mei6"] },
            { chars: ["难","保","更","可","悲"], jp: ["naan4","bou2","gang1","ho2","bei1"] },
            { chars: ["这","心","地"], jp: ["ze5","sam1","dei2"] },
            { chars: ["再","善","良","终","生","怎","去"], jp: ["zoi3","sin6","loeng4","zung1","sang1","zam2","heoi3"] },
            { chars: ["向","你","说","对","不","起"], jp: ["hoeng3","nei5","syut3","deoi3","bat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["良","心","有","愧"], jp: ["loeng4","sam1","jau5","kwai5"] },
            { chars: ["原","来","随","便","错","手"], jp: ["jyun4","loi4","ceoi4","bin6","co3","sau2"] },
            { chars: ["可","毁","了","人","一","世"], jp: ["ho2","wai2","liu5","jan4","jat1","sai3"] },
            { chars: ["立","志","助","世","人","脱","贫","以","为"], jp: ["laap6","zi3","zo6","sai3","jan4","tyut3","pan4","ji5","wai4"] },
            { chars: ["便","伟","大","到","像","多","么","有","为"], jp: ["bin6","wai5","daai6","dou3","zoeng6","do1","mo1","jau5","wai4"] },
            { chars: ["这","种","刺","猬"], jp: ["ze5","zung2","ci3","wai6"] },
            { chars: ["连","谁","曾","待","我","好"], jp: ["lin4","seoi4","cang4","doi6","ngo5","hou2"] },
            { chars: ["都","可","带","来","伤","势"], jp: ["dou1","ho2","daai3","loi4","soeng1","sai3"] },
            { chars: ["被","我","害","过","来","接","受","我","跪"], jp: ["bei6","ngo5","hoi6","gwo3","loi4","zip3","sau6","ngo5","gwai6"] },
            { chars: ["是","我","在","制","造","眼","泪","居","然","想","救","世"], jp: ["si6","ngo5","zoi6","zai3","zou6","ngaan5","leoi6","geoi1","jin4","soeng2","gau3","sai3"] },
            { paragraphBreak: true },
            { chars: ["就","算","积","蓄","献","尽","饥","荒","赤","地"], jp: ["zau6","syun3","zik1","cuk1","hin3","zeon6","gei1","fong1","cek3","dei6"] },
            { chars: ["而","太","多","债","没","处","理"], jp: ["ji4","taai3","do1","zaai3","mut6","cyu5","lei5"] },
            { chars: ["累","人","累","己","滋","味"], jp: ["leoi6","jan4","leoi6","gei2","zi1","mei6"] },
            { chars: ["余","生","也","记","起"], jp: ["jyu4","sang1","jaa5","gei3","hei2"] },
            { chars: ["数","一","数"], jp: ["sou3","jat1","sou3"] },
            { chars: ["我","实","情","不","只","得","你","要","说","句","对","不","起"], jp: ["ngo5","sat6","cing4","bat1","zi2","dak1","nei5","jiu3","syut3","geoi3","deoi3","bat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["良","心","有","愧"], jp: ["loeng4","sam1","jau5","kwai5"] },
            { chars: ["原","来","随","便","错","手"], jp: ["jyun4","loi4","ceoi4","bin6","co3","sau2"] },
            { chars: ["可","毁","了","人","一","世"], jp: ["ho2","wai2","liu5","jan4","jat1","sai3"] },
            { chars: ["立","志","助","世","人","脱","贫","以","为"], jp: ["laap6","zi3","zo6","sai3","jan4","tyut3","pan4","ji5","wai4"] },
            { chars: ["便","伟","大","到","像","多","么","有","为"], jp: ["bin6","wai5","daai6","dou3","zoeng6","do1","mo1","jau5","wai4"] },
            { chars: ["这","种","刺","猬"], jp: ["ze5","zung2","ci3","wai6"] },
            { chars: ["连","谁","曾","待","我","好"], jp: ["lin4","seoi4","cang4","doi6","ngo5","hou2"] },
            { chars: ["都","可","带","来","伤","势"], jp: ["dou1","ho2","daai3","loi4","soeng1","sai3"] },
            { chars: ["被","我","害","过","来","接","受","我","跪"], jp: ["bei6","ngo5","hoi6","gwo3","loi4","zip3","sau6","ngo5","gwai6"] },
            { chars: ["是","我","在","制","造","眼","泪","居","然","想","救","世"], jp: ["si6","ngo5","zoi6","zai3","zou6","ngaan5","leoi6","geoi1","jin4","soeng2","gau3","sai3"] },
            { paragraphBreak: true },
            { chars: ["于","心","有","愧"], jp: ["jyu1","sam1","jau5","kwai5"] },
            { chars: ["原","来","随","便","错","手"], jp: ["jyun4","loi4","ceoi4","bin6","co3","sau2"] },
            { chars: ["可","毁","了","人","一","世"], jp: ["ho2","wai2","liu5","jan4","jat1","sai3"] },
            { chars: ["立","志","助","世","人","脱","贫","以","为"], jp: ["laap6","zi3","zo6","sai3","jan4","tyut3","pan4","ji5","wai4"] },
            { chars: ["便","伟","大","到","像","多","么","有","为"], jp: ["bin6","wai5","daai6","dou3","zoeng6","do1","mo1","jau5","wai4"] },
            { chars: ["这","种","刺","猬"], jp: ["ze5","zung2","ci3","wai6"] },
            { chars: ["连","谁","曾","待","我","好"], jp: ["lin4","seoi4","cang4","doi6","ngo5","hou2"] },
            { chars: ["都","可","带","来","伤","势"], jp: ["dou1","ho2","daai3","loi4","soeng1","sai3"] },
            { chars: ["内","疚","内","疚","内","疚","没","作","为"], jp: ["noi6","gau3","noi6","gau3","noi6","gau3","mut6","zok3","wai4"] },
            { chars: ["直","到","在","某","年","某","日","我","能","安","息","于","葬","礼"], jp: ["zik6","dou3","zoi6","mau5","nin4","mau5","jat6","ngo5","nang4","on1","sik1","jyu1","zong3","lai5"] },
            { paragraphBreak: true },
            { chars: ["仍","想","你","一","家","可","到","齐"], jp: ["jing4","soeng2","nei5","jat1","gaa1","ho2","dou3","cai4"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
