// 歌曲：你在何地

(function() {
    const song = {
        id: 711,
        title: "你在何地",
        titleJyutping: ["nei5","zoi6","ho4","dei6"],
        artist: "张国荣",
        artistJyutping: ["zoeng1","gwok3","wing4"],
        lyricist: "潘源良",
        lyricistJyutping: ["pun1","jyun4","loeng4"],
        composer: "卢冠廷",
        composerJyutping: ["lou4","gun1","ting4"],
        lyrics: [
            { chars: ["夜"," ","天","花","板","有","这","段","戏"], jp: ["je6","","tin1","faa1","baan2","jau5","ze5","dyun6","hei3"] },
            { chars: ["总","关","不","上","心","里","的","放","映","机"], jp: ["zung2","gwaan1","bat1","soeng5","sam1","leoi5","dik1","fong3","jing2","gei1"] },
            { chars: ["你"," ","夜","幕","中","只","有","你"], jp: ["nei5","","je6","mok6","zung1","zi2","jau5","nei5"] },
            { chars: ["飘","过"," ","再","掠","过","再","记","起"], jp: ["piu1","gwo3","","zoi3","loek6","gwo3","zoi3","gei3","hei2"] },
            { paragraphBreak: true },
            { chars: ["旧","的","影","子"], jp: ["gau6","dik1","jing2","zi2"] },
            { chars: ["旧","的","声","音"], jp: ["gau6","dik1","sing1","jam1"] },
            { chars: ["但","新","的","痛","悲"], jp: ["daan6","san1","dik1","tung3","bei1"] },
            { chars: ["来","追","逼","我"], jp: ["loi4","zeoi1","bik1","ngo5"] },
            { chars: ["来","冲","击","我"], jp: ["loi4","cung1","gik1","ngo5"] },
            { chars: ["无","法","退","或","避"], jp: ["mou4","faat3","teoi3","waak6","bei6"] },
            { chars: ["从","此","方","知"], jp: ["cung4","ci2","fong1","zi1"] },
            { chars: ["从","今","方","知"], jp: ["cung4","gam1","fong1","zi1"] },
            { chars: ["是","多","么","爱","你"], jp: ["si6","do1","mo1","ngoi3","nei5"] },
            { chars: ["思","想","早","已","与","你","一","起"], jp: ["si1","soeng2","zou2","ji5","jyu5","nei5","jat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["旧","的","影","子"], jp: ["gau6","dik1","jing2","zi2"] },
            { chars: ["旧","的","声","音"], jp: ["gau6","dik1","sing1","jam1"] },
            { chars: ["但","新","的","痛","悲"], jp: ["daan6","san1","dik1","tung3","bei1"] },
            { chars: ["来","追","逼","我"], jp: ["loi4","zeoi1","bik1","ngo5"] },
            { chars: ["来","冲","击","我"], jp: ["loi4","cung1","gik1","ngo5"] },
            { chars: ["无","法","退","或","避"], jp: ["mou4","faat3","teoi3","waak6","bei6"] },
            { chars: ["从","此","方","知"], jp: ["cung4","ci2","fong1","zi1"] },
            { chars: ["从","今","方","知"], jp: ["cung4","gam1","fong1","zi1"] },
            { chars: ["是","多","么","爱","你"], jp: ["si6","do1","mo1","ngoi3","nei5"] },
            { chars: ["思","想","早","已","与","你","一","起"], jp: ["si1","soeng2","zou2","ji5","jyu5","nei5","jat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["旧","地"," ","偏","不","可","以","再","遇","你"], jp: ["gau6","dei6","","pin1","bat1","ho2","ji5","zoi3","jyu6","nei5"] },
            { chars: ["好","比","失","去","焦","距","的","摄","影","机"], jp: ["hou2","bei2","sat1","heoi3","ziu1","keoi5","dik1","sip3","jing2","gei1"] },
            { chars: ["你"," ","为","什","么","不","见","你"], jp: ["nei5","","wai4","sap6","mo1","bat1","gin3","nei5"] },
            { chars: ["只","有","这","耀","眼","繁","华","地"], jp: ["zi2","jau5","ze5","jiu6","ngaan5","faan4","waa4","dei6"] },
            { paragraphBreak: true },
            { chars: ["旧","的","影","子"], jp: ["gau6","dik1","jing2","zi2"] },
            { chars: ["旧","的","声","音"], jp: ["gau6","dik1","sing1","jam1"] },
            { chars: ["但","新","的","痛","悲"], jp: ["daan6","san1","dik1","tung3","bei1"] },
            { chars: ["来","追","逼","我"], jp: ["loi4","zeoi1","bik1","ngo5"] },
            { chars: ["来","冲","击","我"], jp: ["loi4","cung1","gik1","ngo5"] },
            { chars: ["无","法","退","或","避"], jp: ["mou4","faat3","teoi3","waak6","bei6"] },
            { chars: ["从","此","方","知"], jp: ["cung4","ci2","fong1","zi1"] },
            { chars: ["从","今","方","知"], jp: ["cung4","gam1","fong1","zi1"] },
            { chars: ["是","多","么","爱","你"], jp: ["si6","do1","mo1","ngoi3","nei5"] },
            { chars: ["思","想","早","已","与","你","一","起"], jp: ["si1","soeng2","zou2","ji5","jyu5","nei5","jat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["是","否","应","该","是","否","应","当","让","痴","心","冻","死"], jp: ["si6","fau2","jing3","goi1","si6","fau2","jing3","dong1","joeng6","ci1","sam1","dung3","sei2"] },
            { chars: ["从","此","不","要"], jp: ["cung4","ci2","bat1","jiu3"] },
            { chars: ["从","此","不","再","求","与","你","一","起"], jp: ["cung4","ci2","bat1","zoi3","kau4","jyu5","nei5","jat1","hei2"] },
            { chars: ["但","天","花","板","在","这","一","晚"], jp: ["daan6","tin1","faa1","baan2","zoi6","ze5","jat1","maan5"] },
            { chars: ["仍","挥","不","去","你"], jp: ["jing4","fai1","bat1","heoi3","nei5"] },
            { chars: ["深","宵","冰","冷","情","人","你","在","何","地"], jp: ["sam1","siu1","bing1","laang5","cing4","jan4","nei5","zoi6","ho4","dei6"] },
            { paragraphBreak: true },
            { chars: ["是","否","应","该","是","否","应","当","让","痴","心","冻","死"], jp: ["si6","fau2","jing3","goi1","si6","fau2","jing3","dong1","joeng6","ci1","sam1","dung3","sei2"] },
            { chars: ["从","此","不","要"], jp: ["cung4","ci2","bat1","jiu3"] },
            { chars: ["从","此","不","再","求","与","你","一","起"], jp: ["cung4","ci2","bat1","zoi3","kau4","jyu5","nei5","jat1","hei2"] },
            { chars: ["但","天","花","板","在","这","一","晚"], jp: ["daan6","tin1","faa1","baan2","zoi6","ze5","jat1","maan5"] },
            { chars: ["仍","挥","不","去","你"], jp: ["jing4","fai1","bat1","heoi3","nei5"] },
            { chars: ["深","宵","冰","冷","情","人","你","在","何","地"], jp: ["sam1","siu1","bing1","laang5","cing4","jan4","nei5","zoi6","ho4","dei6"] },
            { chars: ["在","何","地"], jp: ["zoi6","ho4","dei6"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
