// 歌曲：华丽邂逅（live）

(function() {
    const song = {
        id: 510,
        title: "华丽邂逅（live）",
        titleJyutping: ["waa4","lai6","haai5","hau6","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "Eric Kwok",
        composerJyutping: ["","","","","","","","",""],
        lyrics: [
            { chars: ["我","细","看","过"], jp: ["ngo5","sai3","hon3","gwo3"] },
            { chars: ["你","的","笑"], jp: ["nei5","dik1","siu3"] },
            { chars: ["与","你","的","脸"], jp: ["jyu5","nei5","dik1","lim5"] },
            { chars: ["我","占","有","过"], jp: ["ngo5","zim1","jau5","gwo3"] },
            { chars: ["你","的","爱"], jp: ["nei5","dik1","ngoi3"] },
            { chars: ["与","你","的","暖"], jp: ["jyu5","nei5","dik1","nyun5"] },
            { chars: ["我","也","发","觉"], jp: ["ngo5","jaa5","faat3","gok3"] },
            { chars: ["缘","份","曾"], jp: ["jyun4","fan6","zang1"] },
            { chars: ["来","过","了"], jp: ["loi4","gwo3","liu5"] },
            { chars: ["就","在","伸","手","那","么","远"], jp: ["zau6", "zoi6", "san1", "sau2", "naa5", "mo1", "jyun5"] },
            { paragraphBreak: true },
            { chars: ["我","笑","一","笑"], jp: ["ngo5","siu3","jat1","siu3"] },
            { chars: ["计","一","计"], jp: ["gai3","jat1","gai3"] },
            { chars: ["再","算","一","算"], jp: ["zoi3","syun3","jat1","syun3"] },
            { chars: ["我","也","赞","叹"], jp: ["ngo5","jaa5","zaan3","taan3"] },
            { chars: ["奇","妙","如"], jp: ["kei4","miu6","jyu4"] },
            { chars: ["航","道","太","阔"], jp: ["hong4","dou6","taai3","fut3"] },
            { chars: ["宇","宙","太","玄","乘","着","你","我"], jp: ["jyu5","zau6","taai3","jyun4","sing4","zoek6","nei5","ngo5"] },
            { chars: ["两","部","火","箭"], jp: ["loeng5","bou6","fo2","zin3"] },
            { chars: ["其","实","与","你","有","权"], jp: ["kei4","sat6","jyu5","nei5","jau5","kyun4"] },
            { chars: ["永","远","未","谋","面"], jp: ["wing5","jyun5","mei6","mau4","min6"] },
            { chars: ["年","月","里","平","白","错","过"], jp: ["nin4","jyut6","lei5","ping4","baak6","co3","gwo3"] },
            { chars: ["某","个","友","谊","或","爱","恋"], jp: ["mau5","go3","jau5","ji4","waak6","ngoi3","lyun2"] },
            { paragraphBreak: true },
            { chars: ["浮","游","在","无","限","宇","宙"], jp: ["fau4","jau4","zoi6","mou4","haan6","jyu5","zau6"] },
            { chars: ["总","算","拖","过","你","的","手"], jp: ["zung2","syun3","to1","gwo3","nei5","dik1","sau2"] },
            { chars: ["银","河","上","华","丽","邂","逅"], jp: ["ngan4","ho4","soeng6","waa4","lai6","haai5","hau6"] },
            { chars: ["衣","角","沾","满","了","星","斗"], jp: ["ji1","gok3","zim1","mun5","liu5","sing1","dau3"] },
            { chars: ["以","后","纵","然","遇","上","气","流"], jp: ["ji5","hau6","zung3","jin4","jyu6","soeng6","hei3","lau4"] },
            { chars: ["又","远","去"], jp: ["jau6","jyun5","heoi3"] },
            { chars: ["余","晖","可","带","走"], jp: ["jyu4","fai1","ho2","daai3","zau2"] },
            { chars: ["同","游","在","重","叠","宇","宙"], jp: ["tung4","jau4","zoi6","cung5","dip6","jyu5","zau6"] },
            { chars: ["只","要","一","刹","那","么","久"], jp: ["zi2", "jiu3", "jat1", "caat3", "naa5", "mo1", "gau2"] },
            { chars: ["来","年","完","成","夜","航"], jp: ["loi4","nin4","jyun4","sing4","je6","hong4"] },
            { chars: ["降","落","时","候"], jp: ["gong3","lok6","si4","hau6"] },
            { chars: ["我","所","记","得","的","会","是","我","这","刻","多","富","有"], jp: ["ngo5","so2","gei3","dak1","dik1","wui6","si6","ngo5","ze5","hak1","do1","fu3","jau5"] },
            { paragraphBreak: true },
            { chars: ["错","过","了","你"], jp: ["co3","gwo3","liu5","nei5"] },
            { chars: ["我","需","要"], jp: ["ngo5","seoi1","jiu3"] },
            { chars: ["有","记","忆","吗"], jp: ["jau5","gei3","jik1","maa1"] },
            { chars: ["欠","缺","了","你"], jp: ["him3","kyut3","liu5","nei5"] },
            { chars: ["我","今","世"], jp: ["ngo5","gam1","sai3"] },
            { chars: ["会","发","光","吗"], jp: ["wui6","faat3","gwong1","maa1"] },
            { chars: ["我","已","确","信"], jp: ["ngo5","ji5","kok3","seon3"] },
            { chars: ["游","荡","浮","华","世","界"], jp: ["jau4","dong6","fau4","waa4","sai3","gaai3"] },
            { chars: ["就","为","相","交"], jp: ["zau6","wai4","soeng1","gaau1"] },
            { chars: ["那","一","下"], jp: ["naa5","jat1","haa6"] },
            { paragraphBreak: true },
            { chars: ["你","记","得","吗","那","一","秒"], jp: ["nei5","gei3","dak1","maa1","naa5","jat1","miu5"] },
            { chars: ["你","记","得","吗"], jp: ["nei5","gei3","dak1","maa1"] },
            { chars: ["那","次","与","你","禾","稻","田","停","下"], jp: ["naa5","ci3","jyu5","nei5","wo4","dou6","tin4","ting4","haa6"] },
            { chars: ["看","过","壮","丽","晚","霞"], jp: ["hon3","gwo3","zong3","lai6","maan5","haa4"] },
            { chars: ["来","日","你","我"], jp: ["loi4","jat6","nei5","ngo5"] },
            { chars: ["老","掉","了","牙"], jp: ["lou5","diu6","liu5","ngaa4"] },
            { chars: ["还","是","有","个","最","完","美","印","象","留","下"], jp: ["waan4","si6","jau5","go3","zeoi3","jyun4","mei5","jan3","zoeng6","lau4","haa6"] },
            { chars: ["从","没","旅","行","没","票","价"], jp: ["cung4","mut6","leoi5","hang4","mut6","piu3","gaai3"] },
            { chars: ["与","你","我","愿","付","上","它"], jp: ["jyu5","nei5","ngo5","jyun6","fu6","soeng6","taa1"] },
            { paragraphBreak: true },
            { chars: ["浮","游","在","无","限","宇","宙"], jp: ["fau4","jau4","zoi6","mou4","haan6","jyu5","zau6"] },
            { chars: ["总","算","拖","过","你","的","手"], jp: ["zung2","syun3","to1","gwo3","nei5","dik1","sau2"] },
            { chars: ["银","河","上","华","丽","邂","逅"], jp: ["ngan4","ho4","soeng6","waa4","lai6","haai5","hau6"] },
            { chars: ["衣","角","沾","满","了","星","斗"], jp: ["ji1","gok3","zim1","mun5","liu5","sing1","dau3"] },
            { chars: ["以","后","纵","然","遇","上","气","流"], jp: ["ji5","hau6","zung3","jin4","jyu6","soeng6","hei3","lau4"] },
            { chars: ["又","远","去"], jp: ["jau6","jyun5","heoi3"] },
            { chars: ["回","忆","可","带","走"], jp: ["wui4","jik1","ho2","daai3","zau2"] },
            { paragraphBreak: true },
            { chars: ["来","日","旅","程"], jp: ["loi4","jat6","leoi5","cing4"] },
            { chars: ["完","结","以","后"], jp: ["jyun4","git3","ji5","hau6"] },
            { chars: ["可","将","这","次","遨","游"], jp: ["ho2","zoeng1","ze5","ci3","ngou4","jau4"] },
            { chars: ["留","在","我","们"], jp: ["lau4","zoi6","ngo5","mun4"] },
            { chars: ["那","本","春","秋"], jp: ["naa5","bun2","ceon1","cau1"] },
            { paragraphBreak: true },
            { chars: ["浮","游","在","无","限","宇","宙"], jp: ["fau4","jau4","zoi6","mou4","haan6","jyu5","zau6"] },
            { chars: ["总","算","拖","过","你","的","手"], jp: ["zung2","syun3","to1","gwo3","nei5","dik1","sau2"] },
            { chars: ["银","河","上","华","丽","邂","逅"], jp: ["ngan4","ho4","soeng6","waa4","lai6","haai5","hau6"] },
            { chars: ["衣","角","沾","满","了","星","斗"], jp: ["ji1","gok3","zim1","mun5","liu5","sing1","dau3"] },
            { chars: ["以","后","纵","然","遇","上","气","流"], jp: ["ji5","hau6","zung3","jin4","jyu6","soeng6","hei3","lau4"] },
            { chars: ["又","远","去"], jp: ["jau6","jyun5","heoi3"] },
            { chars: ["余","晖","可","带","走"], jp: ["jyu4","fai1","ho2","daai3","zau2"] },
            { paragraphBreak: true },
            { chars: ["同","游","在","重","叠","宇","宙"], jp: ["tung4","jau4","zoi6","cung5","dip6","jyu5","zau6"] },
            { chars: ["只","要","一","刹","那","么","久"], jp: ["zi2", "jiu3", "jat1", "caat3", "naa5", "mo1", "gau2"] },
            { chars: ["来","年","完","成","夜","航"], jp: ["loi4","nin4","jyun4","sing4","je6","hong4"] },
            { chars: ["降","落","时","候"], jp: ["gong3","lok6","si4","hau6"] },
            { chars: ["我","都","记","得","跟","你","互","放","光","辉","的","协","奏"], jp: ["ngo5","dou1","gei3","dak1","gan1","nei5","wu6","fong3","gwong1","fai1","dik1","hip3","zau3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
