// 歌曲：可人儿

(function() {
    const song = {
        id: 470,
        title: "可人儿",
        titleJyutping: ["ho2","jan4","ji4"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "黄丹仪",
        composerJyutping: ["wong4","daan1","ji4"],
        lyrics: [
            { chars: ["良","朋","常","常","提","着","我"], jp: ["loeng4","pang4","soeng4","soeng4","tai4","zoek6","ngo5"] },
            { chars: ["这","么","多","好","友"], jp: ["ze5", "mo1", "do1", "hou2", "jau5"] },
            { chars: ["爱","我","最","多"], jp: ["ngoi3","ngo5","zeoi3","do1"] },
            { chars: ["可","笑","是","这","么","可","爱"], jp: ["ho2", "siu3", "si6", "ze5", "mo1", "ho2", "ngoi3"] },
            { chars: ["对","快","乐","无","助"], jp: ["deoi3","faai3","lok6","mou4","zo6"] },
            { chars: ["这","数","年","不","理","深","爱","着","谁"], jp: ["ze5","sou3","nin4","bat1","lei5","sam1","ngoi3","zoek6","seoi4"] },
            { chars: ["亦","未","被","对","方","珍","惜","过"], jp: ["jik6","mei6","bei6","deoi3","fong1","zan1","sik1","gwo3"] },
            { chars: ["没","有","花"], jp: ["mut6","jau5","faa1"] },
            { chars: ["没","有","果"], jp: ["mut6","jau5","gwo2"] },
            { chars: ["但","我","记","得","他","怎","拒","绝","我"], jp: ["daan6","ngo5","gei3","dak1","taa1","zam2","keoi5","zyut6","ngo5"] },
            { paragraphBreak: true },
            { chars: ["要","是","可","爱"], jp: ["jiu3","si6","ho2","ngoi3"] },
            { chars: ["为","何","无","人","爱","我"], jp: ["wai4","ho4","mou4","jan4","ngoi3","ngo5"] },
            { chars: ["夜","夜","独","自","一","个"], jp: ["je6","je6","duk6","zi6","jat1","go3"] },
            { chars: ["祈","求","谁","来","家","里","坐","坐"], jp: ["kei4", "kau4", "seoi4", "loi4", "gaa1", "leoi5", "zo6", "zo6"] },
            { chars: ["抬","头","望","镜","亦","算","不","失","不","过"], jp: ["toi4","tau4","mong6","geng3","jik6","syun3","bat1","sat1","bat1","gwo3"] },
            { chars: ["到","底","我","什","么","出","错"], jp: ["dou3", "dai2", "ngo5", "sap6", "mo1", "ceot1", "co3"] },
            { paragraphBreak: true },
            { chars: ["要","是","可","爱"], jp: ["jiu3","si6","ho2","ngoi3"] },
            { chars: ["为","何","无","人","爱","我"], jp: ["wai4","ho4","mou4","jan4","ngoi3","ngo5"] },
            { chars: ["夜","夜","独","自","一","个"], jp: ["je6","je6","duk6","zi6","jat1","go3"] },
            { chars: ["回","来","和","墙","壁","唱","着","爱","歌"], jp: ["wui4","loi4","wo4","coeng4","bik1","coeng3","zoek6","ngoi3","go1"] },
            { chars: ["唱","到","自","信","恐","怕","亦","无","多"], jp: ["coeng3","dou3","zi6","seon3","hung2","paa3","jik6","mou4","do1"] },
            { chars: ["连","我","自","己","都","不","爱","我"], jp: ["lin4","ngo5","zi6","gei2","dou1","bat1","ngoi3","ngo5"] },
            { paragraphBreak: true },
            { chars: ["良","朋","常","常","胡","乱","猜"], jp: ["loeng4","pang4","soeng4","soeng4","wu4","lyun6","caai1"] },
            { chars: ["我","这","么","可","爱"], jp: ["ngo5", "ze5", "mo1", "ho2", "ngoi3"] },
            { chars: ["爱","侣","满","街"], jp: ["ngoi3","leoi5","mun5","gaai1"] },
            { chars: ["嘲","笑","内","带","的","安","慰","劝","我","别","言","败"], jp: ["zaau1","siu3","noi6","daai3","dik1","on1","wai3","hyun3","ngo5","bit6","jin4","baai6"] },
            { chars: ["激","愤","时"], jp: ["gik1","fan5","si4"] },
            { chars: ["总","会","拥","我","入","怀"], jp: ["zung2","wui6","jung2","ngo5","jap6","waai4"] },
            { chars: ["落","力","为","我","开","解","不","快"], jp: ["lok6","lik6","wai4","ngo5","hoi1","gaai2","bat1","faai3"] },
            { chars: ["越","要","开"], jp: ["jyut6","jiu3","hoi1"] },
            { chars: ["越","要","解"], jp: ["jyut6","jiu3","gaai2"] },
            { chars: ["让","我","更","加","担","心","我","状","态"], jp: ["joeng6","ngo5","gang1","gaa1","daam1","sam1","ngo5","zong6","taai3"] },
            { paragraphBreak: true },
            { chars: ["要","是","可","爱"], jp: ["jiu3","si6","ho2","ngoi3"] },
            { chars: ["为","何","无","人","爱","我"], jp: ["wai4","ho4","mou4","jan4","ngoi3","ngo5"] },
            { chars: ["夜","夜","独","自","一","个"], jp: ["je6","je6","duk6","zi6","jat1","go3"] },
            { chars: ["祈","求","谁","来","家","里","坐","坐"], jp: ["kei4", "kau4", "seoi4", "loi4", "gaa1", "leoi5", "zo6", "zo6"] },
            { chars: ["抬","头","望","镜","亦","算","不","失","不","过"], jp: ["toi4","tau4","mong6","geng3","jik6","syun3","bat1","sat1","bat1","gwo3"] },
            { chars: ["到","底","我","什","么","出","错"], jp: ["dou3", "dai2", "ngo5", "sap6", "mo1", "ceot1", "co3"] },
            { paragraphBreak: true },
            { chars: ["要","是","可","爱"], jp: ["jiu3","si6","ho2","ngoi3"] },
            { chars: ["为","何","无","人","爱","我"], jp: ["wai4","ho4","mou4","jan4","ngoi3","ngo5"] },
            { chars: ["夜","夜","独","自","一","个"], jp: ["je6","je6","duk6","zi6","jat1","go3"] },
            { chars: ["回","来","和","墙","壁","唱","着","爱","歌"], jp: ["wui4","loi4","wo4","coeng4","bik1","coeng3","zoek6","ngoi3","go1"] },
            { chars: ["唱","到","自","信","恐","怕","亦","无","多"], jp: ["coeng3","dou3","zi6","seon3","hung2","paa3","jik6","mou4","do1"] },
            { chars: ["连","我","亦","笑","问","凭","什","么"], jp: ["lin4", "ngo5", "jik6", "siu3", "man6", "pang4", "sap6", "mo1"] },
            { paragraphBreak: true },
            { chars: ["是","你","么"], jp: ["si6", "nei5", "mo1"] },
            { chars: ["若","有","人","爱","我"], jp: ["joek6","jau5","jan4","ngoi3","ngo5"] },
            { chars: ["是","你","么"], jp: ["si6", "nei5", "mo1"] },
            { chars: ["这","地","球"], jp: ["ze5","dei6","kau4"] },
            { chars: ["男","孩","如","此","多"], jp: ["naam4","haai4","jyu4","ci2","do1"] },
            { chars: ["情","人","在","哪","儿"], jp: ["cing4","jan4","zoi6","naa5","ji4"] },
            { chars: ["情","人","是","你","么"], jp: ["cing4", "jan4", "si6", "nei5", "mo1"] },
            { paragraphBreak: true },
            { chars: ["要","是","可","爱"], jp: ["jiu3","si6","ho2","ngoi3"] },
            { chars: ["为","何","无","人","爱","我"], jp: ["wai4","ho4","mou4","jan4","ngoi3","ngo5"] },
            { chars: ["夜","夜","独","自","一","个"], jp: ["je6","je6","duk6","zi6","jat1","go3"] },
            { chars: ["祈","求","谁","来","家","里","坐","坐"], jp: ["kei4", "kau4", "seoi4", "loi4", "gaa1", "leoi5", "zo6", "zo6"] },
            { chars: ["抬","头","望","镜","亦","算","不","失","不","过"], jp: ["toi4","tau4","mong6","geng3","jik6","syun3","bat1","sat1","bat1","gwo3"] },
            { chars: ["到","底","我","什","么","出","错"], jp: ["dou3", "dai2", "ngo5", "sap6", "mo1", "ceot1", "co3"] },
            { paragraphBreak: true },
            { chars: ["要","是","可","爱"], jp: ["jiu3","si6","ho2","ngoi3"] },
            { chars: ["为","何","无","人","爱","我"], jp: ["wai4","ho4","mou4","jan4","ngoi3","ngo5"] },
            { chars: ["夜","夜","独","自","一","个"], jp: ["je6","je6","duk6","zi6","jat1","go3"] },
            { chars: ["回","来","和","墙","壁","唱","着","爱","歌"], jp: ["wui4","loi4","wo4","coeng4","bik1","coeng3","zoek6","ngoi3","go1"] },
            { chars: ["唱","到","自","信","恐","怕","亦","无","多"], jp: ["coeng3","dou3","zi6","seon3","hung2","paa3","jik6","mou4","do1"] },
            { chars: ["情","爱","是","决","定","遗","下","我"], jp: ["cing4","ngoi3","si6","kyut3","ding6","wai4","haa6","ngo5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
