// 歌曲：啜泣（live）

(function() {
    const song = {
        id: 497,
        title: "啜泣（live）",
        titleJyutping: ["zyut3","jap1","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "舒文",
        composerJyutping: ["syu1","man4"],
        lyrics: [
            { chars: ["谁","明","白","我","想"], jp: ["seoi4","ming4","baak6","ngo5","soeng2"] },
            { chars: ["想","一","觉","熟","睡"], jp: ["soeng2","jat1","gok3","suk6","seoi6"] },
            { chars: ["谁","料","我","竟"], jp: ["seoi4","liu6","ngo5","ging2"] },
            { chars: ["参","加","这","派","对"], jp: ["caam1","gaa1","ze5","paai3","deoi3"] },
            { chars: ["期","待","你","陪","着","我"], jp: ["kei4","doi6","nei5","pui4","zoek6","ngo5"] },
            { chars: ["不","登","对","都","有","趣"], jp: ["bat1","dang1","deoi3","dou1","jau5","ceoi3"] },
            { chars: ["就","趁","你","快","乐","问","你","喜","欢","谁"], jp: ["zau6","can3","nei5","faai3","lok6","man6","nei5","hei2","fun1","seoi4"] },
            { chars: ["你","却","说","是","否","指","恋","爱","伴","侣"], jp: ["nei5","koek3","syut3","si6","fau2","zi2","lyun2","ngoi3","bun6","leoi5"] },
            { chars: ["若","是","那","种"], jp: ["joek6","si6","naa5","zung2"] },
            { chars: ["自","问","怕","累"], jp: ["zi6","man6","paa3","leoi6"] },
            { chars: ["然","后","我","咬","着","唇","勒","住","眼","泪"], jp: ["jin4","hau6","ngo5","ngaau5","zoek6","seon4","lak6","zyu6","ngaan5","leoi6"] },
            { paragraphBreak: true },
            { chars: ["如","若","我","肯","抚","心","去","自","问"], jp: ["jyu4","joek6","ngo5","hang2","fu2","sam1","heoi3","zi6","man6"] },
            { chars: ["其","实","我","想","得","到","你","一","吻"], jp: ["kei4","sat6","ngo5","soeng2","dak1","dou3","nei5","jat1","man5"] },
            { chars: ["然","后","你","承","认","我"], jp: ["jin4","hau6","nei5","sing4","jing6","ngo5"] },
            { chars: ["我","是","谁","的","候","任"], jp: ["ngo5","si6","seoi4","dik1","hau6","jam6"] },
            { chars: ["就","算","我","已","鉴","定","你","非","好","人"], jp: ["zau6","syun3","ngo5","ji5","gaam3","ding6","nei5","fei1","hou2","jan4"] },
            { chars: ["也","至","少","换","得","到","一","个","烙","印"], jp: ["jaa5","zi3","siu2","wun6","dak1","dou3","jat1","go3","lok3","jan3"] },
            { chars: ["但","是","我","想"], jp: ["daan6","si6","ngo5","soeng2"] },
            { chars: ["并","没","有","问"], jp: ["bing6","mut6","jau5","man6"] },
            { chars: ["其","实","你","这","坏","人"], jp: ["kei4","sat6","nei5","ze5","waai6","jan4"] },
            { chars: ["从","来","未","为","女","生"], jp: ["cung4","loi4","mei6","wai4","neoi5","sang1"] },
            { chars: ["虔","诚","认","真"], jp: ["kin4","sing4","jing6","zan1"] },
            { paragraphBreak: true },
            { chars: ["我","爱","你","这","秘","密"], jp: ["ngo5","ngoi3","nei5","ze5","bei3","mat6"] },
            { chars: ["谁","愿","意","去","证","实"], jp: ["seoi4","jyun6","ji3","heoi3","zing3","sat6"] },
            { chars: ["得","到","这","忧","郁","症"], jp: ["dak1","dou3","ze5","jau1","juk1","zing3"] },
            { chars: ["也","不","委","屈"], jp: ["jaa5","bat1","wai2","wat1"] },
            { chars: ["将","灯","光","关","上","后"], jp: ["zoeng1","dang1","gwong1","gwaan1","soeng6","hau6"] },
            { chars: ["便","放","心","怀","念","你"], jp: ["bin6","fong3","sam1","waai4","nim6","nei5"] },
            { chars: ["只","可","惜","只","够","力","啜","泣"], jp: ["zi2","ho2","sik1","zi2","gau3","lik6","zyut3","jap1"] },
            { chars: ["我","对","你","再","老","实"], jp: ["ngo5","deoi3","nei5","zoi3","lou5","sat6"] },
            { chars: ["难","令","你","变","老","实"], jp: ["naan4","ling6","nei5","bin3","lou5","sat6"] },
            { chars: ["单","恋","者","都","可","以"], jp: ["daan1","lyun2","ze2","dou1","ho2","ji5"] },
            { chars: ["勇","敢","呼","吸"], jp: ["jung5","gam2","fu1","kap1"] },
            { chars: ["趁","你","我","还","未","消","失"], jp: ["can3","nei5","ngo5","waan4","mei6","siu1","sat1"] },
            { chars: ["宁","愿","别","公","开","秘","密"], jp: ["ning4","jyun6","bit6","gung1","hoi1","bei3","mat6"] },
            { chars: ["直","到","末","日"], jp: ["zik6","dou3","mut6","jat6"] },
            { paragraphBreak: true },
            { chars: ["我","爱","你","这","秘","密"], jp: ["ngo5","ngoi3","nei5","ze5","bei3","mat6"] },
            { chars: ["谁","愿","意","去","证","实"], jp: ["seoi4","jyun6","ji3","heoi3","zing3","sat6"] },
            { chars: ["得","到","这","忧","郁","症"], jp: ["dak1","dou3","ze5","jau1","juk1","zing3"] },
            { chars: ["也","不","委","屈"], jp: ["jaa5","bat1","wai2","wat1"] },
            { chars: ["将","灯","光","关","上","后"], jp: ["zoeng1","dang1","gwong1","gwaan1","soeng6","hau6"] },
            { chars: ["便","放","心","怀","念","你"], jp: ["bin6","fong3","sam1","waai4","nim6","nei5"] },
            { chars: ["只","可","惜","只","够","力","啜","泣"], jp: ["zi2","ho2","sik1","zi2","gau3","lik6","zyut3","jap1"] },
            { chars: ["我","对","你","再","老","实"], jp: ["ngo5","deoi3","nei5","zoi3","lou5","sat6"] },
            { chars: ["难","令","你","变","老","实"], jp: ["naan4","ling6","nei5","bin3","lou5","sat6"] },
            { chars: ["单","恋","者","都","可","以"], jp: ["daan1","lyun2","ze2","dou1","ho2","ji5"] },
            { chars: ["勇","敢","呼","吸"], jp: ["jung5","gam2","fu1","kap1"] },
            { chars: ["趁","你","我","还","未","消","失"], jp: ["can3","nei5","ngo5","waan4","mei6","siu1","sat1"] },
            { chars: ["明","白","就","公","开","秘","密"], jp: ["ming4","baak6","zau6","gung1","hoi1","bei3","mat6"] },
            { chars: ["直","到","末","日"], jp: ["zik6","dou3","mut6","jat6"] },
            { paragraphBreak: true },
            { chars: ["其","实","我","想"], jp: ["kei4","sat6","ngo5","soeng2"] },
            { chars: ["躲","于","你","附","近"], jp: ["do2","jyu1","nei5","fu6","gan6"] },
            { chars: ["其","实","我","想"], jp: ["kei4","sat6","ngo5","soeng2"] },
            { chars: ["赌","赌","我","命","运"], jp: ["dou2","dou2","ngo5","ming6","wan6"] },
            { chars: ["然","后","我","想"], jp: ["jin4","hau6","ngo5","soeng2"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
