// 歌曲：好好恋爱

(function() {
    const song = {
        id: 705,
        title: "好好恋爱",
        titleJyutping: ["hou2","hou2","lyun2","ngoi3"],
        artist: "方力申",
        artistJyutping: ["fong1","lik6","san1"],
        lyricist: "方杰",
        lyricistJyutping: ["fong1","git6"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["落","力","为","你","好"], jp: ["lok6","lik6","wai4","nei5","hou2"] },
            { chars: ["得","不","到","分","数"], jp: ["dak1","bat1","dou3","fan1","sou3"] },
            { chars: ["你","决","定","要","跟","他","日","后","同","步"], jp: ["nei5","kyut3","ding6","jiu3","gan1","taa1","jat6","hau6","tung4","bou6"] },
            { chars: ["他","不","懂","爱","惜","你"], jp: ["taa1","bat1","dung2","ngoi3","sik1","nei5"] },
            { chars: ["我","乐","意","操","劳"], jp: ["ngo5","lok6","ji3","cou1","lou4"] },
            { chars: ["还","看","着","你"], jp: ["waan4","hon3","zoek6","nei5"] },
            { chars: ["看","你","在","悬","崖","走","路"], jp: ["hon3","nei5","zoi6","jyun4","ngaai4","zau2","lou6"] },
            { chars: ["他","却","放","下","你"], jp: ["taa1","koek3","fong3","haa6","nei5"] },
            { chars: ["只","照","顾","自","己"], jp: ["zi2","ziu3","gu3","zi6","gei2"] },
            { chars: ["我","这","片","苦","心"], jp: ["ngo5","ze5","pin3","fu2","sam1"] },
            { chars: ["无","人","赞","美"], jp: ["mou4","jan4","zaan3","mei5"] },
            { chars: ["还","不","敢","开","口","不","能","妒","忌"], jp: ["waan4","bat1","gam2","hoi1","hau2","bat1","nang4","dou3","gei6"] },
            { paragraphBreak: true },
            { chars: ["对","你","好"], jp: ["deoi3","nei5","hou2"] },
            { chars: ["无","人","希","罕","我","好"], jp: ["mou4","jan4","hei1","hon2","ngo5","hou2"] },
            { chars: ["无","人","欣","赏","我","好"], jp: ["mou4","jan4","jan1","soeng2","ngo5","hou2"] },
            { chars: ["原","来","你","习","惯","他","一","套"], jp: ["jyun4","loi4","nei5","zaap6","gwaan3","taa1","jat1","tou3"] },
            { chars: ["从","来","没","有"], jp: ["cung4","loi4","mut6","jau5"] },
            { chars: ["爱","我","　","看","得","清","楚","我","知","道"], jp: ["ngoi3","ngo5","","hon3","dak1","cing1","co2","ngo5","zi1","dou3"] },
            { chars: ["不","必","得","到"], jp: ["bat1","bit1","dak1","dou3"] },
            { chars: ["不","妨","陪","衬"], jp: ["bat1","fong4","pui4","can3"] },
            { chars: ["但","愿","为","你","好"], jp: ["daan6","jyun6","wai4","nei5","hou2"] },
            { chars: ["好","　","明","明","比","他","更","好"], jp: ["hou2","","ming4","ming4","bei2","taa1","gang1","hou2"] },
            { chars: ["旁","人","都","知","我","好"], jp: ["pong4","jan4","dou1","zi1","ngo5","hou2"] },
            { chars: ["为","何","你","又","与","他","拥","抱"], jp: ["wai4","ho4","nei5","jau6","jyu5","taa1","jung2","pou5"] },
            { chars: ["来","磨","练","我"], jp: ["loi4","mo4","lin6","ngo5"] },
            { chars: ["我","信","　","有","好","心","得","好","报"], jp: ["ngo5","seon3","","jau5","hou2","sam1","dak1","hou2","bou3"] },
            { chars: ["好","人","　","似","我","问","谁","做","到"], jp: ["hou2","jan4","","ci5","ngo5","man6","seoi4","zou6","dou2"] },
            { paragraphBreak: true },
            { chars: ["是","受","罪","也","好"], jp: ["si6","sau6","zeoi6","jaa5","hou2"] },
            { chars: ["听","听","你","哭","诉"], jp: ["ting1","ting1","nei5","huk1","sou3"] },
            { chars: ["你","说","难","过","总","比","分","手","更","好"], jp: ["nei5","syut3","naan4","gwo3","zung2","bei2","fan1","sau2","gang1","hou2"] },
            { chars: ["你","说","几","多","的","女","主","角"], jp: ["nei5","syut3","gei2","do1","dik1","neoi5","zyu2","gok3"] },
            { chars: ["也","受","过","煎","熬"], jp: ["jaa5","sau6","gwo3","zin1","ngou4"] },
            { chars: ["情","况","坏","到"], jp: ["cing4","fong3","waai6","dou3"] },
            { chars: ["你","信","任","来","年","一","日"], jp: ["nei5","seon3","jam6","loi4","nin4","jat1","jat6"] },
            { chars: ["他","答","应","做","到"], jp: ["taa1","daap3","jing3","zou6","dou2"] },
            { chars: ["通","通","都","做","到"], jp: ["tung1","tung1","dou1","zou6","dou2"] },
            { chars: ["我","也","似","你","的"], jp: ["ngo5","jaa5","ci5","nei5","dik1"] },
            { chars: ["无","从","劝","告"], jp: ["mou4","cung4","hyun3","gou3"] },
            { chars: ["宁","愿","牺","牲","都","不","愿","却","步"], jp: ["ning4","jyun6","hei1","sang1","dou1","bat1","jyun6","koek3","bou6"] },
            { paragraphBreak: true },
            { chars: ["对","你","好"], jp: ["deoi3","nei5","hou2"] },
            { chars: ["无","人","希","罕","我","好"], jp: ["mou4","jan4","hei1","hon2","ngo5","hou2"] },
            { chars: ["无","人","欣","赏","我","好"], jp: ["mou4","jan4","jan1","soeng2","ngo5","hou2"] },
            { chars: ["原","来","你","习","惯","他","一","套"], jp: ["jyun4","loi4","nei5","zaap6","gwaan3","taa1","jat1","tou3"] },
            { chars: ["从","来","没","有"], jp: ["cung4","loi4","mut6","jau5"] },
            { chars: ["爱","我","　","看","得","清","楚","我","知","道"], jp: ["ngoi3","ngo5","","hon3","dak1","cing1","co2","ngo5","zi1","dou3"] },
            { chars: ["不","必","得","到"], jp: ["bat1","bit1","dak1","dou3"] },
            { chars: ["不","妨","陪","衬"], jp: ["bat1","fong4","pui4","can3"] },
            { chars: ["但","愿","为","你","好"], jp: ["daan6","jyun6","wai4","nei5","hou2"] },
            { chars: ["好","　","明","明","比","他","更","好"], jp: ["hou2","","ming4","ming4","bei2","taa1","gang1","hou2"] },
            { chars: ["旁","人","都","知","我","好"], jp: ["pong4","jan4","dou1","zi1","ngo5","hou2"] },
            { chars: ["为","何","你","又","与","他","拥","抱"], jp: ["wai4","ho4","nei5","jau6","jyu5","taa1","jung2","pou5"] },
            { chars: ["来","磨","练","我"], jp: ["loi4","mo4","lin6","ngo5"] },
            { chars: ["我","信","　","有","好","心","得","好","报"], jp: ["ngo5","seon3","","jau5","hou2","sam1","dak1","hou2","bou3"] },
            { chars: ["虽","然","　","这","秒","时","辰","未","到"], jp: ["seoi1","jin4","","ze5","miu5","si4","san4","mei6","dou3"] },
            { paragraphBreak: true },
            { chars: ["我","太","好"], jp: ["ngo5","taai3","hou2"] },
            { chars: ["无","人","珍","惜","我","好"], jp: ["mou4","jan4","zan1","sik1","ngo5","hou2"] },
            { chars: ["无","人","喜","欢","我","好"], jp: ["mou4","jan4","hei2","fun1","ngo5","hou2"] },
            { chars: ["原","来","要","学","会","他","一","套"], jp: ["jyun4","loi4","jiu3","hok6","wui6","taa1","jat1","tou3"] },
            { chars: ["从","来","没","有"], jp: ["cung4","loi4","mut6","jau5"] },
            { chars: ["吻","过","　","记","得","清","楚","我","知","道"], jp: ["man5","gwo3","","gei3","dak1","cing1","co2","ngo5","zi1","dou3"] },
            { chars: ["不","必","得","到"], jp: ["bat1","bit1","dak1","dou3"] },
            { chars: ["不","妨","陪","衬"], jp: ["bat1","fong4","pui4","can3"] },
            { chars: ["但","愿","为","你","好"], jp: ["daan6","jyun6","wai4","nei5","hou2"] },
            { chars: ["好","　","明","明","比","他","更","好"], jp: ["hou2","","ming4","ming4","bei2","taa1","gang1","hou2"] },
            { chars: ["旁","人","都","知","我","好"], jp: ["pong4","jan4","dou1","zi1","ngo5","hou2"] },
            { chars: ["无","人","爱","慕","我","忍","得","到"], jp: ["mou4","jan4","ngoi3","mou6","ngo5","jan2","dak1","dou3"] },
            { chars: ["仍","然","相","信"], jp: ["jing4","jin4","soeng1","seon3"] },
            { chars: ["我","会","　","有","天","终","于","等","到"], jp: ["ngo5","wui6","","jau5","tin1","zung1","jyu1","dang2","dou3"] },
            { chars: ["可","能","　","你","有","日","会","知","道"], jp: ["ho2","nang4","","nei5","jau5","jat6","wui6","zi1","dou3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
