// 歌曲：年度之歌

(function() {
    const song = {
        id: 897,
        title: "年度之歌",
        titleJyutping: ["nin4","dou6","zi1","go1"],
        artist: "谢安琪",
        artistJyutping: ["ze6","on1","kei4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "Christopher Chak",
        composerJyutping: ["","","","","","","","","","","","","","","",""],
        lyrics: [
            { chars: ["曾","经","攀","上","的","天","梯"], jp: ["cang4","ging1","paan1","soeng6","dik1","tin1","tai1"] },
            { chars: ["曾","经","拥","抱","的","身","体"], jp: ["cang4","ging1","jung2","pou5","dik1","san1","tai2"] },
            { chars: ["曾","经","在","乎","一","切"], jp: ["cang4","ging1","zoi6","fu4","jat1","cai3"] },
            { chars: ["被","突","然","摧","毁"], jp: ["bei6","dat6","jin4","ceoi1","wai2"] },
            { chars: ["刹","那","比","沙","更","细"], jp: ["caat3","naa5","bei2","saa1","gang1","sai3"] },
            { chars: ["良","夜","美","景"], jp: ["loeng4","je6","mei5","ging2"] },
            { chars: ["没","原","因","出","了","轨"], jp: ["mut6","jyun4","jan1","ceot1","liu5","gwai2"] },
            { chars: ["来","让","我","知"], jp: ["loi4","joeng6","ngo5","zi1"] },
            { chars: ["一","切","皆","可","放","低"], jp: ["jat1","cai3","gaai1","ho2","fong3","dai1"] },
            { chars: ["还","是","百","载","未","逢","的","美","丽"], jp: ["waan4","si6","baak3","zoi3","mei6","fung4","dik1","mei5","lai6"] },
            { chars: ["得","到","过"], jp: ["dak1","dou3","gwo3"] },
            { chars: ["又","猝","逝"], jp: ["jau6","cyut3","sai6"] },
            { chars: ["也","有","一","种","智","慧"], jp: ["jaa5","jau5","jat1","zung2","zi3","wai3"] },
            { paragraphBreak: true },
            { chars: ["全","年","度","有","几","多","首","歌"], jp: ["cyun4","nin4","dou6","jau5","gei2","do1","sau2","go1"] },
            { chars: ["给","天","天","的","播"], jp: ["kap1","tin1","tin1","dik1","bo3"] },
            { chars: ["给","你","最","愉","快","的","消","磨"], jp: ["kap1","nei5","zeoi3","jyu6","faai3","dik1","siu1","mo4"] },
            { chars: ["流","行","是","一","首","窝","心","的","歌"], jp: ["lau4","hang4","si6","jat1","sau2","wo1","sam1","dik1","go1"] },
            { chars: ["突","然","间","说","过","就","过"], jp: ["dat6","jin4","gaan1","syut3","gwo3","zau6","gwo3"] },
            { paragraphBreak: true },
            { chars: ["谁","曾","是","你","这","一","首","歌"], jp: ["seoi4","cang4","si6","nei5","ze5","jat1","sau2","go1"] },
            { chars: ["你","记","不","清","楚"], jp: ["nei5","gei3","bat1","cing1","co2"] },
            { chars: ["我","看","着","你","离","座"], jp: ["ngo5","hon3","zoek6","nei5","lei4","zo6"] },
            { chars: ["真","高","兴","给","你","爱","护","过"], jp: ["zan1","gou1","hing1","kap1","nei5","ngoi3","wu6","gwo3"] },
            { chars: ["根","本","你","不","欠","我","什","么"], jp: ["gan1","bun2","nei5","bat1","him3","ngo5","sap6","mo1"] },
            { paragraphBreak: true },
            { chars: ["曾","经","拥","有","的","春","季"], jp: ["cang4","ging1","jung2","jau5","dik1","ceon1","gwai3"] },
            { chars: ["曾","经","走","过","的","谷","底"], jp: ["cang4","ging1","zau2","gwo3","dik1","guk1","dai2"] },
            { chars: ["人","生","是","场","兴","替"], jp: ["jan4","sang1","si6","coeng4","hing1","tai3"] },
            { chars: ["忽","高","也","忽","低"], jp: ["fat1","gou1","jaa5","fat1","dai1"] },
            { chars: ["不","输","气","势"], jp: ["bat1","syu1","hei3","sai3"] },
            { paragraphBreak: true },
            { chars: ["全","年","度","有","几","多","首","歌"], jp: ["cyun4","nin4","dou6","jau5","gei2","do1","sau2","go1"] },
            { chars: ["给","天","天","的","播"], jp: ["kap1","tin1","tin1","dik1","bo3"] },
            { chars: ["给","你","最","愉","快","的","消","磨"], jp: ["kap1","nei5","zeoi3","jyu6","faai3","dik1","siu1","mo4"] },
            { chars: ["流","行","是","一","首","窝","心","的","歌"], jp: ["lau4","hang4","si6","jat1","sau2","wo1","sam1","dik1","go1"] },
            { chars: ["突","然","间","说","过","就","过"], jp: ["dat6","jin4","gaan1","syut3","gwo3","zau6","gwo3"] },
            { paragraphBreak: true },
            { chars: ["谁","曾","是","你","这","一","首","歌"], jp: ["seoi4","cang4","si6","nei5","ze5","jat1","sau2","go1"] },
            { chars: ["你","记","不","清","楚"], jp: ["nei5","gei3","bat1","cing1","co2"] },
            { chars: ["我","看","着","你","离","座"], jp: ["ngo5","hon3","zoek6","nei5","lei4","zo6"] },
            { chars: ["真","高","兴","给","你","爱","护","过"], jp: ["zan1","gou1","hing1","kap1","nei5","ngoi3","wu6","gwo3"] },
            { chars: ["根","本","你","不","欠","我","什","么"], jp: ["gan1","bun2","nei5","bat1","him3","ngo5","sap6","mo1"] },
            { paragraphBreak: true },
            { chars: ["谁","曾","是","你","这","一","首","歌"], jp: ["seoi4","cang4","si6","nei5","ze5","jat1","sau2","go1"] },
            { chars: ["你","记","不","清","楚"], jp: ["nei5","gei3","bat1","cing1","co2"] },
            { chars: ["我","看","着","你","离","座"], jp: ["ngo5","hon3","zoek6","nei5","lei4","zo6"] },
            { chars: ["很","高","兴","因","你","灿","烂","过"], jp: ["han2","gou1","hing1","jan1","nei5","caan3","laan6","gwo3"] },
            { chars: ["高","峰","过","总","会","有","下","坡"], jp: ["gou1","fung1","gwo3","zung2","wui6","jau5","haa6","po1"] },
            { paragraphBreak: true },
            { chars: ["回","忆","装","满","的","抽","屉"], jp: ["wui4","jik1","zong1","mun5","dik1","cau1","tai3"] },
            { chars: ["时","光","机","里","的","光","辉"], jp: ["si4","gwong1","gei1","leoi5","dik1","gwong1","fai1"] },
            { chars: ["人","生","艳","如","花","卉"], jp: ["jan4","sang1","jim6","jyu4","faa1","wai2"] },
            { chars: ["但","限","时","美","丽"], jp: ["daan6","haan6","si4","mei5","lai6"] },
            { chars: ["一","览","始","终","无","遗"], jp: ["jat1","laam5","ci2","zung1","mou4","wai4"] },
            { chars: ["回","望","昨","天"], jp: ["wui4","mong6","zok3","tin1"] },
            { chars: ["剧","场","深","不","见","底"], jp: ["kek6","coeng4","sam1","bat1","gin3","dai2"] },
            { chars: ["还","是","有","几","幕","曾","好","好","发","挥"], jp: ["waan4","si6","jau5","gei2","mok6","cang4","hou2","hou2","faat3","fai1"] },
            { chars: ["还","愿","我","懂","下","台","的","美","艺"], jp: ["waan4","jyun6","ngo5","dung2","haa6","toi4","dik1","mei5","ngai6"] },
            { chars: ["鞠","躬","了"], jp: ["guk1","gung1","liu5"] },
            { chars: ["就","退","位"], jp: ["zau6","teoi3","wai6"] },
            { chars: ["起","码","得","到","敬","礼"], jp: ["hei2","maa5","dak1","dou3","ging3","lai5"] },
            { paragraphBreak: true },
            { chars: ["谁","又","妄","想","一","曲","一","世"], jp: ["seoi4","jau6","mong5","soeng2","jat1","kuk1","jat1","sai3"] },
            { chars: ["让","人","忠","心","到","底"], jp: ["joeng6","jan4","zung1","sam1","dou3","dai2"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
