// 歌曲：心之科学

(function() {
    const song = {
        id: 522,
        title: "心之科学",
        titleJyutping: ["sam1","zi1","fo1","hok6"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "翁厚梁/林家谦",
        composerJyutping: ["jung1","hau5","loeng4","","lam4","gaa1","him1"],
        lyrics: [
            { chars: ["分","一","次","手"], jp: ["fan1","jat1","ci3","sau2"] },
            { chars: ["你","大","伤","元","气"], jp: ["nei5","daai6","soeng1","jyun4","hei3"] },
            { chars: ["病","两","世","纪"], jp: ["beng6","loeng5","sai3","gei2"] },
            { chars: ["已","经","细","的"], jp: ["ji5","ging1","sai3","dik1"] },
            { chars: ["越","见","卑","微"], jp: ["jyut6","gin3","bei1","mei4"] },
            { chars: ["他","的","五","官"], jp: ["taa1","dik1","ng5","gun1"] },
            { chars: ["也","并","不","完","美"], jp: ["jaa5","bing6","bat1","jyun4","mei5"] },
            { chars: ["提","前","到","末","期"], jp: ["tai4","cin4","dou3","mut6","kei4"] },
            { chars: ["绝","非","因","你"], jp: ["zyut6","fei1","jan1","nei5"] },
            { chars: ["下","错","棋"], jp: ["haa6","co3","kei4"] },
            { chars: ["曾","多","么"], jp: ["zang1","do1","maa1"] },
            { chars: ["爱","亦","会","腻"], jp: ["ngoi3","jik6","wui6","nei6"] },
            { chars: ["谁","的","心"], jp: ["seoi4","dik1","sam1"] },
            { chars: ["似","随","意","肌"], jp: ["ci5","ceoi4","ji3","gei1"] },
            { paragraphBreak: true },
            { chars: ["情","人"," ","不","爱","你"], jp: ["cing4","jan4","","bat1","ngoi3","nei5"] },
            { chars: ["还"," ","不","爱","你"], jp: ["waan4","","bat1","ngoi3","nei5"] },
            { chars: ["凭","什","么"], jp: ["pang4","sap6","maa1"] },
            { chars: ["否","定","你"], jp: ["fau2","ding6","nei5"] },
            { chars: ["月","光"," ","有","人","捞","起"], jp: ["jyut6","gwong1","","jau5","jan4","laau4","hei2"] },
            { chars: ["有","人","瞧","不","起"], jp: ["jau5","jan4","ciu4","bat1","hei2"] },
            { chars: ["被","爱","概","率"], jp: ["bei6","ngoi3","koi3","seot1"] },
            { chars: ["如","宇","宙"], jp: ["jyu4","jyu5","zau6"] },
            { chars: ["阴","森","诡","秘"], jp: ["jam1","sam1","gwai2","bei3"] },
            { chars: ["神","也","摸","不","透","的"], jp: ["san4","jaa5","mo2","bat1","tau3","dik1"] },
            { chars: ["问","你","怎","么","与","它"], jp: ["man6","nei5","zam2","maa1","jyu5","taa1"] },
            { chars: ["斗","气"], jp: ["dau3","hei3"] },
            { paragraphBreak: true },
            { chars: ["倾","心","变","心"], jp: ["king1","sam1","bin3","sam1"] },
            { chars: ["有","什","么","定","理"], jp: ["jau5","sap6","maa1","ding6","lei5"] },
            { chars: ["缠","绵","有","效","期"], jp: ["cin4","min4","jau5","haau6","kei4"] },
            { chars: ["谁","都","不","似"], jp: ["seoi4","dou1","bat1","ci5"] },
            { chars: ["别","去","比"], jp: ["bit6","heoi3","bei2"] },
            { chars: ["谁","失","恋"], jp: ["seoi4","sat1","lyun2"] },
            { chars: ["要","受","责","备"], jp: ["jiu3","sau6","zaak3","bei6"] },
            { chars: ["何","必","将"], jp: ["ho4","bit1","zoeng1"] },
            { chars: ["责","任","揹","起"], jp: ["zaak3","jam6","bui3","hei2"] },
            { paragraphBreak: true },
            { chars: ["情","人"," ","不","爱","你"], jp: ["cing4","jan4","","bat1","ngoi3","nei5"] },
            { chars: ["还"," ","不","爱","你"], jp: ["waan4","","bat1","ngoi3","nei5"] },
            { chars: ["凭","什","么"], jp: ["pang4","sap6","maa1"] },
            { chars: ["否","定","你"], jp: ["fau2","ding6","nei5"] },
            { chars: ["月","光"," ","有","人","捞","起"], jp: ["jyut6","gwong1","","jau5","jan4","laau4","hei2"] },
            { chars: ["有","人","瞧","不","起"], jp: ["jau5","jan4","ciu4","bat1","hei2"] },
            { chars: ["被","爱","概","率"], jp: ["bei6","ngoi3","koi3","seot1"] },
            { chars: ["如","宇","宙"], jp: ["jyu4","jyu5","zau6"] },
            { chars: ["阴","森","诡","秘"], jp: ["jam1","sam1","gwai2","bei3"] },
            { chars: ["无","法","主","宰","那","些"], jp: ["mou4","faat3","zyu2","zoi2","naa5","se1"] },
            { chars: ["谁","那","么","蠢","与","它"], jp: ["seoi4","naa5","maa1","ceon2","jyu5","taa1"] },
            { chars: ["斗","气"], jp: ["dau3","hei3"] },
            { paragraphBreak: true },
            { chars: ["离","离","合","合"], jp: ["lei4","lei4","hap6","hap6"] },
            { chars: ["百","世","纪"], jp: ["baak3","sai3","gei2"] },
            { chars: ["段","段","看","破"], jp: ["dyun6","dyun6","hon3","po3"] },
            { chars: ["无","常","理"], jp: ["mou4","soeng4","lei5"] },
            { chars: ["不","必"," ","呕","心","沥","血"], jp: ["bat1","bit1","","au2","sam1","lik6","hyut3"] },
            { chars: ["叫","他","爱","你"], jp: ["giu3","taa1","ngoi3","nei5"] },
            { chars: ["有","人","是","独","个"], jp: ["jau5","jan4","si6","duk6","go3"] },
            { chars: ["离","场","才","完","美"], jp: ["lei4","coeng4","coi4","jyun4","mei5"] },
            { paragraphBreak: true },
            { chars: ["无","人","生","哲","理"], jp: ["mou4","jan4","sang1","zit3","lei5"] },
            { chars: ["能","急","救","你"], jp: ["nang4","gap1","gau3","nei5"] },
            { chars: ["唯","独","这","歌"], jp: ["wai4","duk6","ze5","go1"] },
            { chars: ["赠","你"], jp: ["zang6","nei5"] },
            { chars: ["幸","福"," ","既","然","随","机"], jp: ["hang6","fuk1","","gei3","jin4","ceoi4","gei1"] },
            { chars: ["你","为","何","心","死"], jp: ["nei5","wai4","ho4","sam1","sei2"] },
            { chars: ["大","脑","细","胞"], jp: ["daai6","nou5","sai3","baau1"] },
            { chars: ["调","校","着"], jp: ["diu6","haau6","zoek6"] },
            { chars: ["恋","之","分","泌"], jp: ["lyun2","zi1","fan1","bei3"] },
            { chars: ["无","法","阻","他","变","心"], jp: ["mou4","faat3","zo2","taa1","bin3","sam1"] },
            { chars: ["仍","有","胸","襟","永","不"], jp: ["jing4","jau5","hung1","kam1","wing5","bat1"] },
            { chars: ["泄","气"], jp: ["sit3","hei3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
