// 歌曲：我杯茶

(function() {
    const song = {
        id: 477,
        title: "我杯茶",
        titleJyutping: ["ngo5","bui1","caa4"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "林若宁",
        lyricistJyutping: ["lam4","joek6","ning4"],
        composer: "冯彦中",
        composerJyutping: ["fung4","jin6","zung1"],
        lyrics: [
            { chars: ["还","是","年","轻","的","花"], jp: ["waan4","si6","nin4","hing1","dik1","faa1"] },
            { chars: ["多","姿","多","采","的","恋","上","每","个","他"], jp: ["do1","zi1","do1","coi2","dik1","lyun2","soeng6","mui5","go3","taa1"] },
            { chars: ["随","着","年","资","增","加"], jp: ["ceoi4","zoek6","nin4","zi1","zang1","gaa1"] },
            { chars: ["风","干","一","脸","风","雅"], jp: ["fung1","gon1","jat1","lim5","fung1","ngaa5"] },
            { chars: ["拿","热","茶","冲","开","它"], jp: ["naa4","jit6","caa4","cung1","hoi1","taa1"] },
            { chars: ["将","青","春","的","怯","都","喝","下"], jp: ["zoeng1","cing1","ceon1","dik1","hip3","dou1","hot3","haa6"] },
            { chars: ["时","间","自","会","淡","化","多","少","创","疤"], jp: ["si4","gaan1","zi6","wui6","daam6","faa3","do1","siu2","cong3","baa1"] },
            { paragraphBreak: true },
            { chars: ["重","踏","繁","嚣","的","街"], jp: ["cung5","daap6","faan4","hiu1","dik1","gaai1"] },
            { chars: ["终","于","可","清","醒","想","到","每","个","他"], jp: ["zung1","jyu1","ho2","cing1","sing2","soeng2","dou3","mui5","go3","taa1"] },
            { chars: ["辛","酸","的","苦","水","有","助","人","消","化"], jp: ["san1","syun1","dik1","fu2","seoi2","jau5","zo6","jan4","siu1","faa3"] },
            { chars: ["给","他","声","音","灌","醉","令","我","豁","出","去"], jp: ["kap1","taa1","sing1","jam1","gun3","zeoi3","ling6","ngo5","kut3","ceot1","heoi3"] },
            { chars: ["情","人","内","在","容","易","被","美","化"], jp: ["cing4","jan4","noi6","zoi6","jung4","ji6","bei6","mei5","faa3"] },
            { chars: ["潇","洒","的","印","象","能","永","久","吗"], jp: ["siu1","saa2","dik1","jan3","zoeng6","nang4","wing5","gau2","maa1"] },
            { paragraphBreak: true },
            { chars: ["还","需","感","慨","甚","么"], jp: ["waan4", "seoi1", "gam2", "koi3", "sam6", "mo1"] },
            { chars: ["曾","经","拥","有","几","段","情"], jp: ["zang1","ging1","jung2","jau5","gei2","dyun6","cing4"] },
            { chars: ["难","堪","总","有","过"], jp: ["naan4","ham1","zung2","jau5","gwo3"] },
            { chars: ["每","段","浓","和","淡","喝","一","杯","便","过"], jp: ["mui5","dyun6","nung4","wo4","daam6","hot3","jat1","bui1","bin6","gwo3"] },
            { chars: ["流","过","段","段","激","情"], jp: ["lau4","gwo3","dyun6","dyun6","gik1","cing4"] },
            { chars: ["情","感","蒸","发","了","领","会","年","青","的","错"], jp: ["cing4","gam2","zing1","faat3","liu5","ling5","wui6","nin4","cing1","dik1","co3"] },
            { chars: ["答","谢","别","人","来","过"], jp: ["daap3","ze6","bit6","jan4","loi4","gwo3"] },
            { chars: ["以","感","情","犯","错"], jp: ["ji5","gam2","cing4","faan6","co3"] },
            { paragraphBreak: true },
            { chars: ["忘","掉","繁","嚣","的","街"], jp: ["mong4","diu6","faan4","hiu1","dik1","gaai1"] },
            { chars: ["终","于","可","找","到","杯","里","这","个","家"], jp: ["zung1","jyu1","ho2","zaau2","dou3","bui1","lei5","ze5","go3","gaa1"] },
            { chars: ["青","花","跟","紫","砂","也","造","型","清","雅"], jp: ["cing1","faa1","gan1","zi2","saa1","jaa5","zou6","jing4","cing1","ngaa5"] },
            { chars: ["新","生","活","很","美","满","在","我","客","厅","里"], jp: ["san1","sang1","wut6","han2","mei5","mun5","zoi6","ngo5","haak3","teng1","lei5"] },
            { chars: ["回","味","段","段","缘","份","在","变","化"], jp: ["wui4","mei6","dyun6","dyun6","jyun4","fan6","zoi6","bin3","faa3"] },
            { chars: ["身","份","可","放","下","忘","记","牵","挂"], jp: ["san1","fan6","ho2","fong3","haa6","mong4","gei3","hin1","gwaa3"] },
            { paragraphBreak: true },
            { chars: ["还","需","感","慨","甚","么"], jp: ["waan4", "seoi1", "gam2", "koi3", "sam6", "mo1"] },
            { chars: ["曾","经","拥","有","几","段","情"], jp: ["zang1","ging1","jung2","jau5","gei2","dyun6","cing4"] },
            { chars: ["难","堪","总","有","过"], jp: ["naan4","ham1","zung2","jau5","gwo3"] },
            { chars: ["每","段","浓","和","淡","喝","一","杯","便","过"], jp: ["mui5","dyun6","nung4","wo4","daam6","hot3","jat1","bui1","bin6","gwo3"] },
            { chars: ["流","过","段","段","激","情"], jp: ["lau4","gwo3","dyun6","dyun6","gik1","cing4"] },
            { chars: ["情","感","蒸","发","了","领","会","年","青","的","错"], jp: ["cing4","gam2","zing1","faat3","liu5","ling5","wui6","nin4","cing1","dik1","co3"] },
            { chars: ["答","谢","别","人","来","过"], jp: ["daap3","ze6","bit6","jan4","loi4","gwo3"] },
            { chars: ["以","感","情","犯","错"], jp: ["ji5","gam2","cing4","faan6","co3"] },
            { paragraphBreak: true },
            { chars: ["甘","甘","苦","苦","的","相","亲","相","爱","后","来","又","如","何"], jp: ["gam1","gam1","fu2","fu2","dik1","soeng1","can1","soeng1","ngoi3","hau6","loi4","jau6","jyu4","ho4"] },
            { chars: ["能","逐","年","逐","年","沉","淀","过"], jp: ["nang4","zuk6","nin4","zuk6","nin4","cam4","din6","gwo3"] },
            { chars: ["没","有","烟","没","有","火","留","下","我"], jp: ["mut6","jau5","jin1","mut6","jau5","fo2","lau4","haa6","ngo5"] },
            { paragraphBreak: true },
            { chars: ["回","忆","中","有","甚","么"], jp: ["wui4", "jik1", "zung1", "jau5", "sam6", "mo1"] },
            { chars: ["曾","经","拥","有","都","动","人"], jp: ["zang1","ging1","jung2","jau5","dou1","dung6","jan4"] },
            { chars: ["和","我","庆","祝","过"], jp: ["wo4","ngo5","hing3","zuk1","gwo3"] },
            { chars: ["往","日","情","人","节","至","少","感","动","过"], jp: ["wong5","jat6","cing4","jan4","zit3","zi3","siu2","gam2","dung6","gwo3"] },
            { chars: ["流","过","段","段","激","情"], jp: ["lau4","gwo3","dyun6","dyun6","gik1","cing4"] },
            { chars: ["留","不","低","每","个","亦","能","留","低","一","课"], jp: ["lau4","bat1","dai1","mui5","go3","jik6","nang4","lau4","dai1","jat1","fo3"] },
            { chars: ["眼","泪","未","曾","流","过"], jp: ["ngaan5","leoi6","mei6","zang1","lau4","gwo3"] },
            { chars: ["我","怎","明","白","我"], jp: ["ngo5","zam2","ming4","baak6","ngo5"] },
            { chars: ["快","乐","混","和","难","过"], jp: ["faai3","lok6","wan6","wo4","naan4","gwo3"] },
            { chars: ["这","杯","茶","是","我"], jp: ["ze5","bui1","caa4","si6","ngo5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
