// 歌曲：打回原形

(function() {
    const song = {
        id: 617,
        title: "打回原形",
        titleJyutping: ["daa2","wui4","jyun4","jing4"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "阿飞",
        composerJyutping: ["aa3","fei1"],
        lyrics: [
            { chars: ["不","要","着","灯"], jp: ["bat1","jiu3","zoek6","dang1"] },
            { chars: ["能","否","先","跟","我"], jp: ["nang4","fau2","sin1","gan1","ngo5"] },
            { chars: ["摸","黑"," ","吻","一","吻"], jp: ["mo2","hak1","","man5","jat1","man5"] },
            { chars: ["如","果","我"], jp: ["jyu4","gwo2","ngo5"] },
            { chars: ["露","出","了","真","身"], jp: ["lou6","ceot1","liu5","zan1","san1"] },
            { chars: ["可","会","被","抱","紧"], jp: ["ho2","wui6","bei6","pou5","gan2"] },
            { chars: ["惊","破","坏","气","氛"], jp: ["ging1","po3","waai6","hei3","fan1"] },
            { chars: ["谁","都","不","知","我"], jp: ["seoi4","dou1","bat1","zi1","ngo5"] },
            { chars: ["心","底","有","多","暗"], jp: ["sam1","dai2","jau5","do1","am3"] },
            { chars: ["如","本","性"], jp: ["jyu4","bun2","sing3"] },
            { chars: ["是","这","么","低","等"], jp: ["si6","ze5","mo1","dai1","dang2"] },
            { chars: ["怎","跟","你","相","衬"], jp: ["zam2","gan1","nei5","soeng1","can3"] },
            { paragraphBreak: true },
            { chars: ["情","人","如","若","很","好","奇"], jp: ["cing4","jan4","jyu4","joek6","han2","hou3","kei4"] },
            { chars: ["要","有","被","我","吓","怕","的","准","备"], jp: ["jiu3","jau5","bei6","ngo5","haak3","paa3","dik1","zeon2","bei6"] },
            { chars: ["试","问","谁","可"], jp: ["si3","man6","seoi4","ho2"] },
            { chars: ["洁","白","无","比"], jp: ["git3","baak6","mou4","bei2"] },
            { chars: ["如","何","承","受","这","好","奇"], jp: ["jyu4","ho4","sing4","sau6","ze5","hou3","kei4"] },
            { chars: ["答","案","大","概","似","剃","刀","锋","利"], jp: ["daap3","on3","daai6","koi3","ci5","tai3","dou1","fung1","lei6"] },
            { chars: ["愿","赤","裸","相","对","时"], jp: ["jyun6","cek3","lo2","soeng1","deoi3","si4"] },
            { chars: ["能","够","不","伤","你"], jp: ["nang4","gau3","bat1","soeng1","nei5"] },
            { paragraphBreak: true },
            { chars: ["当","你","未","放","心"], jp: ["dong1","nei5","mei6","fong3","sam1"] },
            { chars: ["或","者","先","不","要","走","得","这","么","近"], jp: ["waak6","ze2","sin1","bat1","jiu3","zau2","dak1","ze5","mo1","gan6"] },
            { chars: ["如","果","我"], jp: ["jyu4","gwo2","ngo5"] },
            { chars: ["露","出","斑","点","满","身"], jp: ["lou6","ceot1","baan1","dim2","mun5","san1"] },
            { chars: ["可","马","上","转","身"], jp: ["ho2","maa5","soeng6","zyun2","san1"] },
            { chars: ["早","这","样","降","生"], jp: ["zou2","ze5","joeng6","gong3","sang1"] },
            { chars: ["如","基","因","可","以"], jp: ["jyu4","gei1","jan1","ho2","ji5"] },
            { chars: ["分","解","再","装","嵌"], jp: ["fan1","gaai2","zoi3","zong1","ham3"] },
            { chars: ["重","组","我"], jp: ["cung5","zou2","ngo5"] },
            { chars: ["什","么","都","不","要","紧"], jp: ["sap6","mo1","dou1","bat1","jiu3","gan2"] },
            { chars: ["假","使","你","兴","奋"], jp: ["gaa2","si2","nei5","hing1","fan5"] },
            { paragraphBreak: true },
            { chars: ["情","人","如","若","很","好","奇"], jp: ["cing4","jan4","jyu4","joek6","han2","hou3","kei4"] },
            { chars: ["要","有","被","我","吓","怕","的","准","备"], jp: ["jiu3","jau5","bei6","ngo5","haak3","paa3","dik1","zeon2","bei6"] },
            { chars: ["试","问","谁","可"], jp: ["si3","man6","seoi4","ho2"] },
            { chars: ["洁","白","无","比"], jp: ["git3","baak6","mou4","bei2"] },
            { chars: ["如","何","承","受","这","好","奇"], jp: ["jyu4","ho4","sing4","sau6","ze5","hou3","kei4"] },
            { chars: ["答","案","大","概","似","剃","刀","锋","利"], jp: ["daap3","on3","daai6","koi3","ci5","tai3","dou1","fung1","lei6"] },
            { chars: ["但","你","知","一","个","人"], jp: ["daan6","nei5","zi1","jat1","go3","jan4"] },
            { chars: ["谁","没","有","隐","秘"], jp: ["seoi4","mut6","jau5","jan2","bei3"] },
            { paragraphBreak: true },
            { chars: ["几","双","手"], jp: ["gei2","soeng1","sau2"] },
            { chars: ["几","双","腿"], jp: ["gei2","soeng1","teoi2"] },
            { chars: ["方","会","令","你","喜","欢","我"], jp: ["fong1","wui6","ling6","nei5","hei2","fun1","ngo5"] },
            { chars: ["顺","利","无","阻"], jp: ["seon6","lei6","mou4","zo2"] },
            { chars: ["你","爱","我"], jp: ["nei5","ngoi3","ngo5"] },
            { chars: ["别","管","我"], jp: ["bit6","gun2","ngo5"] },
            { chars: ["几","双","耳","朵"], jp: ["gei2","soeng1","ji5","do2"] },
            { chars: ["共","我","放","心","探","戈"], jp: ["gung6","ngo5","fong3","sam1","taam3","gwo1"] },
            { paragraphBreak: true },
            { chars: ["情","人","如","若","很","好","奇"], jp: ["cing4","jan4","jyu4","joek6","han2","hou3","kei4"] },
            { chars: ["要","有","被","我","吓","怕","的","准","备"], jp: ["jiu3","jau5","bei6","ngo5","haak3","paa3","dik1","zeon2","bei6"] },
            { chars: ["试","问","谁","可"], jp: ["si3","man6","seoi4","ho2"] },
            { chars: ["洁","白","无","比"], jp: ["git3","baak6","mou4","bei2"] },
            { chars: ["如","何","承","受","这","好","奇"], jp: ["jyu4","ho4","sing4","sau6","ze5","hou3","kei4"] },
            { chars: ["你","有","没","有","爱","我","的","准","备"], jp: ["nei5","jau5","mut6","jau5","ngoi3","ngo5","dik1","zeon2","bei6"] },
            { chars: ["若","你","喜","欢","怪","人"], jp: ["joek6","nei5","hei2","fun1","gwaai3","jan4"] },
            { chars: ["其","实","我","很","美"], jp: ["kei4","sat6","ngo5","han2","mei5"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
