// 歌曲：无人知道双子座（live）

(function() {
    const song = {
        id: 475,
        title: "无人知道双子座（live）",
        titleJyutping: ["mou4","jan4","zi1","dou6","soeng1","zi2","zo6","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "Cousin Fung",
        composerJyutping: ["","","","","","","","","","",""],
        lyrics: [
            { chars: ["其","实","我","都","不","够","自","信"], jp: ["kei4","sat6","ngo5","dou1","bat1","gau3","zi6","seon3"] },
            { chars: ["才","大","放","烟","花","去","冒","充"], jp: ["coi4","daai6","fong3","jin1","faa1","heoi3","mou6","cung1"] },
            { chars: ["可","惜","多","可","爱"], jp: ["ho2","sik1","do1","ho2","ngoi3"] },
            { chars: ["未","吸","引","著","你"], jp: ["mei6","kap1","jan5","zyu3","nei5"] },
            { chars: ["为","何","照","直","说"], jp: ["wai4","ho4","ziu3","zik6","syut3"] },
            { chars: ["不","兜","不","转"], jp: ["bat1","dau1","bat1","zyun2"] },
            { chars: ["我","不","懂"], jp: ["ngo5","bat1","dung2"] },
            { paragraphBreak: true },
            { chars: ["其","实","我","只","想","你","望","我"], jp: ["kei4","sat6","ngo5","zi2","soeng2","nei5","mong6","ngo5"] },
            { chars: ["才","待","你","苛","刻","到","密","不","通","风"], jp: ["coi4","doi6","nei5","ho1","hak1","dou3","mat6","bat1","tung1","fung1"] },
            { chars: ["相","反","的","把","戏"], jp: ["soeng1","faan2","dik1","baa2","hei3"] },
            { chars: ["最","后","一","发","不","中"], jp: ["zeoi3","hau6","jat1","faat3","bat1","zung1"] },
            { chars: ["自","怜","也","没","用"], jp: ["zi6","lin4","jaa5","mut6","jung6"] },
            { chars: ["讨","好","过","万","人"], jp: ["tou2","hou2","gwo3","maan6","jan4"] },
            { chars: ["但","诱","惑","你","失","准"], jp: ["daan6","jau5","waak6","nei5","sat1","zeon2"] },
            { paragraphBreak: true },
            { chars: ["不","会","有","人","说"], jp: ["bat1","wui6","jau5","jan4","syut3"] },
            { chars: ["明","天","带","我","蜜","月"], jp: ["ming4","tin1","daai3","ngo5","mat6","jyut6"] },
            { chars: ["谁","知","双","子","的","心","也","盼","望","能","被","当","真"], jp: ["seoi4","zi1","soeng1","zi2","dik1","sam1","jaa5","paan3","mong6","nang4","bei6","dong1","zan1"] },
            { chars: ["讲","句","笑","就","算"], jp: ["gong2","geoi3","siu3","zau6","syun3"] },
            { chars: ["伪","装","很","不","上","心"], jp: ["ngai6","zong1","han2","bat1","soeng6","sam1"] },
            { chars: ["但","半","夜","还","是","很","在","意"], jp: ["daan6","bun3","je6","waan4","si6","han2","zoi6","ji3"] },
            { chars: ["错","过","那","戏","份"], jp: ["co3","gwo3","naa5","hei3","fan6"] },
            { paragraphBreak: true },
            { chars: ["谁","亦","说","双","子","太","善","变"], jp: ["seoi4","jik6","syut3","soeng1","zi2","taai3","sin6","bin3"] },
            { chars: ["谁","亦","怨","双","子","怕","闷"], jp: ["seoi4","jik6","jyun3","soeng1","zi2","paa3","mun6"] },
            { chars: ["贪","新","鲜"], jp: ["taam1","san1","sin1"] },
            { chars: ["他","的","专","一"], jp: ["taa1","dik1","zyun1","jat1"] },
            { chars: ["你","擦","掉","所","有","金","箔"], jp: ["nei5","caat3","diu6","so2","jau5","gam1","bok6"] },
            { chars: ["便","能","够","复","现"], jp: ["bin6","nang4","gau3","fuk6","jin6"] },
            { chars: ["可","惜","也","没","谁"], jp: ["ho2","sik1","jaa5","mut6","seoi4"] },
            { chars: ["又","够","耐","性","识","穿"], jp: ["jau6","gau3","noi6","sing3","sik1","cyun1"] },
            { paragraphBreak: true },
            { chars: ["不","会","有","人","说"], jp: ["bat1","wui6","jau5","jan4","syut3"] },
            { chars: ["明","天","带","我","蜜","月"], jp: ["ming4","tin1","daai3","ngo5","mat6","jyut6"] },
            { chars: ["谁","知","双","子","的","心","也","盼","望","能","被","当","真"], jp: ["seoi4","zi1","soeng1","zi2","dik1","sam1","jaa5","paan3","mong6","nang4","bei6","dong1","zan1"] },
            { chars: ["讲","句","笑","就","算"], jp: ["gong2","geoi3","siu3","zau6","syun3"] },
            { chars: ["伪","装","很","不","上","心"], jp: ["ngai6","zong1","han2","bat1","soeng6","sam1"] },
            { chars: ["但","半","夜","还","是","会","伤","心"], jp: ["daan6","bun3","je6","waan4","si6","wui6","soeng1","sam1"] },
            { chars: ["不","被","人","亲","吻"], jp: ["bat1","bei6","jan4","can1","man5"] },
            { paragraphBreak: true },
            { chars: ["花","心","过","万","人"], jp: ["faa1","sam1","gwo3","maan6","jan4"] },
            { chars: ["独","对","著","你","专","心"], jp: ["duk6","deoi3","zyu3","nei5","zyun1","sam1"] },
            { paragraphBreak: true },
            { chars: ["风","相","怕","被","困"], jp: ["fung1","soeng1","paa3","bei6","kwan3"] },
            { chars: ["人","品","看","似","薄","幸"], jp: ["jan4","ban2","hon3","ci5","bok6","hang6"] },
            { chars: ["谁","知","双","子","把","感","性","脆","弱"], jp: ["seoi4","zi1","soeng1","zi2","baa2","gam2","sing3","ceoi3","joek6"] },
            { chars: ["藏","在","最","深"], jp: ["cong4","zoi6","zeoi3","sam1"] },
            { chars: ["不","要","以","为","我","外","表","喜","欢","创","新"], jp: ["bat1","jiu3","ji5","wai4","ngo5","ngoi6","biu2","hei2","fun1","cong3","san1"] },
            { chars: ["内","里","便","同","时","够","摩","登"], jp: ["noi6","lei5","bin6","tung4","si4","gau3","mo1","dang1"] },
            { chars: ["不","用","人","亲","吻"], jp: ["bat1","jung6","jan4","can1","man5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
