// 歌曲：日与夜

(function() {
    const song = {
        id: 686,
        title: "日与夜",
        titleJyutping: ["jat6","jyu5","je6"],
        artist: "林忆莲",
        artistJyutping: ["lam4","jik1","lin4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "陈辉阳",
        composerJyutping: ["can4","fai1","joeng4"],
        lyrics: [
            { paragraphBreak: true },
            { paragraphBreak: true },
            { chars: ["我","爱","你","快","了","一","点"], jp: ["ngo5","ngoi3","nei5","faai3","liu5","jat1","dim2"] },
            { chars: ["你","发","现","慢","了","点"], jp: ["nei5","faat3","jin6","maan6","liu5","dim2"] },
            { chars: ["某","天","我","吻","过","你","腮","边"], jp: ["mau5","tin1","ngo5","man5","gwo3","nei5","soi1","bin1"] },
            { chars: ["连","情","节","也","扰","乱"], jp: ["lin4","cing4","zit3","jaa5","jiu2","lyun6"] },
            { chars: ["最","好","全","部","记","忆","收","起"], jp: ["zeoi3","hou2","cyun4","bou6","gei3","jik1","sau1","hei2"] },
            { chars: ["终","会","淡","忘","你","的","脸"], jp: ["zung1","wui6","daam6","mong4","nei5","dik1","lim5"] },
            { paragraphBreak: true },
            { chars: ["如","果","盛","世","之","恋","到","日","落","时","就","结","束"], jp: ["jyu4","gwo2","sing6","sai3","zi1","lyun2","dou3","jat6","lok6","si4","zau6","git3","cuk1"] },
            { chars: ["开","遍","全","城","灯","火"], jp: ["hoi1","pin3","cyun4","sing4","dang1","fo2"] },
            { chars: ["照","亮","了","天","际"], jp: ["ziu3","loeng6","liu5","tin1","zai3"] },
            { chars: ["试","问","白","昼","会","否","不","完"], jp: ["si3","man6","baak6","zau3","wui6","fau2","bat1","jyun4"] },
            { chars: ["继","续","热","闹","象","下","午","两","点"], jp: ["gai3","zuk6","jit6","naau6","zoeng6","haa6","ng5","loeng5","dim2"] },
            { chars: ["若","我","不","出","家","门"], jp: ["joek6","ngo5","bat1","ceot1","gaa1","mun4"] },
            { chars: ["钟","表","摔","破"], jp: ["zung1","biu2","seot1","po3"] },
            { chars: ["窗","廉","紧","闭","着"], jp: ["coeng1","lim4","gan2","bai3","zoek6"] },
            { chars: ["时","间","会","不","会","暂","停"], jp: ["si4","gaan1","wui6","bat1","wui6","zaam6","ting4"] },
            { chars: ["停","在","夜","半","三","点"], jp: ["ting4","zoi6","je6","bun3","saam1","dim2"] },
            { paragraphBreak: true },
            { chars: ["与","你","约","错","钟","点"], jp: ["jyu5","nei5","joek3","co3","zung1","dim2"] },
            { chars: ["命","运","都","改","编"], jp: ["ming6","wan6","dou1","goi2","pin1"] },
            { chars: ["我","爱","你","快","了","一","点"], jp: ["ngo5","ngoi3","nei5","faai3","liu5","jat1","dim2"] },
            { chars: ["你","发","现","慢","了","点"], jp: ["nei5","faat3","jin6","maan6","liu5","dim2"] },
            { chars: ["也","许","我","怕","错","过","今","天"], jp: ["jaa5","heoi2","ngo5","paa3","co3","gwo3","gam1","tin1"] },
            { chars: ["人","潮","将","彼","此","盖","掩"], jp: ["jan4","ciu4","zoeng1","bei2","ci2","goi3","jim2"] },
            { chars: ["永","远","擦","过","你","身","边"], jp: ["wing5","jyun5","caat3","gwo3","nei5","san1","bin1"] },
            { chars: ["碰","上","仍","遇","不","见"], jp: ["pung3","soeng5","jing4","jyu6","bat1","gin3"] },
            { paragraphBreak: true },
            { chars: ["如","果","盛","世","之","恋","到","日","落","时","就","结","束"], jp: ["jyu4","gwo2","sing6","sai3","zi1","lyun2","dou3","jat6","lok6","si4","zau6","git3","cuk1"] },
            { chars: ["开","遍","全","城","灯","火"], jp: ["hoi1","pin3","cyun4","sing4","dang1","fo2"] },
            { chars: ["照","亮","了","天","际"], jp: ["ziu3","loeng6","liu5","tin1","zai3"] },
            { chars: ["试","问","白","昼","会","否","不","完"], jp: ["si3","man6","baak6","zau3","wui6","fau2","bat1","jyun4"] },
            { chars: ["继","续","热","闹","象","下","午","两","点"], jp: ["gai3","zuk6","jit6","naau6","zoeng6","haa6","ng5","loeng5","dim2"] },
            { chars: ["若","我","不","出","家","门"], jp: ["joek6","ngo5","bat1","ceot1","gaa1","mun4"] },
            { chars: ["钟","表","摔","破"], jp: ["zung1","biu2","seot1","po3"] },
            { chars: ["窗","廉","紧","闭","着"], jp: ["coeng1","lim4","gan2","bai3","zoek6"] },
            { chars: ["时","间","会","不","会","暂","停"], jp: ["si4","gaan1","wui6","bat1","wui6","zaam6","ting4"] },
            { chars: ["能","让","我","末","做","的","做","完"], jp: ["nang4","joeng6","ngo5","mut6","zou6","dik1","zou6","jyun4"] },
            { paragraphBreak: true },
            { chars: ["也","许","你","我","会","分","开"], jp: ["jaa5","heoi2","nei5","ngo5","wui6","fan1","hoi1"] },
            { chars: ["共","度","着","一","生"], jp: ["gung6","dou6","zoek6","jat1","sang1"] },
            { chars: ["像","日","夜","等","不","到","黎","明","黄","昏"], jp: ["zoeng6","jat6","je6","dang2","bat1","dou3","lai4","ming4","wong4","fan1"] },
            { chars: ["于","无","聊","时","路","过","的","篮","球","场","上"], jp: ["jyu1","mou4","liu4","si4","lou6","gwo3","dik1","laam4","kau4","coeng4","soeng6"] },
            { chars: ["于","玩","乐","后","经","过","的","便","利","店","中"], jp: ["jyu1","wun6","lok6","hau6","ging1","gwo3","dik1","bin6","lei6","dim3","zung1"] },
            { chars: ["于","静","默","地","铁"], jp: ["jyu1","zing6","mak6","dei6","tit3"] },
            { chars: ["于","寂","寞","路","边"], jp: ["jyu1","zik6","mok6","lou6","bin1"] },
            { chars: ["都","落","力","地","找","你","的","迷","途","情","感"], jp: ["dou1","lok6","lik6","dei6","zaau2","nei5","dik1","mai4","tou4","cing4","gam2"] },
            { paragraphBreak: true },
            { chars: ["当","你","我","错","过","今","天"], jp: ["dong1","nei5","ngo5","co3","gwo3","gam1","tin1"] },
            { chars: ["人","潮","将","彼","此","盖","掩"], jp: ["jan4","ciu4","zoeng1","bei2","ci2","goi3","jim2"] },
            { chars: ["仍","期","望","有","生","一","天"], jp: ["jing4","kei4","mong6","jau5","sang1","jat1","tin1"] },
            { chars: ["跟","你","有","缘","吻","一","遍"], jp: ["gan1","nei5","jau5","jyun4","man5","jat1","pin3"] },
            { paragraphBreak: true },
            { chars: ["与","你","约","错","终","点"], jp: ["jyu5","nei5","joek3","co3","zung1","dim2"] },
            { chars: ["再","邂","逅","是","那","天"], jp: ["zoi3","haai5","hau6","si6","naa5","tin1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
