// 歌曲：最佳损友

(function() {
    const song = {
        id: 971,
        title: "最佳损友",
        titleJyutping: ["zeoi3","gaai1","syun2","jau5"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "Eric Kwok",
        composerJyutping: ["","","","","","","","",""],
        lyrics: [
            { chars: ["朋","友","我","当","你","一","秒","朋","友"], jp: ["pang4","jau5","ngo5","dong1","nei5","jat1","miu5","pang4","jau5"] },
            { chars: ["朋","友","我","当","你","一","世","朋","友"], jp: ["pang4","jau5","ngo5","dong1","nei5","jat1","sai3","pang4","jau5"] },
            { chars: ["奇","怪","过","去","再","不","堪","回","首"], jp: ["kei4","gwaai3","gwo3","heoi3","zoi3","bat1","ham1","wui4","sau2"] },
            { chars: ["怀","缅","时","时","其","实","还","有"], jp: ["waai4","min5","si4","si4","kei4","sat6","waan4","jau5"] },
            { paragraphBreak: true },
            { chars: ["朋","友","你","试","过","将","我","营","救"], jp: ["pang4","jau5","nei5","si3","gwo3","zoeng1","ngo5","jing4","gau3"] },
            { chars: ["朋","友","你","试","过","把","我","批","斗"], jp: ["pang4","jau5","nei5","si3","gwo3","baa2","ngo5","pai1","dau3"] },
            { chars: ["无","法","再","与","你","交","心","联","手"], jp: ["mou4","faat3","zoi3","jyu5","nei5","gaau1","sam1","lyun4","sau2"] },
            { chars: ["毕","竟","难","得","有","过","最","佳","损","友"], jp: ["bat1","ging2","naan4","dak1","jau5","gwo3","zeoi3","gaai1","syun2","jau5"] },
            { paragraphBreak: true },
            { chars: ["从","前","共","你","促","膝","把","酒","倾","通","宵","都","不","够"], jp: ["cung4","cin4","gung6","nei5","cuk1","sat1","baa2","zau2","king1","tung1","siu1","dou1","bat1","gau3"] },
            { chars: ["我","有","痛","快","过","你","有","没","有"], jp: ["ngo5","jau5","tung3","faai3","gwo3","nei5","jau5","mut6","jau5"] },
            { chars: ["很","多","东","西","今","生","只","可","给","你"], jp: ["han2","do1","dung1","sai1","gam1","sang1","zi2","ho2","kap1","nei5"] },
            { chars: ["保","守","至","到","永","久"], jp: ["bou2","sau2","zi3","dou3","wing5","gau2"] },
            { chars: ["别","人","如","何","明","白","透"], jp: ["bit6","jan4","jyu4","ho4","ming4","baak6","tau3"] },
            { chars: ["实","实","在","在","踏","入","过","我","宇","宙"], jp: ["sat6","sat6","zoi6","zoi6","daap6","jap6","gwo3","ngo5","jyu5","zau6"] },
            { chars: ["即","使","相","处","到","有","个","裂","口"], jp: ["zik1","si2","soeng1","cyu5","dou3","jau5","go3","lit6","hau2"] },
            { chars: ["命","运","决","定","了","以","后","再","没","法","聚","头"], jp: ["ming6","wan6","kyut3","ding6","liu5","ji5","hau6","zoi3","mut6","faat3","zeoi6","tau4"] },
            { chars: ["但","说","过","去","却","那","样","厚"], jp: ["daan6","syut3","gwo3","heoi3","koek3","naa5","joeng6","hau5"] },
            { paragraphBreak: true },
            { chars: ["问","我","有","没","有"], jp: ["man6","ngo5","jau5","mut6","jau5"] },
            { chars: ["确","实","也","没","有","一","直","躲","避","的","借","口"], jp: ["kok3","sat6","jaa5","mut6","jau5","jat1","zik6","do2","bei6","dik1","ze3","hau2"] },
            { chars: ["非","甚","么","大","仇"], jp: ["fei1","sam6","mo1","daai6","sau4"] },
            { chars: ["为","何","旧","知","己","在","最","后","变","不","到","老","友"], jp: ["wai4","ho4","gau6","zi1","gei2","zoi6","zeoi3","hau6","bin3","bat1","dou3","lou5","jau5"] },
            { chars: ["不","知","你","是","我","敌","友"], jp: ["bat1","zi1","nei5","si6","ngo5","dik6","jau5"] },
            { chars: ["已","没","法","望","透"], jp: ["ji5","mut6","faat3","mong6","tau3"] },
            { chars: ["被","推","着","走","跟","着","生","活","流"], jp: ["bei6","teoi1","zoek6","zau2","gan1","zoek6","sang1","wut6","lau4"] },
            { chars: ["来","年","陌","生","的","是","昨","日","最","亲","的","某","某"], jp: ["loi4","nin4","mak6","sang1","dik1","si6","zok3","jat6","zeoi3","can1","dik1","mau5","mau5"] },
            { paragraphBreak: true },
            { chars: ["生","死","之","交","当","天","不","知","罕","有"], jp: ["sang1","sei2","zi1","gaau1","dong1","tin1","bat1","zi1","hon2","jau5"] },
            { chars: ["到","你","变","节","了","至","觉","未","够"], jp: ["dou3","nei5","bin3","zit3","liu5","zi3","gok3","mei6","gau3"] },
            { chars: ["多","想","一","天","彼","此","都","不","追","究"], jp: ["do1","soeng2","jat1","tin1","bei2","ci2","dou1","bat1","zeoi1","gau3"] },
            { chars: ["相","邀","再","次","喝","酒"], jp: ["soeng1","jiu1","zoi3","ci3","hot3","zau2"] },
            { chars: ["待","葡","萄","成","熟","透"], jp: ["doi6","pou4","tou4","sing4","suk6","tau3"] },
            { chars: ["但","是","命","运","入","面","每","个","邂","逅"], jp: ["daan6","si6","ming6","wan6","jap6","min6","mui5","go3","haai5","hau6"] },
            { chars: ["一","起","走","到","了","某","个","路","口"], jp: ["jat1","hei2","zau2","dou3","liu5","mau5","go3","lou6","hau2"] },
            { chars: ["是","敌","与","是","友","各","自","也","没","有","自","由"], jp: ["si6","dik6","jyu5","si6","jau5","gok3","zi6","jaa5","mut6","jau5","zi6","jau4"] },
            { chars: ["位","置","变","了"], jp: ["wai6","zi3","bin3","liu5"] },
            { chars: ["各","有","队","友"], jp: ["gok3","jau5","deoi6","jau5"] },
            { paragraphBreak: true },
            { chars: ["问","我","有","没","有"], jp: ["man6","ngo5","jau5","mut6","jau5"] },
            { chars: ["确","实","也","没","有","一","直","躲","避","的","借","口"], jp: ["kok3","sat6","jaa5","mut6","jau5","jat1","zik6","do2","bei6","dik1","ze3","hau2"] },
            { chars: ["非","甚","么","大","仇"], jp: ["fei1","sam6","mo1","daai6","sau4"] },
            { chars: ["为","何","旧","知","己","在","最","后","变","不","到","老","友"], jp: ["wai4","ho4","gau6","zi1","gei2","zoi6","zeoi3","hau6","bin3","bat1","dou3","lou5","jau5"] },
            { chars: ["不","知","你","是","我","敌","友"], jp: ["bat1","zi1","nei5","si6","ngo5","dik6","jau5"] },
            { chars: ["已","没","法","望","透"], jp: ["ji5","mut6","faat3","mong6","tau3"] },
            { chars: ["被","推","着","走","跟","着","生","活","流"], jp: ["bei6","teoi1","zoek6","zau2","gan1","zoek6","sang1","wut6","lau4"] },
            { chars: ["来","年","陌","生","的","是","昨","日","最","亲","的","某","某"], jp: ["loi4","nin4","mak6","sang1","dik1","si6","zok3","jat6","zeoi3","can1","dik1","mau5","mau5"] },
            { chars: ["早","知","解","散","后","各","自","有","际","遇","作","导","游"], jp: ["zou2","zi1","gaai2","saan3","hau6","gok3","zi6","jau5","zai3","jyu6","zok3","dou6","jau4"] },
            { chars: ["奇","就","奇","在","接","受","了","各","自","有","路","走"], jp: ["kei4","zau6","kei4","zoi6","zip3","sau6","liu5","gok3","zi6","jau5","lou6","zau2"] },
            { chars: ["却","没","人","像","你","让","我","眼","泪","背","着","流"], jp: ["koek3","mut6","jan4","zoeng6","nei5","joeng6","ngo5","ngaan5","leoi6","bui3","zoek6","lau4"] },
            { chars: ["严","重","似","情","侣","讲","分","手"], jp: ["jim4","cung5","ci5","cing4","leoi5","gong2","fan1","sau2"] },
            { paragraphBreak: true },
            { chars: ["有","没","有"], jp: ["jau5","mut6","jau5"] },
            { chars: ["确","实","也","没","有","一","直","躲","避","的","借","口"], jp: ["kok3","sat6","jaa5","mut6","jau5","jat1","zik6","do2","bei6","dik1","ze3","hau2"] },
            { chars: ["非","甚","么","大","仇"], jp: ["fei1","sam6","mo1","daai6","sau4"] },
            { chars: ["为","何","旧","知","己","在","最","后","变","不","到","老","友"], jp: ["wai4","ho4","gau6","zi1","gei2","zoi6","zeoi3","hau6","bin3","bat1","dou3","lou5","jau5"] },
            { paragraphBreak: true },
            { chars: ["不","知","你","又","有","没","有"], jp: ["bat1","zi1","nei5","jau6","jau5","mut6","jau5"] },
            { chars: ["挂","念","这","旧","友"], jp: ["gwaa3","nim6","ze5","gau6","jau5"] },
            { chars: ["或","者","自","己","早","就","想","通","透"], jp: ["waak6","ze2","zi6","gei2","zou2","zau6","soeng2","tung1","tau3"] },
            { chars: ["来","年","陌","生","的","是","昨","日","最","亲","的","某","某"], jp: ["loi4","nin4","mak6","sang1","dik1","si6","zok3","jat6","zeoi3","can1","dik1","mau5","mau5"] },
            { chars: ["总","好","于","那","日","我","没","有","没","有","遇","过","某","某"], jp: ["zung2","hou2","jyu1","naa5","jat6","ngo5","mut6","jau5","mut6","jau5","jyu6","gwo3","mau5","mau5"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
