// 歌曲：最冷一天

(function() {
    const song = {
        id: 899,
        title: "最冷一天",
        titleJyutping: ["zeoi3","laang5","jat1","tin1"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "陈小霞",
        composerJyutping: ["can4","siu2","haa4"],
        lyrics: [
            { chars: ["如","果","伤","感","比","快","乐","更","深"], jp: ["jyu4","gwo2","soeng1","gam2","bei2","faai3","lok6","gang1","sam1"] },
            { chars: ["但","愿","我","一","样","伴","你","行"], jp: ["daan6","jyun6","ngo5","jat1","joeng6","bun6","nei5","hang4"] },
            { chars: ["当","抬","头","迎","面","总","有","密","云"], jp: ["dong1","toi4","tau4","jing4","min6","zung2","jau5","mat6","wan4"] },
            { chars: ["只","要","认","得","你","再","没","有","遗","憾"], jp: ["zi2","jiu3","jing6","dak1","nei5","zoi3","mut6","jau5","wai4","ham6"] },
            { paragraphBreak: true },
            { chars: ["如","果","苦","笑","比","眼","泪","更","真"], jp: ["jyu4","gwo2","fu2","siu3","bei2","ngaan5","leoi6","gang1","zan1"] },
            { chars: ["但","愿","笑","声","像","一","滴","滴","吻"], jp: ["daan6","jyun6","siu3","sing1","zoeng6","jat1","dik6","dik6","man5"] },
            { chars: ["如","明","日","好","景","忽","远","忽","近"], jp: ["jyu4","ming4","jat6","hou2","ging2","fat1","jyun5","fat1","gan6"] },
            { chars: ["仍","愿","抱","着","这","份","情","没","疑","问"], jp: ["jing4","jyun6","pou5","zoek6","ze5","fan6","cing4","mut6","ji4","man6"] },
            { paragraphBreak: true },
            { chars: ["任","面","前","时","代","再","低","气","温"], jp: ["jam6","min6","cin4","si4","doi6","zoi3","dai1","hei3","wan1"] },
            { chars: ["多","么","的","庆","幸"], jp: ["do1","mo1","dik1","hing3","hang6"] },
            { chars: ["长","夜","无","需","一","个","人"], jp: ["coeng4","je6","mou4","seoi1","jat1","go3","jan4"] },
            { chars: ["任","未","来","存","在","哪","个","可","能"], jp: ["jam6","mei6","loi4","cyun4","zoi6","naa5","go3","ho2","nang4"] },
            { chars: ["和","你","亦","是"], jp: ["wo4","nei5","jik6","si6"] },
            { chars: ["最","后","那","对","变","更"], jp: ["zeoi3","hau6","naa5","deoi3","bin3","gang1"] },
            { paragraphBreak: true },
            { chars: ["唯","愿","在","剩","余","光","线","面","前"], jp: ["wai4","jyun6","zoi6","sing6","jyu4","gwong1","sin3","min6","cin4"] },
            { chars: ["留","下","两","眼","为","见","你","一","面"], jp: ["lau4","haa6","loeng5","ngaan5","wai4","gin3","nei5","jat1","min6"] },
            { chars: ["仍","然","能","相","拥","才","不","怕","骤","变"], jp: ["jing4","jin4","nang4","soeng1","jung2","coi4","bat1","paa3","zaau6","bin3"] },
            { chars: ["但","怕","思","念"], jp: ["daan6","paa3","si1","nim6"] },
            { paragraphBreak: true },
            { chars: ["唯","愿","会","及","时","拥","抱","入","眠"], jp: ["wai4","jyun6","wui6","kap6","si4","jung2","pou5","jap6","min4"] },
            { chars: ["留","住","这","世","上","最","暖","一","面"], jp: ["lau4","zyu6","ze5","sai3","soeng6","zeoi3","nyun5","jat1","min6"] },
            { chars: ["茫","茫","人","海","取","暖","渡","过"], jp: ["mong4","mong4","jan4","hoi2","ceoi2","nyun5","dou6","gwo3"] },
            { chars: ["最","冷","一","天"], jp: ["zeoi3","laang5","jat1","tin1"] },
            { paragraphBreak: true },
            { chars: ["如","果","苦","笑","比","眼","泪","更","真"], jp: ["jyu4","gwo2","fu2","siu3","bei2","ngaan5","leoi6","gang1","zan1"] },
            { chars: ["但","愿","笑","声","像","一","滴","滴","吻"], jp: ["daan6","jyun6","siu3","sing1","zoeng6","jat1","dik6","dik6","man5"] },
            { chars: ["如","明","日","好","景","忽","远","忽","近"], jp: ["jyu4","ming4","jat6","hou2","ging2","fat1","jyun5","fat1","gan6"] },
            { chars: ["仍","愿","抱","着","这","份","情","没","疑","问"], jp: ["jing4","jyun6","pou5","zoek6","ze5","fan6","cing4","mut6","ji4","man6"] },
            { paragraphBreak: true },
            { chars: ["任","面","前","时","代","再","低","气","温"], jp: ["jam6","min6","cin4","si4","doi6","zoi3","dai1","hei3","wan1"] },
            { chars: ["多","么","的","庆","幸"], jp: ["do1","mo1","dik1","hing3","hang6"] },
            { chars: ["长","夜","无","需","一","个","人"], jp: ["coeng4","je6","mou4","seoi1","jat1","go3","jan4"] },
            { chars: ["任","未","来","存","在","哪","个","可","能"], jp: ["jam6","mei6","loi4","cyun4","zoi6","naa5","go3","ho2","nang4"] },
            { chars: ["和","你","亦","是"], jp: ["wo4","nei5","jik6","si6"] },
            { chars: ["最","后","那","对","变","更"], jp: ["zeoi3","hau6","naa5","deoi3","bin3","gang1"] },
            { paragraphBreak: true },
            { chars: ["唯","愿","在","剩","余","光","线","面","前"], jp: ["wai4","jyun6","zoi6","sing6","jyu4","gwong1","sin3","min6","cin4"] },
            { chars: ["留","下","两","眼","为","见","你","一","面"], jp: ["lau4","haa6","loeng5","ngaan5","wai4","gin3","nei5","jat1","min6"] },
            { chars: ["仍","然","能","相","拥","才","不","怕","骤","变"], jp: ["jing4","jin4","nang4","soeng1","jung2","coi4","bat1","paa3","zaau6","bin3"] },
            { chars: ["但","怕","思","念"], jp: ["daan6","paa3","si1","nim6"] },
            { paragraphBreak: true },
            { chars: ["唯","愿","会","及","时","拥","抱","入","眠"], jp: ["wai4","jyun6","wui6","kap6","si4","jung2","pou5","jap6","min4"] },
            { chars: ["留","住","这","世","上","最","暖","一","面"], jp: ["lau4","zyu6","ze5","sai3","soeng6","zeoi3","nyun5","jat1","min6"] },
            { chars: ["茫","茫","人","海","取","暖","渡","过"], jp: ["mong4","mong4","jan4","hoi2","ceoi2","nyun5","dou6","gwo3"] },
            { chars: ["最","冷","一","天"], jp: ["zeoi3","laang5","jat1","tin1"] },
            { paragraphBreak: true },
            { chars: ["唯","愿","在","剩","余","光","线","面","前"], jp: ["wai4","jyun6","zoi6","sing6","jyu4","gwong1","sin3","min6","cin4"] },
            { chars: ["留","下","两","眼","为","见","你","一","面"], jp: ["lau4","haa6","loeng5","ngaan5","wai4","gin3","nei5","jat1","min6"] },
            { chars: ["仍","然","能","相","拥","才","不","怕","骤","变"], jp: ["jing4","jin4","nang4","soeng1","jung2","coi4","bat1","paa3","zaau6","bin3"] },
            { chars: ["但","怕","思","念"], jp: ["daan6","paa3","si1","nim6"] },
            { paragraphBreak: true },
            { chars: ["唯","愿","会","及","时","拥","抱","入","眠"], jp: ["wai4","jyun6","wui6","kap6","si4","jung2","pou5","jap6","min4"] },
            { chars: ["留","住","这","世","上","最","暖","一","面"], jp: ["lau4","zyu6","ze5","sai3","soeng6","zeoi3","nyun5","jat1","min6"] },
            { chars: ["茫","茫","人","海","取","暖","渡","过"], jp: ["mong4","mong4","jan4","hoi2","ceoi2","nyun5","dou6","gwo3"] },
            { chars: ["最","冷","一","天"], jp: ["zeoi3","laang5","jat1","tin1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
