// 歌曲：末日

(function() {
    const song = {
        id: 941,
        title: "末日",
        titleJyutping: ["mut6","jat6"],
        artist: "王菀之",
        artistJyutping: ["wong4","jyun2","zi1"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "王菀之",
        composerJyutping: ["wong4","jyun2","zi1"],
        lyrics: [
            { chars: ["明","晨","天","将","会","塌","下","来","吧"], jp: ["ming4","san4","tin1","zoeng1","wui6","taap3","haa6","loi4","baa6"] },
            { chars: ["突","然","你","我","爱","的","一","切"], jp: ["dat6","jin4","nei5","ngo5","ngoi3","dik1","jat1","cai3"] },
            { chars: ["未","曾","爱","够","已","火","化"], jp: ["mei6","cang4","ngoi3","gau3","ji5","fo2","faa3"] },
            { paragraphBreak: true },
            { chars: ["传","闻"," ","的","审","判","马","上","来","吧"], jp: ["cyun4","man4","","dik1","sam2","pun3","maa5","soeng6","loi4","baa6"] },
            { chars: ["面","前","有","数","百","种","讲","法","难","分","真","假"], jp: ["min6","cin4","jau5","sou3","baak3","zung2","gong2","faat3","naan4","fan1","zan1","gaa2"] },
            { paragraphBreak: true },
            { chars: ["这","末","日","理","论"], jp: ["ze5","mut6","jat6","lei5","leon6"] },
            { chars: ["像","提","我"], jp: ["zoeng6","tai4","ngo5"] },
            { chars: ["过","得","好","吗"], jp: ["gwo3","dak1","hou2","maa1"] },
            { chars: ["日","子"," ","若","果","不","多","了"], jp: ["jat6","zi2","","joek6","gwo2","bat1","do1","liu5"] },
            { chars: ["还","想","怎","花"], jp: ["waan4","soeng2","zam2","faa1"] },
            { paragraphBreak: true },
            { chars: ["如","果","祸","与","福","都","躲","不","过"], jp: ["jyu4","gwo2","wo6","jyu5","fuk1","dou1","do2","bat1","gwo3"] },
            { chars: ["就","每","天","当","没","明","天"], jp: ["zau6","mui5","tin1","dong1","mut6","ming4","tin1"] },
            { chars: ["捉","紧","爱","人","过"], jp: ["zuk1","gan2","ngoi3","jan4","gwo3"] },
            { chars: ["将","生","活","还","给","我"], jp: ["zoeng1","sang1","wut6","waan4","kap1","ngo5"] },
            { chars: ["做","每","天","必","修","功","课"], jp: ["zou6","mui5","tin1","bit1","sau1","gung1","fo3"] },
            { chars: ["就","算","知","岁","月","无","多"], jp: ["zau6","syun3","zi1","seoi3","jyut6","mou4","do1"] },
            { chars: ["无","憾","的","生","存","过"], jp: ["mou4","ham6","dik1","sang1","cyun4","gwo3"] },
            { chars: ["在","爱","惜","中","离","座","已","经","不","错"], jp: ["zoi6","ngoi3","sik1","zung1","lei4","zo6","ji5","ging1","bat1","co3"] },
            { paragraphBreak: true },
            { chars: ["如","常"," ","不","可","以","失","方","吋","吗"], jp: ["jyu4","soeng4","","bat1","ho2","ji5","sat1","fong1","cyun3","maa1"] },
            { chars: ["尽","回","你","我","那","些","职","责"], jp: ["zeon6","wui4","nei5","ngo5","naa5","se1","zik1","zaak3"] },
            { chars: ["限","期","到","了","也","优","雅"], jp: ["haan6","kei4","dou3","liu5","jaa5","jau1","ngaa5"] },
            { paragraphBreak: true },
            { chars: ["假","设","悲","观","放","大","了","的","话"], jp: ["gaa2","cit3","bei1","gun1","fong3","daai6","liu5","dik1","waa6"] },
            { chars: ["蔓","延","世","界","气","氛","只","有","沉","郁","孤","寡"], jp: ["maan6","jin4","sai3","gaai3","hei3","fan1","zi2","jau5","cam4","juk1","gu1","gwaa2"] },
            { paragraphBreak: true },
            { chars: ["这","末","日","理","论"], jp: ["ze5","mut6","jat6","lei5","leon6"] },
            { chars: ["预","言","到"], jp: ["jyu6","jin4","dou3"] },
            { chars: ["那","么","可","怕"], jp: ["naa5","mo1","ho2","paa3"] },
            { chars: ["无","辜"," ","或","者","讲","不","上"], jp: ["mou4","gu1","","waak6","ze2","gong2","bat1","soeng6"] },
            { chars: ["无","奈","不","假"], jp: ["mou4","noi6","bat1","gaa2"] },
            { paragraphBreak: true },
            { chars: ["如","果","祸","与","福","都","躲","不","过"], jp: ["jyu4","gwo2","wo6","jyu5","fuk1","dou1","do2","bat1","gwo3"] },
            { chars: ["就","每","天","当","没","明","天"], jp: ["zau6","mui5","tin1","dong1","mut6","ming4","tin1"] },
            { chars: ["捉","紧","爱","人","过"], jp: ["zuk1","gan2","ngoi3","jan4","gwo3"] },
            { chars: ["将","生","活","还","给","我"], jp: ["zoeng1","sang1","wut6","waan4","kap1","ngo5"] },
            { chars: ["做","每","天","必","修","功","课"], jp: ["zou6","mui5","tin1","bit1","sau1","gung1","fo3"] },
            { chars: ["就","算","知","岁","月","无","多"], jp: ["zau6","syun3","zi1","seoi3","jyut6","mou4","do1"] },
            { chars: ["无","憾","的","生","存","过"], jp: ["mou4","ham6","dik1","sang1","cyun4","gwo3"] },
            { chars: ["遇","上","这","好","时","代"], jp: ["jyu6","soeng5","ze5","hou2","si4","doi6"] },
            { chars: ["有","这","双","你","我"], jp: ["jau5","ze5","soeng1","nei5","ngo5"] },
            { paragraphBreak: true },
            { chars: ["非","走","不","可","时"], jp: ["fei1","zau2","bat1","ho2","si4"] },
            { chars: ["非","走","不","可"], jp: ["fei1","zau2","bat1","ho2"] },
            { chars: ["散","落","茫","茫","银","河"], jp: ["saan3","lok6","mong4","mong4","ngan4","ho4"] },
            { chars: ["万","年","后"], jp: ["maan6","nin4","hau6"] },
            { chars: ["没","有","我"], jp: ["mut6","jau5","ngo5"] },
            { chars: ["谁","可","救","助"], jp: ["seoi4","ho2","gau3","zo6"] },
            { chars: ["最","后"," ","谁","亦","会","流","过","重","要","是","留","影","过"], jp: ["zeoi3","hau6","","seoi4","jik6","wui6","lau4","gwo3","zung6","jiu3","si6","lau4","jing2","gwo3"] },
            { paragraphBreak: true },
            { chars: ["如","果","祸","与","福","都","躲","不","过"], jp: ["jyu4","gwo2","wo6","jyu5","fuk1","dou1","do2","bat1","gwo3"] },
            { chars: ["就","每","天","当","没","明","天"], jp: ["zau6","mui5","tin1","dong1","mut6","ming4","tin1"] },
            { chars: ["捉","紧","爱","人","过"], jp: ["zuk1","gan2","ngoi3","jan4","gwo3"] },
            { chars: ["将","生","活","还","给","我"], jp: ["zoeng1","sang1","wut6","waan4","kap1","ngo5"] },
            { chars: ["别","教","恐","慌","击","倒","我"], jp: ["bit6","gaau3","hung2","fong1","gik1","dou2","ngo5"] },
            { chars: ["就","算","知","岁","月","无","多"], jp: ["zau6","syun3","zi1","seoi3","jyut6","mou4","do1"] },
            { chars: ["平","实","的","生","存"], jp: ["ping4","sat6","dik1","sang1","cyun4"] },
            { chars: ["每","天","好","好","过"], jp: ["mui5","tin1","hou2","hou2","gwo3"] },
            { chars: ["很","坏","之","中","等","最","好"], jp: ["han2","waai6","zi1","zung1","dang2","zeoi3","hou2"] },
            { chars: ["也","许","它","计","错"], jp: ["jaa5","heoi2","taa1","gai3","co3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
