// 歌曲：渐渐

(function() {
    const song = {
        id: 596,
        title: "渐渐",
        titleJyutping: ["zim6","zim6"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "陈咏谦",
        lyricistJyutping: ["can4","wing6","him1"],
        composer: "张杰邦",
        composerJyutping: ["zoeng1","git6","bong1"],
        lyrics: [
            { chars: ["在","夜","晚"], jp: ["zoi6","je6","maan5"] },
            { chars: ["说","早","晨"], jp: ["syut3","zou2","san4"] },
            { chars: ["闲","谈","后"], jp: ["haan4","taam4","hau6"] },
            { chars: ["你","更","像","别","人"], jp: ["nei5","gang1","zoeng6","bit6","jan4"] },
            { chars: ["字","幕","里"], jp: ["zi6","mok6","leoi5"] },
            { chars: ["说","冬","日","灰","暗"], jp: ["syut3","dung1","jat6","fui1","am3"] },
            { chars: ["回","答","你"], jp: ["wui4","daap3","nei5"] },
            { chars: ["这","边","的","气","氛"], jp: ["ze5","bin1","dik1","hei3","fan1"] },
            { paragraphBreak: true },
            { chars: ["就","像","你"], jp: ["zau6","zoeng6","nei5"] },
            { chars: ["已","记","不","起","了"], jp: ["ji5","gei3","bat1","hei2","liu5"] },
            { chars: ["连","怀","旧"], jp: ["lin4","waai4","gau6"] },
            { chars: ["也","格","外","寂","寥"], jp: ["jaa5","gaak3","ngoi6","zik6","liu4"] },
            { chars: ["杂","物","里"], jp: ["zaap6","mat6","leoi5"] },
            { chars: ["遗","物","和","旧","照"], jp: ["wai4","mat6","wo4","gau6","ziu3"] },
            { chars: ["谁","变","卖"], jp: ["seoi4","bin3","maai6"] },
            { chars: ["谁","弃","掉"], jp: ["seoi4","hei3","diu6"] },
            { chars: ["谁","看","到","破","晓"], jp: ["seoi4","hon3","dou3","po3","hiu2"] },
            { paragraphBreak: true },
            { chars: ["渐","渐","我","甚","么","都","不","想","知","道"], jp: ["zim6","zim6","ngo5","sam6","mo1","dou1","bat1","soeng2","zi1","dou3"] },
            { chars: ["我","觉","得","迷","失","竟","比","醒","觉","好"], jp: ["ngo5","gok3","dak1","mai4","sat1","ging2","bei2","sing2","gok3","hou2"] },
            { chars: ["渐","渐","我","离","开","都","不","想","宣","布"], jp: ["zim6","zim6","ngo5","lei4","hoi1","dou1","bat1","soeng2","syun1","bou3"] },
            { chars: ["怕","记","忆"], jp: ["paa3","gei3","jik1"] },
            { chars: ["最","后","变","话","题"], jp: ["zeoi3","hau6","bin3","waa6","tai4"] },
            { chars: ["太","俗","套"], jp: ["taai3","zuk6","tou3"] },
            { paragraphBreak: true },
            { chars: ["别","让","我"], jp: ["bit6","joeng6","ngo5"] },
            { chars: ["再","失","眠"], jp: ["zoi3","sat1","min4"] },
            { chars: ["沉","迷","后"], jp: ["cam4","mai4","hau6"] },
            { chars: ["有","美","梦","未","圆"], jp: ["jau5","mei5","mung6","mei6","jyun4"] },
            { chars: ["现","实","里"], jp: ["jin6","sat6","leoi5"] },
            { chars: ["你","飘","荡","很","远"], jp: ["nei5","piu1","dong6","han2","jyun5"] },
            { chars: ["还","劝","我"], jp: ["waan4","hyun3","ngo5"] },
            { chars: ["不","应","该","眷","恋"], jp: ["bat1","jing3","goi1","gyun3","lyun2"] },
            { paragraphBreak: true },
            { chars: ["但","是","我"], jp: ["daan6","si6","ngo5"] },
            { chars: ["却","看","得","穿","了"], jp: ["koek3","hon3","dak1","cyun1","liu5"] },
            { chars: ["谁","承","诺"], jp: ["seoi4","sing4","nok6"] },
            { chars: ["似","信","念","动","摇"], jp: ["ci5","seon3","nim6","dung6","jiu4"] },
            { chars: ["背","诵","了"], jp: ["bui3","zung6","liu5"] },
            { chars: ["闲","话","和","玩","笑"], jp: ["haan4","waa6","wo4","waan4","siu3"] },
            { chars: ["忘","记","吧"], jp: ["mong4","gei3","baa6"] },
            { chars: ["谁","记","住"], jp: ["seoi4","gei3","zyu6"] },
            { chars: ["谁","要","我","发","表"], jp: ["seoi4","jiu3","ngo5","faat3","biu2"] },
            { paragraphBreak: true },
            { chars: ["渐","渐","我","甚","么","都","不","想","知","道"], jp: ["zim6","zim6","ngo5","sam6","mo1","dou1","bat1","soeng2","zi1","dou3"] },
            { chars: ["我","觉","得","迷","失","竟","比","醒","觉","好"], jp: ["ngo5","gok3","dak1","mai4","sat1","ging2","bei2","sing2","gok3","hou2"] },
            { chars: ["渐","渐","我","离","开","都","不","想","宣","布"], jp: ["zim6","zim6","ngo5","lei4","hoi1","dou1","bat1","soeng2","syun1","bou3"] },
            { chars: ["怕","记","忆"], jp: ["paa3","gei3","jik1"] },
            { chars: ["最","后","变","话","题"], jp: ["zeoi3","hau6","bin3","waa6","tai4"] },
            { chars: ["太","俗","套"], jp: ["taai3","zuk6","tou3"] },
            { paragraphBreak: true },
            { chars: ["寂","寞"," ","寂","寞","出","于","你","的","空","白"], jp: ["zik6","mok6","","zik6","mok6","ceot1","jyu1","nei5","dik1","hung1","baak6"] },
            { chars: ["剩","下","我","被","记","忆","掌","掴"], jp: ["sing6","haa6","ngo5","bei6","gei3","jik1","zoeng2","gwaak3"] },
            { chars: ["如","留","下","语","录","谁","来","看"], jp: ["jyu4","lau4","haa6","jyu5","luk6","seoi4","loi4","hon3"] },
            { chars: ["怀","念","只","可","铺","满","被","单"], jp: ["waai4","nim6","zi2","ho2","pou1","mun5","bei6","daan1"] },
            { paragraphBreak: true },
            { chars: ["渐","渐","我","闻","歌","都","不","想","起","舞"], jp: ["zim6","zim6","ngo5","man4","go1","dou1","bat1","soeng2","hei2","mou5"] },
            { chars: ["我","觉","得","我","失","去","一","切","知","觉","极","美","好"], jp: ["ngo5","gok3","dak1","ngo5","sat1","heoi3","jat1","cai3","zi1","gok3","gik6","mei5","hou2"] },
            { chars: ["浑","噩","哪","及","记","得","恐","怖"], jp: ["wan4","ngok6","naa5","kap6","gei3","dak1","hung2","bou3"] },
            { chars: ["记","得","种","种","感","觉"], jp: ["gei3","dak1","zung2","zung2","gam2","gok3"] },
            { chars: ["但","欠","你","的","厮","守","到","老"], jp: ["daan6","him3","nei5","dik1","si1","sau2","dou3","lou5"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
