// 歌曲：漂流教室

(function() {
    const song = {
        id: 643,
        title: "漂流教室",
        titleJyutping: ["piu1","lau4","gaau3","sat1"],
        artist: "古巨基",
        artistJyutping: ["gu2","geoi6","gei1"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "张佳添",
        composerJyutping: ["zoeng1","gaai1","tim1"],
        lyrics: [
            { chars: ["谁","自","愿","恨","成","世"], jp: ["seoi4","zi6","jyun6","han6","seng4","sai3"] },
            { chars: ["爱","情","不","等","于","一","切"], jp: ["ngoi3","cing4","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["共","聚","又","离","开"], jp: ["gung6","zeoi6","jau6","lei4","hoi1"] },
            { chars: ["从","来","并","未","学","到","可","以","发","誓"], jp: ["cung4","loi4","bing6","mei6","hok6","dou3","ho2","ji5","faat3","sai6"] },
            { chars: ["可","抱","起","来","亦","抛","得","低"], jp: ["ho2","pou5","hei2","loi4","jik6","paau1","dak1","dai1"] },
            { chars: ["但","学","费","都","真","的","太","贵"], jp: ["daan6","hok6","fai3","dou1","zan1","dik1","taai3","gwai3"] },
            { paragraphBreak: true },
            { chars: ["如","果","没","有","初","恋","感","动","经","过"], jp: ["jyu4","gwo2","mut6","jau5","co1","lyun2","gam2","dung6","ging1","gwo3"] },
            { chars: ["下","个","怎","会","爱","得","死","我"], jp: ["haa6","go3","zam2","wui6","ngoi3","dak1","sei2","ngo5"] },
            { chars: ["种","种","因","果","这","日","才","有","我"], jp: ["zung2","zung2","jan1","gwo2","ze5","jat6","coi4","jau5","ngo5"] },
            { chars: ["情","实","在","太","多"], jp: ["cing4","sat6","zoi6","taai3","do1"] },
            { paragraphBreak: true },
            { chars: ["如","果","失","恋","失","得","不","够","折","堕"], jp: ["jyu4","gwo2","sat1","lyun2","sat1","dak1","bat1","gau3","zit3","do6"] },
            { chars: ["何","来","这","刹","那","够","勇","敢","的","我"], jp: ["ho4","loi4","ze5","caat3","naa5","gau3","jung5","gam2","dik1","ngo5"] },
            { chars: ["所","有","伴","侣","都","有","份","教","我"], jp: ["so2","jau5","bun6","leoi5","dou1","jau5","fan2","gaau3","ngo5"] },
            { chars: ["曾","太","过","拼","命","爱"], jp: ["cang4","taai3","gwo3","ping3","ming6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["压","力","大","到","彼","此","多","么","好","也","不","得","不","分","开"], jp: ["aat3","lik6","daai6","dou3","bei2","ci2","do1","mo1","hou2","jaa5","bat1","dak1","bat1","fan1","hoi1"] },
            { chars: ["试","过","友","情","拿","来","暂","借","单","恋","多","悲","哀"], jp: ["si3","gwo3","jau5","cing4","naa4","loi4","zaam6","ze3","daan1","lyun2","do1","bei1","oi1"] },
            { chars: ["大","概"," ","其","实","要","最","真","心","说","声"], jp: ["daai6","koi3","","kei4","sat6","jiu3","zeoi3","zan1","sam1","syut3","sing1"] },
            { chars: ["多","谢","爱"], jp: ["do1","ze6","ngoi3"] },
            { chars: ["学","到","的","多","精","彩"], jp: ["hok6","dou3","dik1","do1","zing1","coi2"] },
            { paragraphBreak: true },
            { chars: ["谁","又","是","做","人","世"], jp: ["seoi4","jau6","si6","zou6","jan4","sai3"] },
            { chars: ["眼","泪","不","等","于","一","切"], jp: ["ngaan5","leoi6","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["献","上","我","的","心"], jp: ["hin3","soeng6","ngo5","dik1","sam1"] },
            { chars: ["亦","要","适","当","去","自","卫"], jp: ["jik6","jiu3","sik1","dong1","heoi3","zi6","wai6"] },
            { chars: ["是"," ","我","好","胜"], jp: ["si6","","ngo5","hou2","sing3"] },
            { chars: ["我","爱","哭"], jp: ["ngo5","ngoi3","huk1"] },
            { chars: ["不","是","问","题"], jp: ["bat1","si6","man6","tai4"] },
            { chars: ["不","这","样","爱","下","个"], jp: ["bat1","ze5","joeng6","ngoi3","haa6","go3"] },
            { chars: ["便","伤","不","到","底"], jp: ["bin6","soeng1","bat1","dou3","dai2"] },
            { paragraphBreak: true },
            { chars: ["谁","自","愿","恨","成","世"], jp: ["seoi4","zi6","jyun6","han6","seng4","sai3"] },
            { chars: ["爱","情","不","等","于","一","切"], jp: ["ngoi3","cing4","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["共","聚","又","离","开"], jp: ["gung6","zeoi6","jau6","lei4","hoi1"] },
            { chars: ["从","来","并","未","学","到","可","以","发","誓"], jp: ["cung4","loi4","bing6","mei6","hok6","dou3","ho2","ji5","faat3","sai6"] },
            { chars: ["可","抱","起","来","亦","抛","得","低"], jp: ["ho2","pou5","hei2","loi4","jik6","paau1","dak1","dai1"] },
            { chars: ["但","学","费","都","真","的","太","贵"], jp: ["daan6","hok6","fai3","dou1","zan1","dik1","taai3","gwai3"] },
            { paragraphBreak: true },
            { chars: ["曾","经","（","曾","经","）"], jp: ["cang4","ging1","","cang4","ging1",""] },
            { chars: ["这","双","手","给","她","抹","眼","泪"], jp: ["ze5","soeng1","sau2","kap1","taa1","mut3","ngaan5","leoi6"] },
            { chars: ["拿","来","抱","你","以","免","你","的","心","碎"], jp: ["naa4","loi4","pou5","nei5","ji5","min5","nei5","dik1","sam1","seoi3"] },
            { chars: ["一","个","又","一","个","也","得","过","去"], jp: ["jat1","go3","jau6","jat1","go3","jaa5","dak1","gwo3","heoi3"] },
            { chars: ["而","我","已","透","视","你"], jp: ["ji4","ngo5","ji5","tau3","si6","nei5"] },
            { paragraphBreak: true },
            { chars: ["怕","寂","寞","叫","你","遇","上","我","所","以","不","得","不","一","起"], jp: ["paa3","zik6","mok6","giu3","nei5","jyu6","soeng5","ngo5","so2","ji5","bat1","dak1","bat1","jat1","hei2"] },
            { chars: ["过","去","有","人","同","样","害","我","少","一","位","知","己"], jp: ["gwo3","heoi3","jau5","jan4","tung4","joeng6","hoi6","ngo5","siu2","jat1","wai6","zi1","gei2"] },
            { chars: ["别","怕"," ","（","别","怕","）"," ","明","白","你","始","终","都","会","走"], jp: ["bit6","paa3","","","bit6","paa3","","","ming4","baak6","nei5","ci2","zung1","dou1","wui6","zau2"] },
            { chars: ["多","谢","你","（","多","谢","你","）","如","今","我","输","得","起"], jp: ["do1","ze6","nei5","","do1","ze6","nei5","","jyu4","gam1","ngo5","syu1","dak1","hei2"] },
            { paragraphBreak: true },
            { chars: ["谁","又","是","做","人","世"], jp: ["seoi4","jau6","si6","zou6","jan4","sai3"] },
            { chars: ["眼","泪","不","等","于","一","切"], jp: ["ngaan5","leoi6","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["献","上","我","的","心"], jp: ["hin3","soeng6","ngo5","dik1","sam1"] },
            { chars: ["亦","要","适","当","去","自","卫"], jp: ["jik6","jiu3","sik1","dong1","heoi3","zi6","wai6"] },
            { chars: ["是"," ","我","好","胜"], jp: ["si6","","ngo5","hou2","sing3"] },
            { chars: ["我","爱","哭"], jp: ["ngo5","ngoi3","huk1"] },
            { chars: ["不","是","问","题"], jp: ["bat1","si6","man6","tai4"] },
            { chars: ["不","这","样","爱","下","个"], jp: ["bat1","ze5","joeng6","ngoi3","haa6","go3"] },
            { chars: ["便","伤","不","到","底"], jp: ["bin6","soeng1","bat1","dou3","dai2"] },
            { paragraphBreak: true },
            { chars: ["谁","自","愿","恨","成","世"], jp: ["seoi4","zi6","jyun6","han6","seng4","sai3"] },
            { chars: ["爱","情","不","等","于","一","切"], jp: ["ngoi3","cing4","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["共","聚","又","离","开"], jp: ["gung6","zeoi6","jau6","lei4","hoi1"] },
            { chars: ["从","来","并","未","学","到","可","以","发","誓"], jp: ["cung4","loi4","bing6","mei6","hok6","dou3","ho2","ji5","faat3","sai6"] },
            { chars: ["可","抱","起","来","亦","抛","得","低"], jp: ["ho2","pou5","hei2","loi4","jik6","paau1","dak1","dai1"] },
            { chars: ["但","学","费","都","真","的","太","贵"], jp: ["daan6","hok6","fai3","dou1","zan1","dik1","taai3","gwai3"] },
            { paragraphBreak: true },
            { chars: ["最","需","要","学","的","是"], jp: ["zeoi3","seoi1","jiu3","hok6","dik1","si6"] },
            { chars: ["如","何","麻","木","了","又","重","头","开","始"], jp: ["jyu4","ho4","maa4","muk6","liu5","jau6","cung5","tau4","hoi1","ci2"] },
            { chars: ["让","每","一","次","亦","似","初","恋","第","一","次"], jp: ["joeng6","mui5","jat1","ci3","jik6","ci5","co1","lyun2","dai6","jat1","ci3"] },
            { chars: ["然","后","再","为","了","下","次","开","始"], jp: ["jin4","hau6","zoi3","wai4","liu5","haa6","ci3","hoi1","ci2"] },
            { paragraphBreak: true },
            { chars: ["谁","又","是","做","人","世"], jp: ["seoi4","jau6","si6","zou6","jan4","sai3"] },
            { chars: ["眼","泪","不","等","于","一","切"], jp: ["ngaan5","leoi6","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["献","上","我","的","心"], jp: ["hin3","soeng6","ngo5","dik1","sam1"] },
            { chars: ["亦","要","适","当","去","自","卫"], jp: ["jik6","jiu3","sik1","dong1","heoi3","zi6","wai6"] },
            { chars: ["是"," ","我","好","胜"], jp: ["si6","","ngo5","hou2","sing3"] },
            { chars: ["我","爱","哭"], jp: ["ngo5","ngoi3","huk1"] },
            { chars: ["不","是","问","题"], jp: ["bat1","si6","man6","tai4"] },
            { chars: ["不","这","样","爱","下","个"], jp: ["bat1","ze5","joeng6","ngoi3","haa6","go3"] },
            { chars: ["便","伤","不","到","底"], jp: ["bin6","soeng1","bat1","dou3","dai2"] },
            { paragraphBreak: true },
            { chars: ["谁","自","愿","恨","成","世"], jp: ["seoi4","zi6","jyun6","han6","seng4","sai3"] },
            { chars: ["爱","情","不","等","于","一","切"], jp: ["ngoi3","cing4","bat1","dang2","jyu1","jat1","cai3"] },
            { chars: ["共","聚","又","离","开"], jp: ["gung6","zeoi6","jau6","lei4","hoi1"] },
            { chars: ["从","来","并","未","学","到","可","以","发","誓"], jp: ["cung4","loi4","bing6","mei6","hok6","dou3","ho2","ji5","faat3","sai6"] },
            { chars: ["转","眼","飘","流"], jp: ["zyun2","ngaan5","piu1","lau4"] },
            { chars: ["是","哪","一","位"], jp: ["si6","naa5","jat1","wai6"] },
            { chars: ["但","学","费","都","真","的","太","贵"], jp: ["daan6","hok6","fai3","dou1","zan1","dik1","taai3","gwai3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
