// 歌曲：炼金术

(function() {
    const song = {
        id: 458,
        title: "炼金术",
        titleJyutping: ["lin6","gam1","seot6"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "伍乐城",
        composerJyutping: ["ng5","lok6","sing4"],
        lyrics: [
            { chars: ["给","我","一","团","熊","火"], jp: ["kap1","ngo5","jat1","tyun4","hung4","fo2"] },
            { chars: ["试","炼","我"], jp: ["si3","lin6","ngo5"] },
            { chars: ["证","明","我","这","么","狠","狠","爱","过"], jp: ["zing3", "ming4", "ngo5", "ze5", "mo1", "han2", "han2", "ngoi3", "gwo3"] },
            { chars: ["期","望","不","多"], jp: ["kei4","mong6","bat1","do1"] },
            { chars: ["只","要","得","到","过"], jp: ["zi2","jiu3","dak1","dou3","gwo3"] },
            { chars: ["你","身","旁"], jp: ["nei5","san1","pong4"] },
            { chars: ["那","宝","座"], jp: ["naa5","bou2","zo6"] },
            { paragraphBreak: true },
            { chars: ["给","我","一","场","洪","水"], jp: ["kap1","ngo5","jat1","coeng4","hung4","seoi2"] },
            { chars: ["冷","静","我"], jp: ["laang5","zing6","ngo5"] },
            { chars: ["眼","泪","太","多"], jp: ["ngaan5","leoi6","taai3","do1"] },
            { chars: ["已","汇","聚","成","河"], jp: ["ji5","wui6","zeoi6","sing4","ho4"] },
            { chars: ["力","竭","声","嘶"], jp: ["lik6","kit3","sing1","sai1"] },
            { chars: ["请","你","喜","欢","我"], jp: ["cing2","nei5","hei2","fun1","ngo5"] },
            { chars: ["什","么","事","都","做","过"], jp: ["sap6", "mo1", "si6", "dou1", "zou6", "gwo3"] },
            { chars: ["都","不","能","感","动","你","么"], jp: ["dou1", "bat1", "nang4", "gam2", "dung6", "nei5", "mo1"] },
            { paragraphBreak: true },
            { chars: ["原","来","暂","时","共","你","没","缘","份"], jp: ["jyun4","loi4","zaam6","si4","gung6","nei5","mut6","jyun4","fan6"] },
            { chars: ["来","年","先","会","变","得","更","合","衬"], jp: ["loi4","nin4","sin1","wui6","bin3","dak1","gang1","hap6","can3"] },
            { chars: ["顽","石","哪","天","变","黄","金"], jp: ["waan4","sek6","naa5","tin1","bin3","wong4","gam1"] },
            { chars: ["我","可","以","等"], jp: ["ngo5","ho2","ji5","dang2"] },
            { chars: ["融","和","二","人","是","哪","样","成","份"], jp: ["jung4","wo4","ji6","jan4","si6","naa5","joeng6","sing4","fan6"] },
            { chars: ["但","愿","虔","诚","能","显","得","吸","引"], jp: ["daan6","jyun6","kin4","sing4","nang4","hin2","dak1","kap1","jan5"] },
            { chars: ["用","五","十","年","溶","化","你"], jp: ["jung6","ng5","sap6","nin4","jung4","faa3","nei5"] },
            { chars: ["成","就"," ","金","禧","一","吻"], jp: ["sing4","zau6","","gam1","hei1","jat1","man5"] },
            { paragraphBreak: true },
            { chars: ["不","够","激","情"], jp: ["bat1","gau3","gik1","cing4"] },
            { chars: ["仍","可","靠","耐","性"], jp: ["jing4","ho2","kaau3","noi6","sing3"] },
            { chars: ["对","付","你","的","冷","酷","及","无","情"], jp: ["deoi3","fu6","nei5","dik1","laang5","huk6","kap6","mou4","cing4"] },
            { chars: ["沉","默","假","使"], jp: ["cam4","mak6","gaa2","si2"] },
            { chars: ["都","算","种","本","领"], jp: ["dou1","syun3","zung2","bun2","ling5"] },
            { chars: ["我","一","定"], jp: ["ngo5","jat1","ding6"] },
            { chars: ["最","安","静"], jp: ["zeoi3","on1","zing6"] },
            { paragraphBreak: true },
            { chars: ["深","信","忠","诚","迟","早","会","获","胜"], jp: ["sam1","seon3","zung1","sing4","ci4","zou2","wui6","wok6","sing3"] },
            { chars: ["那","份","固","执","终","于","都","会","被","尊","敬"], jp: ["naa5","fan6","gu3","zap1","zung1","jyu1","dou1","wui6","bei6","zyun1","ging3"] },
            { chars: ["如","炼","金","般","等","你","先","转","性"], jp: ["jyu4","lin6","gam1","bun1","dang2","nei5","sin1","zyun2","sing3"] },
            { chars: ["除","非","遗","失","人","性"], jp: ["ceoi4","fei1","wai4","sat1","jan4","sing3"] },
            { chars: ["怎","可","能","一","直","结","冰"], jp: ["zam2","ho2","nang4","jat1","zik6","git3","bing1"] },
            { paragraphBreak: true },
            { chars: ["原","来","暂","时","共","你","没","缘","份"], jp: ["jyun4","loi4","zaam6","si4","gung6","nei5","mut6","jyun4","fan6"] },
            { chars: ["来","年","先","会","变","得","更","合","衬"], jp: ["loi4","nin4","sin1","wui6","bin3","dak1","gang1","hap6","can3"] },
            { chars: ["顽","石","哪","天","变","黄","金"], jp: ["waan4","sek6","naa5","tin1","bin3","wong4","gam1"] },
            { chars: ["我","可","以","等"], jp: ["ngo5","ho2","ji5","dang2"] },
            { chars: ["融","和","二","人","是","哪","样","成","份"], jp: ["jung4","wo4","ji6","jan4","si6","naa5","joeng6","sing4","fan6"] },
            { chars: ["但","愿","虔","诚","能","显","得","吸","引"], jp: ["daan6","jyun6","kin4","sing4","nang4","hin2","dak1","kap1","jan5"] },
            { chars: ["用","五","十","年","溶","化","你"], jp: ["jung6","ng5","sap6","nin4","jung4","faa3","nei5"] },
            { chars: ["成","就"," ","金","禧","一","吻"], jp: ["sing4","zau6","","gam1","hei1","jat1","man5"] },
            { paragraphBreak: true },
            { chars: ["头","白","了"], jp: ["tau4","baak6","liu5"] },
            { chars: ["还","在","等"], jp: ["waan4","zoi6","dang2"] },
            { chars: ["情","人","预","约","在","黄","昏"], jp: ["cing4","jan4","jyu6","joek3","zoi6","wong4","fan1"] },
            { paragraphBreak: true },
            { chars: ["原","来","暂","时","共","你","没","缘","份"], jp: ["jyun4","loi4","zaam6","si4","gung6","nei5","mut6","jyun4","fan6"] },
            { chars: ["来","年","先","会","变","得","更","合","衬"], jp: ["loi4","nin4","sin1","wui6","bin3","dak1","gang1","hap6","can3"] },
            { chars: ["期","待","再","苦","再","难","堪"], jp: ["kei4","doi6","zoi3","fu2","zoi3","naan4","ham1"] },
            { chars: ["我","都","会","忍"], jp: ["ngo5","dou1","wui6","jan2"] },
            { chars: ["谈","情","十","年","未","晚","不","怕","等"], jp: ["taam4","cing4","sap6","nin4","mei6","maan5","bat1","paa3","dang2"] },
            { chars: ["渡","日","如","年","仍","觉","得","兴","奋"], jp: ["dou6","jat6","jyu4","nin4","jing4","gok3","dak1","hing1","fan5"] },
            { chars: ["若","最","后","能","溶","化","你"], jp: ["joek6","zeoi3","hau6","nang4","jung4","faa3","nei5"] },
            { chars: ["何","用"," ","心","急","手","震"], jp: ["ho4","jung6","","sam1","gap1","sau2","zan3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
