// 歌曲：烈女

(function() {
    const song = {
        id: 445,
        title: "烈女",
        titleJyutping: ["lit6","neoi5"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["很","想","装","作","我","没","有","灵","魂"], jp: ["han2","soeng2","zong1","zok3","ngo5","mut6","jau5","ling4","wan4"] },
            { chars: ["但","你","赞","我","性","感"], jp: ["daan6","nei5","zaan3","ngo5","sing3","gam2"] },
            { chars: ["很","想","偷","呃","拐","骗","的","勾","引"], jp: ["han2","soeng2","tau1","ak1","gwaai2","pin3","dik1","ngau1","jan5"] },
            { chars: ["完","了","事","便","怀","孕"], jp: ["jyun4","liu5","si6","bin6","waai4","jan6"] },
            { chars: ["然","后","便","跟","你"], jp: ["jin4","hau6","bin6","gan1","nei5"] },
            { chars: ["跟","你","到","家","里","去","扫","地"], jp: ["gan1","nei5","dou3","gaa1","lei5","heoi3","sou3","dei6"] },
            { chars: ["让","情","敌","跟","我","讲","恭","喜"], jp: ["joeng6","cing4","dik6","gan1","ngo5","gong2","gung1","hei2"] },
            { chars: ["放","弃","事","与","非"], jp: ["fong3","hei3","si6","jyu5","fei1"] },
            { chars: ["与","魔","鬼","在","一","起"], jp: ["jyu5","mo1","gwai2","zoi6","jat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["烈","女","不","怕","死"], jp: ["lit6","neoi5","bat1","paa3","sei2"] },
            { chars: ["但","凭","傲","气"], jp: ["daan6","pang4","ngou6","hei3"] },
            { chars: ["绝","没","有","必","要","呵","你","似","歌","姬"], jp: ["zyut6","mut6","jau5","bit1","jiu3","ho1","nei5","ci5","go1","gei1"] },
            { chars: ["知","你","好","过","了","便","要","分","离"], jp: ["zi1","nei5","hou2","gwo3","liu5","bin6","jiu3","fan1","lei4"] },
            { chars: ["没","有","骨","气","只","会","变","奸","妃"], jp: ["mut6","jau5","gwat1","hei3","zi2","wui6","bin3","gaan1","fei1"] },
            { paragraphBreak: true },
            { chars: ["烈","女","不","怕","死"], jp: ["lit6","neoi5","bat1","paa3","sei2"] },
            { chars: ["又","何","惧","你"], jp: ["jau6","ho4","geoi6","nei5"] },
            { chars: ["不","会","失","去","血","性","和","品","味"], jp: ["bat1","wui6","sat1","heoi3","hyut3","sing3","wo4","ban2","mei6"] },
            { chars: ["知","你","一","向","以","我","去","摄","期"], jp: ["zi1","nei5","jat1","hoeng3","ji5","ngo5","heoi3","sip3","kei4"] },
            { chars: ["迎","合","你","便","令","名","誉","扫","地"], jp: ["jing4","hap6","nei5","bin6","ling6","ming4","jyu6","sou3","dei6"] },
            { chars: ["呸","呸"], jp: ["pei1","pei1"] },
            { paragraphBreak: true },
            { chars: ["本","应","想","我","变","做","你","类","型"], jp: ["bun2","jing3","soeng2","ngo5","bin3","zou6","nei5","leoi6","jing4"] },
            { chars: ["让","你","与","我","有","景"], jp: ["joeng6","nei5","jyu5","ngo5","jau5","ging2"] },
            { chars: ["只","可","惜","得","到","你","的","尊","敬"], jp: ["zi2","ho2","sik1","dak1","dou3","nei5","dik1","zyun1","ging3"] },
            { chars: ["全","因","肯","当","布","景"], jp: ["cyun4","jan1","hang2","dong1","bou3","ging2"] },
            { chars: ["无","谓","被","选","美"], jp: ["mou4","wai6","bei6","syun2","mei5"] },
            { chars: ["逼","你","待","我","好","我","宁","愿","伤","悲"], jp: ["bik1","nei5","doi6","ngo5","hou2","ngo5","ning4","jyun6","soeng1","bei1"] },
            { chars: ["若","然","排","在","榜","中","最","多","三","四"], jp: ["joek6","jin4","paai4","zoi6","bong2","zung1","zeoi3","do1","saam1","sei3"] },
            { chars: ["我","纵","像","储","妃"], jp: ["ngo5","zung3","zoeng6","cyu5","fei1"] },
            { chars: ["违","背","了","我","天","地"], jp: ["wai4","bui3","liu5","ngo5","tin1","dei6"] },
            { paragraphBreak: true },
            { chars: ["烈","女","不","怕","死"], jp: ["lit6","neoi5","bat1","paa3","sei2"] },
            { chars: ["但","凭","傲","气"], jp: ["daan6","pang4","ngou6","hei3"] },
            { chars: ["绝","没","有","必","要","呵","你","似","歌","姬"], jp: ["zyut6","mut6","jau5","bit1","jiu3","ho1","nei5","ci5","go1","gei1"] },
            { chars: ["知","你","好","过","了","便","要","分","离"], jp: ["zi1","nei5","hou2","gwo3","liu5","bin6","jiu3","fan1","lei4"] },
            { chars: ["没","有","骨","气","只","会","变","奸","妃"], jp: ["mut6","jau5","gwat1","hei3","zi2","wui6","bin3","gaan1","fei1"] },
            { paragraphBreak: true },
            { chars: ["烈","女","不","怕","死"], jp: ["lit6","neoi5","bat1","paa3","sei2"] },
            { chars: ["又","何","惧","你"], jp: ["jau6","ho4","geoi6","nei5"] },
            { chars: ["不","会","失","去","血","性","和","品","味"], jp: ["bat1","wui6","sat1","heoi3","hyut3","sing3","wo4","ban2","mei6"] },
            { chars: ["知","你","一","向","以","我","去","摄","期"], jp: ["zi1","nei5","jat1","hoeng3","ji5","ngo5","heoi3","sip3","kei4"] },
            { chars: ["迎","合","你","便","令","名","誉","扫","地"], jp: ["jing4","hap6","nei5","bin6","ling6","ming4","jyu6","sou3","dei6"] },
            { paragraphBreak: true },
            { chars: ["烈","女","不","怕","死"], jp: ["lit6","neoi5","bat1","paa3","sei2"] },
            { chars: ["但","凭","傲","气"], jp: ["daan6","pang4","ngou6","hei3"] },
            { chars: ["绝","没","有","必","要","呵","你","似","歌","姬"], jp: ["zyut6","mut6","jau5","bit1","jiu3","ho1","nei5","ci5","go1","gei1"] },
            { chars: ["知","你","好","过","了","便","要","分","离"], jp: ["zi1","nei5","hou2","gwo3","liu5","bin6","jiu3","fan1","lei4"] },
            { chars: ["没","有","骨","气","只","会","变","奸","妃"], jp: ["mut6","jau5","gwat1","hei3","zi2","wui6","bin3","gaan1","fei1"] },
            { paragraphBreak: true },
            { chars: ["烈","女","不","怕","死"], jp: ["lit6","neoi5","bat1","paa3","sei2"] },
            { chars: ["又","何","惧","你"], jp: ["jau6","ho4","geoi6","nei5"] },
            { chars: ["不","会","失","去","血","性","和","品","味"], jp: ["bat1","wui6","sat1","heoi3","hyut3","sing3","wo4","ban2","mei6"] },
            { chars: ["知","你","一","向","以","我","去","摄","期"], jp: ["zi1","nei5","jat1","hoeng3","ji5","ngo5","heoi3","sip3","kei4"] },
            { chars: ["迎","合","你","便","令","名","誉","扫","地"], jp: ["jing4","hap6","nei5","bin6","ling6","ming4","jyu6","sou3","dei6"] },
            { chars: ["呸","呸"], jp: ["pei1","pei1"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
