// 歌曲：特别嘉宾

(function() {
    const song = {
        id: 516,
        title: "特别嘉宾",
        titleJyutping: ["dak6","bit6","gaa1","ban1"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "Barry Chung",
        composerJyutping: ["","","","","","","","","","",""],
        lyrics: [
            { chars: ["想"," ","无","论","什","么","都","也","不","想"], jp: ["soeng2","","mou4","leon6","sap6","maa1","dou1","jaa5","bat1","soeng2"] },
            { chars: ["甜","品","使","我","心","痒"], jp: ["tim4","ban2","si2","ngo5","sam1","joeng5"] },
            { chars: ["亦","期","待","你"], jp: ["jik6","kei4","doi6","nei5"] },
            { chars: ["共","我","愉","快","分","享"], jp: ["gung6","ngo5","jyu4","faai3","fan1","hoeng2"] },
            { paragraphBreak: true },
            { chars: ["如","果"," ","甜","蜜","是","最","后","才","出","场"], jp: ["jyu4","gwo2","","tim4","mat6","si6","zeoi3","hau6","coi4","ceot1","coeng4"] },
            { chars: ["情","感"," ","多","少","笔","帐"], jp: ["cing4","gam2","","do1","siu2","bat1","zoeng3"] },
            { chars: ["全","部","等","压","轴","那","位","登","场"], jp: ["cyun4","bou6","dang2","aat3","zuk6","naa5","wai6","dang1","coeng4"] },
            { paragraphBreak: true },
            { chars: ["无","论","什","么","东","西","使","我","痛","快","开","心"], jp: ["mou4","leon6","sap6","maa1","dung1","sai1","si2","ngo5","tung3","faai3","hoi1","sam1"] },
            { chars: ["仍","期","待","你","是","我","特","别","嘉","宾"], jp: ["jing4","kei4","doi6","nei5","si6","ngo5","dak6","bit6","gaa1","ban1"] },
            { paragraphBreak: true },
            { chars: ["当","我","最","快","乐","时","替","我","高","兴"], jp: ["dong1","ngo5","zeoi3","faai3","lok6","si4","tai3","ngo5","gou1","hing1"] },
            { chars: ["当","我","要","放","任","时","赐","我","反","应"], jp: ["dong1","ngo5","jiu3","fong3","jam6","si4","ci3","ngo5","faan2","jing3"] },
            { chars: ["有","你","陪","伴","气","氛","总","有","保","证"], jp: ["jau5","nei5","pui4","bun6","hei3","fan1","zung2","jau5","bou2","zing3"] },
            { chars: ["娱","乐","我","是","你","本","领"], jp: ["jyu4","lok6","ngo5","si6","nei5","bun2","ling5"] },
            { paragraphBreak: true },
            { chars: ["唯","独","你"], jp: ["wai4","duk6","nei5"] },
            { chars: ["当","我","最","快","乐","时","替","我","高","兴"], jp: ["dong1","ngo5","zeoi3","faai3","lok6","si4","tai3","ngo5","gou1","hing1"] },
            { chars: ["如","像","将","恭","喜","变","作","铃","声"], jp: ["jyu4","zoeng6","zoeng1","gung1","hei2","bin3","zok3","ling4","sing1"] },
            { chars: ["不","算","天","大","事","情"], jp: ["bat1","syun3","tin1","daai6","si6","cing4"] },
            { chars: ["难","道","你","忍","心","不","去","赠","兴"], jp: ["naan4","dou6","nei5","jan2","sam1","bat1","heoi3","zang6","hing1"] },
            { paragraphBreak: true },
            { chars: ["请"," ","前","来","做","我","压","轴","的","人"], jp: ["cing2","","cin4","loi4","zou6","ngo5","aat3","zuk6","dik1","jan4"] },
            { chars: ["无","须","约","会","别","人"], jp: ["mou4","seoi1","joek3","wui6","bit6","jan4"] },
            { chars: ["娱","乐","一","晚","扮","庆","祝","生","辰"], jp: ["jyu4","lok6","jat1","maan5","baan6","hing3","zuk1","sang1","san4"] },
            { paragraphBreak: true },
            { chars: ["无","论","什","么","东","西","使","我","痛","快","开","心"], jp: ["mou4","leon6","sap6","maa1","dung1","sai1","si2","ngo5","tung3","faai3","hoi1","sam1"] },
            { chars: ["仍","期","待","你","是","我","特","别","嘉","宾"], jp: ["jing4","kei4","doi6","nei5","si6","ngo5","dak6","bit6","gaa1","ban1"] },
            { paragraphBreak: true },
            { chars: ["当","我","最","快","乐","时","替","我","高","兴"], jp: ["dong1","ngo5","zeoi3","faai3","lok6","si4","tai3","ngo5","gou1","hing1"] },
            { chars: ["当","我","要","放","任","时","赐","我","反","应"], jp: ["dong1","ngo5","jiu3","fong3","jam6","si4","ci3","ngo5","faan2","jing3"] },
            { chars: ["有","你","陪","伴","气","氛","总","有","保","证"], jp: ["jau5","nei5","pui4","bun6","hei3","fan1","zung2","jau5","bou2","zing3"] },
            { chars: ["娱","乐","我","是","你","本","领"], jp: ["jyu4","lok6","ngo5","si6","nei5","bun2","ling5"] },
            { paragraphBreak: true },
            { chars: ["唯","独","你"], jp: ["wai4","duk6","nei5"] },
            { chars: ["当","我","最","快","乐","时","替","我","高","兴"], jp: ["dong1","ngo5","zeoi3","faai3","lok6","si4","tai3","ngo5","gou1","hing1"] },
            { chars: ["如","像","将","恭","喜","变","作","铃","声"], jp: ["jyu4","zoeng6","zoeng1","gung1","hei2","bin3","zok3","ling4","sing1"] },
            { chars: ["不","算","天","大","事","情"], jp: ["bat1","syun3","tin1","daai6","si6","cing4"] },
            { chars: ["难","道","你","忍","心","不","去","赠","兴"], jp: ["naan4","dou6","nei5","jan2","sam1","bat1","heoi3","zang6","hing1"] },
            { paragraphBreak: true },
            { chars: ["我","能","被","你"], jp: ["ngo5","nang4","bei6","nei5"] },
            { chars: ["拿","着","爱"], jp: ["naa4","zoek6","ngoi3"] },
            { chars: ["扶","着","吻"], jp: ["fu4","zoek6","man5"] },
            { chars: ["我","难","道","要"], jp: ["ngo5","naan4","dou6","jiu3"] },
            { chars: ["预","备","嘉","宾"], jp: ["jyu6","bei6","gaa1","ban1"] },
            { paragraphBreak: true },
            { chars: ["唯","独","你"], jp: ["wai4","duk6","nei5"] },
            { chars: ["当","我","最","快","乐","时","替","我","高","兴"], jp: ["dong1","ngo5","zeoi3","faai3","lok6","si4","tai3","ngo5","gou1","hing1"] },
            { chars: ["当","我","要","放","任","时","赐","我","反","应"], jp: ["dong1","ngo5","jiu3","fong3","jam6","si4","ci3","ngo5","faan2","jing3"] },
            { chars: ["有","你","陪","伴","气","氛","总","有","保","证"], jp: ["jau5","nei5","pui4","bun6","hei3","fan1","zung2","jau5","bou2","zing3"] },
            { chars: ["娱","乐","我","是","你","本","领"], jp: ["jyu4","lok6","ngo5","si6","nei5","bun2","ling5"] },
            { paragraphBreak: true },
            { chars: ["唯","独","你"], jp: ["wai4","duk6","nei5"] },
            { chars: ["当","我","最","快","乐","时","替","我","高","兴"], jp: ["dong1","ngo5","zeoi3","faai3","lok6","si4","tai3","ngo5","gou1","hing1"] },
            { chars: ["如","像","将","恭","喜","变","作","铃","声"], jp: ["jyu4","zoeng6","zoeng1","gung1","hei2","bin3","zok3","ling4","sing1"] },
            { chars: ["不","算","天","大","事","情"], jp: ["bat1","syun3","tin1","daai6","si6","cing4"] },
            { chars: ["难","道","你","忍","心","不","去","赠","兴"], jp: ["naan4","dou6","nei5","jan2","sam1","bat1","heoi3","zang6","hing1"] },
            { paragraphBreak: true },
            { chars: ["不","算","天","大","事","情"], jp: ["bat1","syun3","tin1","daai6","si6","cing4"] },
            { chars: ["仍","期","待","你","赠","我","掌","声"], jp: ["jing4","kei4","doi6","nei5","zang6","ngo5","zoeng2","sing1"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
