// 歌曲：电灯胆

(function() {
    const song = {
        id: 709,
        title: "电灯胆",
        titleJyutping: ["din6","dang1","daam2"],
        artist: "邓丽欣",
        artistJyutping: ["dang6","lai6","jan1"],
        lyricist: "李竣一",
        lyricistJyutping: ["lei5","zeon3","jat1"],
        composer: "李竣一",
        composerJyutping: ["lei5","zeon3","jat1"],
        lyrics: [
            { chars: ["假","使","不","能","公","开","妒","忌"], jp: ["gaa2","si2","bat1","nang4","gung1","hoi1","dou3","gei6"] },
            { chars: ["学","习","大","方","接","受"], jp: ["hok6","zaap6","daai6","fong1","zip3","sau6"] },
            { chars: ["同","行","时","要","殿","后"], jp: ["tung4","hong4","si4","jiu3","din6","hau6"] },
            { chars: ["谁","冷","落","旧","朋","友"], jp: ["seoi4","laang5","lok6","gau6","pang4","jau5"] },
            { chars: ["节","日","约","我","三","位","一","体","的","庆","祝"], jp: ["zit3","jat6","joek3","ngo5","saam1","wai6","jat1","tai2","dik1","hing3","zuk1"] },
            { chars: ["沿","途","明","亮","灯","饰","闪","映","着","沈","重"], jp: ["jyun4","tou4","ming4","loeng6","dang1","sik1","sim2","jing2","zoek6","sam2","cung5"] },
            { chars: ["言","谈","越","炽","热","内","在","更","冰","冻"], jp: ["jin4","taam4","jyut6","ci3","jit6","noi6","zoi6","gang1","bing1","dung3"] },
            { paragraphBreak: true },
            { chars: ["谁","当","初","无","心","将","两","方","缀","合"], jp: ["seoi4","dong1","co1","mou4","sam1","zoeng1","loeng5","fong1","zeoi3","hap6"] },
            { chars: ["然","后","留","低"], jp: ["jin4","hau6","lau4","dai1"] },
            { chars: ["只","得","这","寂","寞","人"], jp: ["zi2","dak1","ze5","zik6","mok6","jan4"] },
            { chars: ["仍","是","你","们","密","友","呆","望","你","们","热","吻"], jp: ["jing4","si6","nei5","mun4","mat6","jau5","ngoi4","mong6","nei5","mun4","jit6","man5"] },
            { chars: ["应","该","伤","感","还","是","快","感"], jp: ["jing3","goi1","soeng1","gam2","waan4","si6","faai3","gam2"] },
            { paragraphBreak: true },
            { chars: ["能","回","避","嘛"], jp: ["nang4","wui4","bei6","maa1"] },
            { chars: ["我","怕","了"], jp: ["ngo5","paa3","liu5"] },
            { chars: ["当","那","电","灯","胆"], jp: ["dong1","naa5","din6","dang1","daam2"] },
            { chars: ["黏","着","你","们","来","来","回"], jp: ["nim1","zoek6","nei5","mun4","loi4","loi4","wui4"] },
            { chars: ["委","曲","中","受","难"], jp: ["wai2","kuk1","zung1","sau6","naan4"] },
            { chars: ["一","个","我","被","撇","低"], jp: ["jat1","go3","ngo5","bei6","pit3","dai1"] },
            { chars: ["却","又","很","不","惯"], jp: ["koek3","jau6","han2","bat1","gwaan3"] },
            { chars: ["要","走","的","一","刹","又","折","返"], jp: ["jiu3","zau2","dik1","jat1","caat3","jau6","zit3","faan2"] },
            { paragraphBreak: true },
            { chars: ["能","承","认","嘛"], jp: ["nang4","sing4","jing6","maa1"] },
            { chars: ["我","故","意","当","那","电","灯","胆"], jp: ["ngo5","gu3","ji3","dong1","naa5","din6","dang1","daam2"] },
            { chars: ["他","日","你","们","完","场","时"], jp: ["taa1","jat6","nei5","mun4","jyun4","coeng4","si4"] },
            { chars: ["入","替","也","不","难"], jp: ["jap6","tai3","jaa5","bat1","naan4"] },
            { chars: ["善","良","人","埋","藏","着","最","坏","的","心","眼"], jp: ["sin6","loeng4","jan4","maai4","cong4","zoek6","zeoi3","waai6","dik1","sam1","ngaan5"] },
            { chars: ["妄","想","一","天","你","们","会","散"], jp: ["mong5","soeng2","jat1","tin1","nei5","mun4","wui6","saan3"] },
            { chars: ["会","选","我","吗"], jp: ["wui6","syun2","ngo5","maa1"] },
            { paragraphBreak: true },
            { chars: ["啦","啦"," ","啦","啦","啦","啦"], jp: ["laa4","laa1","","laa4","laa1","laa4","laa1"] },
            { chars: ["啦","啦","啦","啦","啦","啦","啦"], jp: ["laa4","laa1","laa4","laa1","laa4","laa1","laa1"] },
            { chars: ["啦","啦","啦"], jp: ["laa4","laa1","laa1"] },
            { chars: ["啦","啦"," ","啦","啦"], jp: ["laa4","laa1","","laa4","laa1"] },
            { chars: ["啦","啦","啦","啦"], jp: ["laa4","laa1","laa4","laa1"] },
            { paragraphBreak: true },
            { chars: ["对","换","了","你","身","份","可","应","该","满","足"], jp: ["deoi3","wun6","liu5","nei5","san1","fan2","ho2","jing3","goi1","mun5","zuk1"] },
            { chars: ["情","人","还","是","知","己","都","拥","入","怀","抱"], jp: ["cing4","jan4","waan4","si6","zi1","gei2","dou1","jung2","jap6","waai4","pou5"] },
            { chars: ["同","情","或","眼","泪"], jp: ["tung4","cing4","waak6","ngaan5","leoi6"] },
            { chars: ["让","别","个","得","到"], jp: ["joeng6","bit6","go3","dak1","dou3"] },
            { paragraphBreak: true },
            { chars: ["留","低","的","原","因"], jp: ["lau4","dai1","dik1","jyun4","jan1"] },
            { chars: ["一","世","的","秘","密"], jp: ["jat1","sai3","dik1","bei3","mat6"] },
            { chars: ["其","实","明","知","只","得","我","是","外","人"], jp: ["kei4","sat6","ming4","zi1","zi2","dak1","ngo5","si6","ngoi6","jan4"] },
            { chars: ["仍","是","你","们","密","友","呆","望","你","们","热","吻"], jp: ["jing4","si6","nei5","mun4","mat6","jau5","ngoi4","mong6","nei5","mun4","jit6","man5"] },
            { chars: ["应","该","开","心","还","是","痛","心"], jp: ["jing3","goi1","hoi1","sam1","waan4","si6","tung3","sam1"] },
            { paragraphBreak: true },
            { chars: ["能","回","避","嘛"], jp: ["nang4","wui4","bei6","maa1"] },
            { chars: ["我","怕","了"], jp: ["ngo5","paa3","liu5"] },
            { chars: ["当","那","电","灯","胆"], jp: ["dong1","naa5","din6","dang1","daam2"] },
            { chars: ["黏","着","你","们","来","来","回"], jp: ["nim1","zoek6","nei5","mun4","loi4","loi4","wui4"] },
            { chars: ["委","曲","中","受","难"], jp: ["wai2","kuk1","zung1","sau6","naan4"] },
            { chars: ["一","个","我","被","撇","低"], jp: ["jat1","go3","ngo5","bei6","pit3","dai1"] },
            { chars: ["却","又","很","不","惯"], jp: ["koek3","jau6","han2","bat1","gwaan3"] },
            { chars: ["要","走","的","一","刹","又","折","返"], jp: ["jiu3","zau2","dik1","jat1","caat3","jau6","zit3","faan2"] },
            { paragraphBreak: true },
            { chars: ["能","承","认","嘛"], jp: ["nang4","sing4","jing6","maa1"] },
            { chars: ["我","故","意","当","那","电","灯","胆"], jp: ["ngo5","gu3","ji3","dong1","naa5","din6","dang1","daam2"] },
            { chars: ["他","日","你","们","完","场","时"], jp: ["taa1","jat6","nei5","mun4","jyun4","coeng4","si4"] },
            { chars: ["入","替","也","不","难"], jp: ["jap6","tai3","jaa5","bat1","naan4"] },
            { chars: ["善","良","人","埋","藏","着","最","坏","的","心","眼"], jp: ["sin6","loeng4","jan4","maai4","cong4","zoek6","zeoi3","waai6","dik1","sam1","ngaan5"] },
            { chars: ["妄","想","一","天","你","们","会","散"], jp: ["mong5","soeng2","jat1","tin1","nei5","mun4","wui6","saan3"] },
            { chars: ["会","选","我","吗"], jp: ["wui6","syun2","ngo5","maa1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
