// 歌曲：画意

(function() {
    const song = {
        id: 945,
        title: "画意",
        titleJyutping: ["waak6","ji3"],
        artist: "王菀之",
        artistJyutping: ["wong4","jyun2","zi1"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "王菀之",
        composerJyutping: ["wong4","jyun2","zi1"],
        lyrics: [
            { chars: ["被","人","嫌","怪","被","人","辞","退","被","情","人","骗","去"], jp: ["bei6","jan4","jim4","gwaai3","bei6","jan4","ci4","teoi3","bei6","cing4","jan4","pin3","heoi3"] },
            { chars: ["绝","望","的","感","情","傻","到","留","下","耳","朵"], jp: ["zyut6","mong6","dik1","gam2","cing4","so4","dou3","lau4","haa6","ji5","do2"] },
            { chars: ["给","情","人","做","装","饰","的","怪","客"], jp: ["kap1","cing4","jan4","zou6","zong1","sik1","dik1","gwaai3","haak3"] },
            { chars: ["谁","受","过","他","感","动"], jp: ["seoi4","sau6","gwo3","taa1","gam2","dung6"] },
            { chars: ["还","是","觉","得","惊","吓"], jp: ["waan4","si6","gok3","dak1","ging1","haak3"] },
            { chars: ["苦","恋","之","痛","全","被","抹","杀"], jp: ["fu2","lyun2","zi1","tung3","cyun4","bei6","mut3","saat3"] },
            { paragraphBreak: true },
            { chars: ["百","病","贫","困","仍","然","无","悔","未","曾","卖","过","仍","旧","画","画"], jp: ["baak3","beng6","pan4","kwan3","jing4","jin4","mou4","fui3","mei6","cang4","maai6","gwo3","jing4","gau6","waak6","waak6"] },
            { chars: ["只","是","为","了","呈","现","世","间","光","明","来","叫","开","心","可","散","发"], jp: ["zi2","si6","wai4","liu5","cing4","jin6","sai3","gaan1","gwong1","ming4","loi4","giu3","hoi1","sam1","ho2","saan3","faat3"] },
            { chars: ["无","视","血","色","苍","白"], jp: ["mou4","si6","hyut3","sik1","cong1","baak6"] },
            { chars: ["忘","掉","过","得","萧","煞"], jp: ["mong4","diu6","gwo3","dak1","siu1","saat3"] },
            { chars: ["色","彩","鲜","暖","全","是","自","发"], jp: ["sik1","coi2","sin1","nyun5","cyun4","si6","zi6","faat3"] },
            { paragraphBreak: true },
            { chars: ["你","听","过","梵","高","吧"], jp: ["nei5","ting1","gwo3","faan6","gou1","baa6"] },
            { chars: ["值","几","多","百"], jp: ["zik6","gei2","do1","baak3"] },
            { chars: ["他","那","人","格"], jp: ["taa1","naa5","jan4","gaak3"] },
            { chars: ["难","剖","白"], jp: ["naan4","fau2","baak6"] },
            { chars: ["求","存","人","人","明","白"], jp: ["kau4","cyun4","jan4","jan4","ming4","baak6"] },
            { chars: ["看","　","他","有","权","乱","去","画"], jp: ["hon3","","taa1","jau5","kyun4","lyun6","heoi3","waak6"] },
            { chars: ["也","许","口","袋"], jp: ["jaa5","heoi2","hau2","doi6"] },
            { chars: ["也","不","致","一","片","空","白"], jp: ["jaa5","bat1","zi3","jat1","pin3","hung1","baak6"] },
            { paragraphBreak: true },
            { chars: ["画","完","无","数","麦","田","和","向","日","葵"], jp: ["waak6","jyun4","mou4","sou3","mak6","tin4","wo4","hoeng3","jat6","kwai4"] },
            { chars: ["赢","到","了","后","代","的","收","藏","研","究"], jp: ["jing4","dou3","liu5","hau6","doi6","dik1","sau1","cong4","jin4","gau3"] },
            { chars: ["无","奈","有","生","之","年","才","售","得","出","一","个","客"], jp: ["mou4","noi6","jau5","sang1","zi1","nin4","coi4","sau6","dak1","ceot1","jat1","go3","haak3"] },
            { chars: ["无","奈","那","种","钩","勒"], jp: ["mou4","noi6","naa5","zung2","ngau1","lak6"] },
            { chars: ["无","奈","那","种","笔","法"], jp: ["mou4","noi6","naa5","zung2","bat1","faat3"] },
            { chars: ["一","幅","心","血","才","值","二","百"], jp: ["jat1","fuk1","sam1","hyut3","coi4","zik6","ji6","baak3"] },
            { paragraphBreak: true },
            { chars: ["万","人","做","上","万","年","难","买","艺","术","杰","作"], jp: ["maan6","jan4","zou6","soeng6","maan6","nin4","naan4","maai5","ngai6","seot6","git6","zok3"] },
            { chars: ["从","未","获","得","当","时","留","意"], jp: ["cung4","mei6","wok6","dak1","dong1","si4","lau4","ji3"] },
            { chars: ["难","道","人","死","商","业","才","计","得","到","他","价","格"], jp: ["naan4","dou6","jan4","sei2","soeng1","jip6","coi4","gai3","dak1","dou3","taa1","gaa3","gaak3"] },
            { chars: ["难","道","妥","协","一","划"], jp: ["naan4","dou6","to5","hip3","jat1","waak6"] },
            { chars: ["难","道","放","弃","风","格"], jp: ["naan4","dou6","fong3","hei3","fung1","gaak3"] },
            { chars: ["跟","风","一","下","然","后","暴","发"], jp: ["gan1","fung1","jat1","haa5","jin4","hau6","bou6","faat3"] },
            { paragraphBreak: true },
            { chars: ["你","听","过","梵","高","吧"], jp: ["nei5","ting1","gwo3","faan6","gou1","baa6"] },
            { chars: ["值","几","多","百"], jp: ["zik6","gei2","do1","baak3"] },
            { chars: ["只","有","人","格"], jp: ["zi2","jau5","jan4","gaak3"] },
            { chars: ["难","表","白"], jp: ["naan4","biu2","baak6"] },
            { chars: ["求","存","人","人","明","白"], jp: ["kau4","cyun4","jan4","jan4","ming4","baak6"] },
            { chars: ["看","　","他","有","权","乱","去","画"], jp: ["hon3","","taa1","jau5","kyun4","lyun6","heoi3","waak6"] },
            { chars: ["也","许","口","袋"], jp: ["jaa5","heoi2","hau2","doi6"] },
            { chars: ["也","不","致","一","片","空","白"], jp: ["jaa5","bat1","zi3","jat1","pin3","hung1","baak6"] },
            { paragraphBreak: true },
            { chars: ["卖","完","又","买","卖","完","又","买","凭","谁","订","价"], jp: ["maai6","jyun4","jau6","maai5","maai6","jyun4","jau6","maai5","pang4","seoi4","ding3","gaa3"] },
            { chars: ["凭","卖","艺","讨","生","活","谁","会","沦","落","似"], jp: ["pang4","maai6","ngai6","tou2","sang1","wut6","seoi4","wui6","leon4","lok6","ci5"] },
            { chars: ["这","精","神","病","院","关","起","的","过","客"], jp: ["ze5","zing1","san4","beng6","jyun2","gwaan1","hei2","dik1","gwo3","haak3"] },
            { chars: ["难","活","到","了","不","惑"], jp: ["naan4","wut6","dou3","liu5","bat1","waak6"] },
            { chars: ["留","下","了","他","风","格"], jp: ["lau4","haa6","liu5","taa1","fung1","gaak3"] },
            { chars: ["很","想","清","醒","无","耐","病","发"], jp: ["han2","soeng2","cing1","sing2","mou4","noi6","beng6","faat3"] },
            { paragraphBreak: true },
            { chars: ["看","一","个","人","的","命"], jp: ["hon3","jat1","go3","jan4","dik1","ming6"] },
            { chars: ["或","者","悲","惨"], jp: ["waak6","ze2","bei1","caam2"] },
            { chars: ["他","到","临","终","仍","肯","画"], jp: ["taa1","dou3","lam4","zung1","jing4","hang2","waak6"] },
            { chars: ["仍","然","贡","献","世","间"], jp: ["jing4","jin4","gung3","hin3","sai3","gaan1"] },
            { chars: ["看","他","看","长","夜","星","空"], jp: ["hon3","taa1","hon3","coeng4","je6","sing1","hung1"] },
            { chars: ["那","种","灿","烂"], jp: ["naa5","zung2","caan3","laan6"] },
            { chars: ["显","得","世","间","太","苍","白"], jp: ["hin2","dak1","sai3","gaan1","taai3","cong1","baak6"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
