// 歌曲：稀客

(function() {
    const song = {
        id: 537,
        title: "稀客",
        titleJyutping: ["hei1","haak3"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["为","何","男","孩","都","这","副","德","性"], jp: ["wai4","ho4","naam4","haai4","dou1","ze5","fu3","dak1","sing3"] },
            { chars: ["没","法","忍","受","欲","望","停","定"], jp: ["mut6","faat3","jan2","sau6","juk6","mong6","ting4","ding6"] },
            { chars: ["年","轻","要","任","性"], jp: ["nin4","hing1","jiu3","jam6","sing3"] },
            { chars: ["外","出","要","尽","兴"], jp: ["ngoi6","ceot1","jiu3","zeon6","hing1"] },
            { chars: ["热","恋","也","像","驱","车","过","境"], jp: ["jit6","lyun2","jaa5","zoeng6","keoi1","ce1","gwo3","ging2"] },
            { chars: ["好","好","观","光"], jp: ["hou2","hou2","gun1","gwong1"] },
            { chars: ["亲","手","摄","影"], jp: ["can1","sau2","sip3","jing2"] },
            { chars: ["抱","抱","陌","生","的","背","影"], jp: ["pou5","pou5","mak6","sang1","dik1","bui3","jing2"] },
            { chars: ["然","后","你","继","续","行","程"], jp: ["jin4","hau6","nei5","gai3","zuk6","hang4","cing4"] },
            { chars: ["玩","遍","每","座","城"], jp: ["wun6","pin3","mui5","zo6","sing4"] },
            { chars: ["护","照","里","盖","上","各","式","签","证"], jp: ["wu6","ziu3","leoi5","goi3","soeng6","gok3","sik1","cim1","zing3"] },
            { paragraphBreak: true },
            { chars: ["游","客","是","你","风","景","是","我"], jp: ["jau4","haak3","si6","nei5","fung1","ging2","si6","ngo5"] },
            { chars: ["无","法","避","免","让","你","经","过"], jp: ["mou4","faat3","bei6","min5","joeng6","nei5","ging1","gwo3"] },
            { chars: ["蔷","薇","如","期","盛","放"], jp: ["coeng4","mei4","jyu4","kei4","sing6","fong3"] },
            { chars: ["游","人","如","期","过","路"], jp: ["jau4","jan4","jyu4","kei4","gwo3","lou6"] },
            { chars: ["情","人","如","期","相","爱","至","到","分","开"], jp: ["cing4","jan4","jyu4","kei4","soeng1","ngoi3","zi3","dou3","fan1","hoi1"] },
            { paragraphBreak: true },
            { chars: ["就","像","命","书","中","批","过"], jp: ["zau6","zoeng6","ming6","syu1","zung1","pai1","gwo3"] },
            { chars: ["在","最","后","都","化","作","乌","有"], jp: ["zoi6","zeoi3","hau6","dou1","faa3","zok3","wu1","jau5"] },
            { chars: ["但","那","天","曾","实","在","华","丽","地","邂","逅"], jp: ["daan6","naa5","tin1","zang1","sat6","zoi6","waa4","lai6","dei6","haai5","hau6"] },
            { chars: ["早","发","生","过"], jp: ["zou2","faat3","sang1","gwo3"] },
            { chars: ["好","等","你","继","续","走"], jp: ["hou2","dang2","nei5","gai3","zuk6","zau2"] },
            { paragraphBreak: true },
            { chars: ["年","华","磨","成","的","精","致","优","雅"], jp: ["nin4","waa4","mo4","sing4","dik1","zing1","zi3","jau1","ngaa5"] },
            { chars: ["未","够","一","夜","便","用","完","吧"], jp: ["mei6","gau3","jat1","je6","bin6","jung6","jyun4","baa6"] },
            { chars: ["由","稀","客","路","过"], jp: ["jau4","hei1","haak3","lou6","gwo3"] },
            { chars: ["玩","赏","赞","誉","过"], jp: ["wun6","soeng2","zaan3","jyu6","gwo3"] },
            { chars: ["什","么","故","事","也","没","留","下"], jp: ["sap6","mo1","gu3","si6","jaa5","mut6","lau4","haa6"] },
            { chars: ["山","光","水","色"], jp: ["saan1","gwong1","seoi2","sik1"] },
            { chars: ["芳","草","野","花"], jp: ["fong1","cou2","je5","faa1"] },
            { chars: ["你","那","日","记","写","过","吗"], jp: ["nei5","naa5","jat6","gei3","se2","gwo3","maa1"] },
            { chars: ["难","道","我","美","丽","年","华"], jp: ["naan4","dou6","ngo5","mei5","lai6","nin4","waa4"] },
            { chars: ["为","装","饰","一","下"], jp: ["wai4","zong1","sik1","jat1","haa5"] },
            { chars: ["夜","里","你","那","无","聊","的","牵","挂"], jp: ["je6","leoi5","nei5","naa5","mou4","liu4","dik1","hin1","gwaa3"] },
            { paragraphBreak: true },
            { chars: ["游","客","是","你","风","景","是","我"], jp: ["jau4","haak3","si6","nei5","fung1","ging2","si6","ngo5"] },
            { chars: ["无","法","避","免","让","你","经","过"], jp: ["mou4","faat3","bei6","min5","joeng6","nei5","ging1","gwo3"] },
            { chars: ["蔷","薇","如","期","盛","放"], jp: ["coeng4","mei4","jyu4","kei4","sing6","fong3"] },
            { chars: ["游","人","如","期","过","路"], jp: ["jau4","jan4","jyu4","kei4","gwo3","lou6"] },
            { chars: ["情","人","如","期","相","爱","至","到","分","开"], jp: ["cing4","jan4","jyu4","kei4","soeng1","ngoi3","zi3","dou3","fan1","hoi1"] },
            { paragraphBreak: true },
            { chars: ["就","像","命","书","中","批","过"], jp: ["zau6","zoeng6","ming6","syu1","zung1","pai1","gwo3"] },
            { chars: ["在","最","后","都","化","作","乌","有"], jp: ["zoi6","zeoi3","hau6","dou1","faa3","zok3","wu1","jau5"] },
            { chars: ["但","那","天","曾","实","在","华","丽","地","邂","逅"], jp: ["daan6","naa5","tin1","zang1","sat6","zoi6","waa4","lai6","dei6","haai5","hau6"] },
            { chars: ["早","发","生","过"], jp: ["zou2","faat3","sang1","gwo3"] },
            { chars: ["不","阻","你","继","续","走"], jp: ["bat1","zo2","nei5","gai3","zuk6","zau2"] },
            { paragraphBreak: true },
            { chars: ["命","运","暂","且","的","交","错"], jp: ["ming6","wan6","zaam6","ce2","dik1","gaau1","co3"] },
            { chars: ["在","最","后","都","化","作","乌","有"], jp: ["zoi6","zeoi3","hau6","dou1","faa3","zok3","wu1","jau5"] },
            { chars: ["但","那","天","曾","实","在","华","丽","地","邂","逅"], jp: ["daan6","naa5","tin1","zang1","sat6","zoi6","waa4","lai6","dei6","haai5","hau6"] },
            { chars: ["这","个","诅","咒"], jp: ["ze5","go3","zo3","zau3"] },
            { chars: ["不","知","算","应","了","没","有"], jp: ["bat1","zi1","syun3","jing3","liu5","mut6","jau5"] },
            { paragraphBreak: true },
            { chars: ["即","使","间","相","恋","像","化","缘"], jp: ["zik1","si2","gaan1","soeng1","lyun2","zoeng6","faa3","jyun4"] },
            { chars: ["以","后","亦","无","内","疚","还","哪","有","借","口"], jp: ["ji5","hau6","jik6","mou4","noi6","gau3","waan4","naa5","jau5","ze3","hau2"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
