// 歌曲：空港（live）

(function() {
    const song = {
        id: 491,
        title: "空港（live）",
        titleJyutping: ["hung1","gong2","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "Skot Suyama/梁永泰",
        composerJyutping: ["","","","","","","","","","","","","loeng4","wing5","taai3"],
        lyrics: [
            { chars: ["只","知","要","飞"], jp: ["zi2","zi1","jiu3","fei1"] },
            { chars: ["但","是","不","知","高","处"], jp: ["daan6","si6","bat1","zi1","gou1","cyu5"] },
            { chars: ["会","抽","光","我","的","氧","气"], jp: ["wui6","cau1","gwong1","ngo5","dik1","joeng5","hei3"] },
            { chars: ["当","初","我","这","班","客","机"], jp: ["dong1","co1","ngo5","ze5","baan1","haak3","gei1"] },
            { chars: ["曾","羡","慕","空","中","的","鸟"], jp: ["zang1","sin6","mou6","hung1","zung1","dik1","niu5"] },
            { chars: ["要","展","开","我","的","两","臂"], jp: ["jiu3","zin2","hoi1","ngo5","dik1","loeng5","bei3"] },
            { chars: ["跌","痛","了"], jp: ["dit3","tung3","liu5"] },
            { chars: ["我","会","努","力","从","原","地","起"], jp: ["ngo5","wui6","nou5","lik6","cung4","jyun4","dei6","hei2"] },
            { chars: ["到","了","最","终"], jp: ["dou3","liu5","zeoi3","zung1"] },
            { chars: ["总","算"," ","学","会","飞"], jp: ["zung2","syun3","","hok6","wui6","fei1"] },
            { chars: ["但","为","什","么"], jp: ["daan6","wai4","sap6","maa1"] },
            { chars: ["捉","到","浮","云"], jp: ["zuk1","dou3","fau4","wan4"] },
            { chars: ["才","想","起"], jp: ["coi4","soeng2","hei2"] },
            { paragraphBreak: true },
            { chars: ["谁","的","光"], jp: ["seoi4","dik1","gwong1"] },
            { chars: ["如","常","为","我","筑","起"], jp: ["jyu4","soeng4","wai4","ngo5","zuk1","hei2"] },
            { chars: ["这","空","港"], jp: ["ze5","hung1","gong2"] },
            { chars: ["何","时","若","觉","不","安"], jp: ["ho4","si4","joek6","gok3","bat1","on1"] },
            { chars: ["都","清","楚","灯","塔","会","于","哪","方"], jp: ["dou1","cing1","co2","dang1","taap3","wui6","jyu1","naa5","fong1"] },
            { chars: ["迷","失","了","到","底","要","飞","哪","方"], jp: ["mai4","sat1","liu5","dou3","dai2","jiu3","fei1","naa5","fong1"] },
            { chars: ["y","e","a","h"," ","y","e","a","h"], jp: ["","","","","","","","",""] },
            { chars: ["云","苍","苍"], jp: ["wan4","cong1","cong1"] },
            { chars: ["茫","茫","长","夜","里","感","激"], jp: ["mong4","mong4","coeng4","je6","lei5","gam2","gik1"] },
            { chars: ["有","空","港"], jp: ["jau5","hung1","gong2"] },
            { chars: ["云","层","上","满","星","光"], jp: ["wan4","cang4","soeng6","mun5","sing1","gwong1"] },
            { chars: ["星","星","不","知","道","我","的","怯","慌"], jp: ["sing1","sing1","bat1","zi1","dou6","ngo5","dik1","hip3","fong1"] },
            { chars: ["人","间","却","有","殷","切","的","眼","光"], jp: ["jan4","gaan1","koek3","jau5","jan1","cit3","dik1","ngaan5","gwong1"] },
            { chars: ["仰","望"," ","我","下","降"], jp: ["joeng5","mong6","","ngo5","haa6","gong3"] },
            { paragraphBreak: true },
            { chars: ["我","惯","了"], jp: ["ngo5","gwaan3","liu5"] },
            { chars: ["世","界","各","地","来","回","地","飞"], jp: ["sai3","gaai3","gok3","dei6","loi4","wui4","dei6","fei1"] },
            { chars: ["却","怕","有","一","天","我"], jp: ["koek3","paa3","jau5","jat1","tin1","ngo5"] },
            { chars: ["下","了","机"], jp: ["haa6","liu5","gei1"] },
            { chars: ["站","在","陌","生","的","星","球","时"], jp: ["zaam6","zoi6","mak6","sang1","dik1","sing1","kau4","si4"] },
            { chars: ["才","伤","悲"], jp: ["coi4","soeng1","bei1"] },
            { paragraphBreak: true },
            { chars: ["谁","的","光"], jp: ["seoi4","dik1","gwong1"] },
            { chars: ["如","常","为","我","筑","起"], jp: ["jyu4","soeng4","wai4","ngo5","zuk1","hei2"] },
            { chars: ["这","空","港"], jp: ["ze5","hung1","gong2"] },
            { chars: ["曾","忙","着","破","天","荒"], jp: ["zang1","mong4","zoek6","po3","tin1","fong1"] },
            { chars: ["不","清","楚","心","要","放","于","哪","方"], jp: ["bat1","cing1","co2","sam1","jiu3","fong3","jyu1","naa5","fong1"] },
            { chars: ["谁","给","我","盖","好","被","讲","晚","安"], jp: ["seoi4","kap1","ngo5","goi3","hou2","bei6","gong2","maan5","on1"] },
            { chars: ["y","e","a","h"," ","y","e","a","h"], jp: ["","","","","","","","",""] },
            { chars: ["云","苍","苍"], jp: ["wan4","cong1","cong1"] },
            { chars: ["茫","茫","长","夜","里","感","激"], jp: ["mong4","mong4","coeng4","je6","lei5","gam2","gik1"] },
            { chars: ["有","空","港"], jp: ["jau5","hung1","gong2"] },
            { chars: ["云","层","上","满","星","光"], jp: ["wan4","cang4","soeng6","mun5","sing1","gwong1"] },
            { chars: ["星","星","不","知","道","我","的","怯","慌"], jp: ["sing1","sing1","bat1","zi1","dou6","ngo5","dik1","hip3","fong1"] },
            { chars: ["人","间","却","有","殷","切","的","眼","光"], jp: ["jan4","gaan1","koek3","jau5","jan1","cit3","dik1","ngaan5","gwong1"] },
            { chars: ["每","夜"," ","往","上","看"], jp: ["mui5","je6","","wong5","soeng6","hon3"] },
            { paragraphBreak: true },
            { chars: ["(","从","高","处",")"], jp: ["","cung4","gou1","cyu5",""] },
            { chars: ["往","下","看"], jp: ["wong5","haa6","hon3"] },
            { chars: ["~"], jp: [""] },
            { chars: ["(","迷","失","里",")"], jp: ["","mai4","sat1","lei5",""] },
            { chars: ["你","的","爱","好","比"], jp: ["nei5","dik1","ngoi3","hou2","bei2"] },
            { chars: ["~"," ","一","个","网"], jp: ["","","jat1","go3","mong5"] },
            { chars: ["往","下","看"], jp: ["wong5","haa6","hon3"] },
            { chars: ["(","台","风","里",")"], jp: ["","toi4","fung1","lei5",""] },
            { chars: ["的","空","港"], jp: ["dik1","hung1","gong2"] },
            { chars: ["~"," ","(","唯","一","你",")"], jp: ["","","","wai4","jat1","nei5",""] },
            { chars: ["会","等","我","心","足","了","飞","够","了"], jp: ["wui6","dang2","ngo5","sam1","zuk1","liu5","fei1","gau3","liu5"] },
            { chars: ["再","下","降"], jp: ["zoi3","haa6","gong3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
