// 歌曲：花洒

(function() {
    const song = {
        id: 931,
        title: "花洒",
        titleJyutping: ["faa1","saa2"],
        artist: "古巨基",
        artistJyutping: ["gu2","geoi6","gei1"],
        lyricist: "王菀之",
        lyricistJyutping: ["wong4","jyun2","zi1"],
        composer: "林夕",
        composerJyutping: ["lam4","zik6"],
        lyrics: [
            { chars: ["为","了","要","博","世","界","赞","美"], jp: ["wai4","liu5","jiu3","bok3","sai3","gaai3","zaan3","mei5"] },
            { chars: ["便","苦","恼"], jp: ["bin6","fu2","nou5"] },
            { chars: ["害","怕","永","远","也","做","不","到"], jp: ["hoi6","paa3","wing5","jyun5","jaa5","zou6","bat1","dou3"] },
            { chars: ["忘","掉","了","偶","尔","懒","理","世","界","或","会","更","好"], jp: ["mong4","diu6","liu5","ngau5","ji5","laan5","lei5","sai3","gaai3","waak6","wui6","gang1","hou2"] },
            { chars: ["期","望","要","有","这","个","与","那","个"], jp: ["kei4","mong6","jiu3","jau5","ze5","go3","jyu5","naa5","go3"] },
            { chars: ["像","匹","布"], jp: ["zoeng6","pat1","bou3"] },
            { chars: ["被","剪","碎","飞","舞"], jp: ["bei6","zin2","seoi3","fei1","mou5"] },
            { chars: ["盲","目","了","两","眼","也","但","求"], jp: ["maang4","muk6","liu5","loeng5","ngaan5","jaa5","daan6","kau4"] },
            { chars: ["要","拾","到"], jp: ["jiu3","sap6","dou3"] },
            { paragraphBreak: true },
            { chars: ["何","必","要","做","奴","隶"], jp: ["ho4","bit1","jiu3","zou6","nou4","dai6"] },
            { chars: ["无","需","要","为","失","去","了","的","执","迷"], jp: ["mou4","seoi1","jiu3","wai4","sat1","heoi3","liu5","dik1","zap1","mai4"] },
            { chars: ["轮","流","凉","或","暖","像","四","季"], jp: ["leon4","lau4","loeng4","waak6","nyun5","zoeng6","sei3","gwai3"] },
            { chars: ["做","人","做","过","世"], jp: ["zou6","jan4","zou6","gwo3","sai3"] },
            { chars: ["漫","长","年","月","有","路","轨"], jp: ["maan6","coeng4","nin4","jyut6","jau5","lou6","gwai2"] },
            { chars: ["人","总","想","拥","有","东","西"], jp: ["jan4","zung2","soeng2","jung2","jau5","dung1","sai1"] },
            { chars: ["要","是","代","价","高"], jp: ["jiu3","si6","doi6","gaa3","gou1"] },
            { chars: ["越","令","心","中","牵","系"], jp: ["jyut6","ling6","sam1","zung1","hin1","hai6"] },
            { chars: ["担","忧","要","是","无","谓"], jp: ["daam1","jau1","jiu3","si6","mou4","wai6"] },
            { chars: ["拿","花","洒","洗","礼"], jp: ["naa4","faa1","saa2","sai2","lai5"] },
            { paragraphBreak: true },
            { chars: ["为","了","要","与","某","某","爱","上"], jp: ["wai4","liu5","jiu3","jyu5","mau5","mau5","ngoi3","soeng6"] },
            { chars: ["便","希","冀"], jp: ["bin6","hei1","kei3"] },
            { chars: ["为","了","挫","折","过"], jp: ["wai4","liu5","co3","zit3","gwo3"] },
            { chars: ["便","紧","记"], jp: ["bin6","gan2","gei3"] },
            { chars: ["全","为","贡","献","过"], jp: ["cyun4","wai4","gung3","hin3","gwo3"] },
            { chars: ["要","有","报","答"], jp: ["jiu3","jau5","bou3","daap3"] },
            { chars: ["便","有","对","比"], jp: ["bin6","jau5","deoi3","bei2"] },
            { chars: ["全","为","看","中","过"], jp: ["cyun4","wai4","hon3","zung3","gwo3"] },
            { chars: ["发","觉","看","错"], jp: ["faat3","gok3","hon3","co3"] },
            { chars: ["便","生","气"], jp: ["bin6","sang1","hei3"] },
            { chars: ["甚","么","叫","天","理"], jp: ["sam6","mo1","giu3","tin1","lei5"] },
            { chars: ["忘","掉","奋","斗","过","要","随","缘"], jp: ["mong4","diu6","fan5","dau3","gwo3","jiu3","ceoi4","jyun4"] },
            { chars: ["信","命","理"], jp: ["seon3","ming6","lei5"] },
            { paragraphBreak: true },
            { chars: ["何","必","要","做","奴","隶"], jp: ["ho4","bit1","jiu3","zou6","nou4","dai6"] },
            { chars: ["无","需","要","为","失","去","了","的","执","迷"], jp: ["mou4","seoi1","jiu3","wai4","sat1","heoi3","liu5","dik1","zap1","mai4"] },
            { chars: ["轮","流","凉","或","暖","像","四","季"], jp: ["leon4","lau4","loeng4","waak6","nyun5","zoeng6","sei3","gwai3"] },
            { chars: ["做","人","做","过","世"], jp: ["zou6","jan4","zou6","gwo3","sai3"] },
            { chars: ["漫","长","年","月","有","路","轨"], jp: ["maan6","coeng4","nin4","jyut6","jau5","lou6","gwai2"] },
            { chars: ["人","总","想","拥","有","东","西"], jp: ["jan4","zung2","soeng2","jung2","jau5","dung1","sai1"] },
            { chars: ["要","是","代","价","高"], jp: ["jiu3","si6","doi6","gaa3","gou1"] },
            { chars: ["越","令","心","中","牵","系"], jp: ["jyut6","ling6","sam1","zung1","hin1","hai6"] },
            { chars: ["担","忧","要","是","无","谓"], jp: ["daam1","jau1","jiu3","si6","mou4","wai6"] },
            { chars: ["拿","花","洒","洗","礼"], jp: ["naa4","faa1","saa2","sai2","lai5"] },
            { paragraphBreak: true },
            { chars: ["梳","化","自","在","自","在","齐","齐","坐"], jp: ["so1","faa2","zi6","zoi6","zi6","zoi6","cai4","cai4","zo6"] },
            { chars: ["拿","去","它","都","总","可","去","站","去","跑"], jp: ["naa4","heoi3","taa1","dou1","zung2","ho2","heoi3","zaam6","heoi3","paau2"] },
            { chars: ["无","谓","靠","甚","么"], jp: ["mou4","wai6","kaau3","sam6","mo1"] },
            { paragraphBreak: true },
            { chars: ["何","不","将","一","切","抛","低"], jp: ["ho4","bat1","zoeng1","jat1","cai3","paau1","dai1"] },
            { chars: ["志","愿","大","过","天"], jp: ["zi3","jyun6","daai6","gwo3","tin1"] },
            { chars: ["亦","像","世","上","蝼","蚁"], jp: ["jik6","zoeng6","sai3","soeng6","lau4","ngai5"] },
            { chars: ["星","星","永","未","流","逝"], jp: ["sing1","sing1","wing5","mei6","lau4","sai6"] },
            { chars: ["如","只","可","感","叹","它","美","丽"], jp: ["jyu4","zi2","ho2","gam2","taan3","taa1","mei5","lai6"] },
            { chars: ["得","到","也","是","无","谓"], jp: ["dak1","dou3","jaa5","si6","mou4","wai6"] },
            { chars: ["负","担","高","过","天","际"], jp: ["fu6","daam1","gou1","gwo3","tin1","zai3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
