// 歌曲：苦瓜

(function() {
    const song = {
        id: 958,
        title: "苦瓜",
        titleJyutping: ["fu2","gwaa1"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "章霈迎",
        composerJyutping: ["zoeng1","pui3","jing4"],
        lyrics: [
            { chars: ["共","你","干","杯","再","举","箸"], jp: ["gung6","nei5","gon1","bui1","zoi3","geoi2","zyu6"] },
            { chars: ["突","然","间","相","看","莞","尔"], jp: ["dat6","jin4","gaan1","soeng1","hon3","gun1","ji5"] },
            { chars: ["盘","中","透","着","那","味","儿"], jp: ["pun4","zung1","tau3","zoek6","naa5","mei6","ji4"] },
            { chars: ["大","概","今","生","有","些","事"], jp: ["daai6","koi3","gam1","sang1","jau5","se1","si6"] },
            { chars: ["是","提","早","都","不","可","以"], jp: ["si6","tai4","zou2","dou1","bat1","ho2","ji5"] },
            { chars: ["明","白","其","妙","处"], jp: ["ming4","baak6","kei4","miu6","cyu5"] },
            { chars: ["就","像","你","当","日","痛","心","她","回","绝","一","番","美","意"], jp: ["zau6","zoeng6","nei5","dong1","jat6","tung3","sam1","taa1","wui4","zyut6","jat1","faan1","mei5","ji3"] },
            { chars: ["怎","发","现","你","从","情","劫","亦","能","学","懂","开","解","与","宽","恕"], jp: ["zam2","faat3","jin6","nei5","cung4","cing4","gip3","jik6","nang4","hok6","dung2","hoi1","gaai2","jyu5","fun1","syu3"] },
            { chars: ["也","像","我","很","纠","结","的","公","事"], jp: ["jaa5","zoeng6","ngo5","han2","gau2","git3","dik1","gung1","si6"] },
            { chars: ["此","际","回","头","看"], jp: ["ci2","zai3","wui4","tau4","hon3"] },
            { chars: ["原","来","并","没","有","事"], jp: ["jyun4","loi4","bing6","mut6","jau5","si6"] },
            { paragraphBreak: true },
            { chars: ["真","想","不","到","当","初","我","们","也","讨","厌","吃","苦","瓜"], jp: ["zan1","soeng2","bat1","dou3","dong1","co1","ngo5","mun4","jaa5","tou2","jim3","hek3","fu2","gwaa1"] },
            { chars: ["今","天","竟","吃","得","出","那","睿","智","愈","来","愈","记","挂"], jp: ["gam1","tin1","ging2","hek3","dak1","ceot1","naa5","jeoi6","zi3","jyu6","loi4","jyu6","gei3","gwaa3"] },
            { chars: ["开","始","时","挨","一","些","苦"], jp: ["hoi1","ci2","si4","aai1","jat1","se1","fu2"] },
            { chars: ["栽","种","绝","处","的","花"], jp: ["zoi1","zung2","zyut6","cyu5","dik1","faa1"] },
            { chars: ["幸","得","艰","辛","的","引","路","甜","蜜","不","致","太","寡"], jp: ["hang6","dak1","gaan1","san1","dik1","jan5","lou6","tim4","mat6","bat1","zi3","taai3","gwaa2"] },
            { paragraphBreak: true },
            { chars: ["青","春","的","快","餐","只","要","求","快","不","理","哪","一","家"], jp: ["cing1","ceon1","dik1","faai3","caan1","zi2","jiu3","kau4","faai3","bat1","lei5","naa5","jat1","gaa1"] },
            { chars: ["哪","有","玩","味","的","空","档","来","欣","赏","细","致","淡","雅"], jp: ["naa5","jau5","wun6","mei6","dik1","hung1","dong2","loi4","jan1","soeng2","sai3","zi3","daam6","ngaa5"] },
            { chars: ["到","大","悟","大","彻","将","虎","咽","的","升","华"], jp: ["dou3","daai6","ng6","daai6","cit3","zoeng1","fu2","jin1","dik1","sing1","waa4"] },
            { chars: ["等","消","化","学","沏","茶"], jp: ["dang2","siu1","faa3","hok6","cai3","caa4"] },
            { chars: ["至","共","你","觉","得","苦","也"], jp: ["zi3","gung6","nei5","gok3","dak1","fu2","jaa5"] },
            { chars: ["不","太","差"], jp: ["bat1","taai3","caa1"] },
            { paragraphBreak: true },
            { chars: ["下","半","生","竟","再","开","学"], jp: ["haa6","bun3","sang1","ging2","zoi3","hoi1","hok6"] },
            { chars: ["入","迷","的","终","于","醒","觉"], jp: ["jap6","mai4","dik1","zung1","jyu1","sing2","gok3"] },
            { chars: ["移","走","最","后","的","死","角"], jp: ["ji4","zau2","zeoi3","hau6","dik1","sei2","gok3"] },
            { chars: ["用","痛","苦","烘","托","欢","乐"], jp: ["jung6","tung3","fu2","hung3","tok3","fun1","lok6"] },
            { chars: ["让","余","甘","彰","显","险","恶"], jp: ["joeng6","jyu4","gam1","zoeng1","hin2","him2","ok3"] },
            { chars: ["如","艺","坛","杰","作"], jp: ["jyu4","ngai6","taan4","git6","zok3"] },
            { chars: ["就","像","我","一","直","听","香","夭","从","未","沾","湿","眼","角"], jp: ["zau6","zoeng6","ngo5","jat1","zik6","ting1","hoeng1","jiu1","cung4","mei6","zim1","sap1","ngaan5","gok3"] },
            { chars: ["仔","细","地","看","神","坛","里","木","纹","什","么","精","巧","也","不","觉"], jp: ["zai2","sai3","dei6","hon3","san4","taan4","leoi5","muk6","man4","sap6","mo1","zing1","haau2","jaa5","bat1","gok3"] },
            { chars: ["却","在","某","萧","瑟","晚","秋","深","夜"], jp: ["koek3","zoi6","mau5","siu1","sat1","maan5","cau1","sam1","je6"] },
            { chars: ["忽","尔","明","了","了"], jp: ["fat1","ji5","ming4","liu5","liu5"] },
            { chars: ["而","黄","叶","便","碎","落"], jp: ["ji4","wong4","jip6","bin6","seoi3","lok6"] },
            { paragraphBreak: true },
            { chars: ["真","想","不","到","当","初","我","们","也","讨","厌","吃","苦","瓜"], jp: ["zan1","soeng2","bat1","dou3","dong1","co1","ngo5","mun4","jaa5","tou2","jim3","hek3","fu2","gwaa1"] },
            { chars: ["今","天","竟","吃","得","出","那","睿","智","愈","来","愈","记","挂"], jp: ["gam1","tin1","ging2","hek3","dak1","ceot1","naa5","jeoi6","zi3","jyu6","loi4","jyu6","gei3","gwaa3"] },
            { chars: ["开","始","时","挨","一","些","苦"], jp: ["hoi1","ci2","si4","aai1","jat1","se1","fu2"] },
            { chars: ["栽","种","绝","处","的","花"], jp: ["zoi1","zung2","zyut6","cyu5","dik1","faa1"] },
            { chars: ["幸","得","艰","辛","的","引","路","甜","蜜","不","致","太","寡"], jp: ["hang6","dak1","gaan1","san1","dik1","jan5","lou6","tim4","mat6","bat1","zi3","taai3","gwaa2"] },
            { paragraphBreak: true },
            { chars: ["青","春","的","快","餐","只","要","求","快","不","理","哪","一","家"], jp: ["cing1","ceon1","dik1","faai3","caan1","zi2","jiu3","kau4","faai3","bat1","lei5","naa5","jat1","gaa1"] },
            { chars: ["哪","有","玩","味","的","空","档","来","欣","赏","细","致","淡","雅"], jp: ["naa5","jau5","wun6","mei6","dik1","hung1","dong2","loi4","jan1","soeng2","sai3","zi3","daam6","ngaa5"] },
            { chars: ["到","大","悟","大","彻","将","虎","咽","的","升","华"], jp: ["dou3","daai6","ng6","daai6","cit3","zoeng1","fu2","jin1","dik1","sing1","waa4"] },
            { chars: ["等","消","化","学","沏","茶"], jp: ["dang2","siu1","faa3","hok6","cai3","caa4"] },
            { chars: ["至","共","你","觉","得","苦","也"], jp: ["zi3","gung6","nei5","gok3","dak1","fu2","jaa5"] },
            { chars: ["不","太","差"], jp: ["bat1","taai3","caa1"] },
            { paragraphBreak: true },
            { chars: ["做","人","没","有","苦","涩","可","以","吗"], jp: ["zou6","jan4","mut6","jau5","fu2","gip3","ho2","ji5","maa1"] },
            { paragraphBreak: true },
            { chars: ["真","想","不","到","当","初","我","们","也","讨","厌","吃","苦","瓜"], jp: ["zan1","soeng2","bat1","dou3","dong1","co1","ngo5","mun4","jaa5","tou2","jim3","hek3","fu2","gwaa1"] },
            { chars: ["当","睇","清","世","间","所","有","定","理","又","何","用","再","怕"], jp: ["dong1","tai2","cing1","sai3","gaan1","so2","jau5","ding6","lei5","jau6","ho4","jung6","zoi3","paa3"] },
            { chars: ["珍","惜","淡","定","的","心","境"], jp: ["zan1","sik1","daam6","ding6","dik1","sam1","ging2"] },
            { chars: ["苦","过","后","更","加","清"], jp: ["fu2","gwo3","hau6","gang3","gaa1","cing1"] },
            { chars: ["万","般","过","去","亦","无","味","但","有","领","会","留","下"], jp: ["maan6","bun1","gwo3","heoi3","jik6","mou4","mei6","daan6","jau5","ling5","wui6","lau4","haa6"] },
            { paragraphBreak: true },
            { chars: ["今","天","先","记","得","听","过","人","说","这","叫","半","生","瓜"], jp: ["gam1","tin1","sin1","gei3","dak1","ting1","gwo3","jan4","syut3","ze5","giu3","bun3","sang1","gwaa1"] },
            { chars: ["那","意","味","着","它","的","美","年","轻","不","会","洞","察","吗"], jp: ["naa5","ji3","mei6","zoek6","taa1","dik1","mei5","nin4","hing1","bat1","wui6","dung6","caat3","maa1"] },
            { chars: ["到","大","悟","大","彻","将","一","切","都","升","华"], jp: ["dou3","daai6","ng6","daai6","cit3","zoeng1","jat1","cai3","dou1","sing1","waa4"] },
            { chars: ["这","一","秒","坐","拥","晚","霞"], jp: ["ze5","jat1","miu5","zo6","jung2","maan5","haa4"] },
            { chars: ["我","共","你","觉","得","苦","也"], jp: ["ngo5","gung6","nei5","gok3","dak1","fu2","jaa5"] },
            { chars: ["不","太","差"], jp: ["bat1","taai3","caa1"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
