// 歌曲：落花流水

(function() {
    const song = {
        id: 806,
        title: "落花流水",
        titleJyutping: ["lok6","faa1","lau4","seoi2"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "郭伟亮/陈奕迅",
        composerJyutping: ["gwok3","wai5","loeng6","","can4","jik6","seon3"],
        lyrics: [
            { chars: ["流","水","像","清","得","没","带","半","颗","沙"], jp: ["lau4","seoi2","zoeng6","cing1","dak1","mut6","daai3","bun3","fo2","saa1"] },
            { chars: ["前","身","被","搁","在","上","游","风","化"], jp: ["cin4","san1","bei6","gok3","zoi6","soeng6","jau4","fung1","faa3"] },
            { chars: ["但","那","天","经","过","那","条","提","坝"], jp: ["daan6","naa5","tin1","ging1","gwo3","naa5","tiu4","tai4","baa3"] },
            { chars: ["斜","阳","又","返","照","闪","一","下"], jp: ["ce4","joeng4","jau6","faan2","ziu3","sim2","jat1","haa5"] },
            { chars: ["遇","上","一","朵","落","花"], jp: ["jyu6","soeng5","jat1","do2","lok6","faa1"] },
            { paragraphBreak: true },
            { chars: ["相","遇","就","此","拥","着","最","爱","归","家"], jp: ["soeng1","jyu6","zau6","ci2","jung2","zoek6","zeoi3","ngoi3","gwai1","gaa1"] },
            { chars: ["生","活","别","过","份","地","童","话","化"], jp: ["sang1","wut6","bit6","gwo3","fan6","dei6","tung4","waa6","faa3"] },
            { chars: ["故","事","假","使","短","过","这","五","月","落","霞"], jp: ["gu3","si6","gaa2","si2","dyun2","gwo3","ze5","ng5","jyut6","lok6","haa4"] },
            { chars: ["没","有","需","要","惊","诧"], jp: ["mut6","jau5","seoi1","jiu3","ging1","caa3"] },
            { paragraphBreak: true },
            { chars: ["流","水","很","清","楚"], jp: ["lau4","seoi2","han2","cing1","co2"] },
            { chars: ["惜","花","这","个","责","任"], jp: ["sik1","faa1","ze5","go3","zaak3","jam6"] },
            { chars: ["真","的","身","份","不","过","送","运"], jp: ["zan1","dik1","san1","fan2","bat1","gwo3","sung3","wan6"] },
            { chars: ["这","趟","旅","行","若","算","开","心","亦","是","无","负","一","生"], jp: ["ze5","tong3","leoi5","hang4","joek6","syun3","hoi1","sam1","jik6","si6","mou4","fu6","jat1","sang1"] },
            { paragraphBreak: true },
            { chars: ["水","点","蒸","发","变","做","白","云"], jp: ["seoi2","dim2","zing1","faat3","bin3","zou6","baak6","wan4"] },
            { chars: ["花","瓣","飘","落","下","游","生","根"], jp: ["faa1","faan2","piu1","lok6","haa6","jau4","saang1","gan1"] },
            { chars: ["淡","淡","交","会","过"], jp: ["daam6","daam6","gaau1","wui6","gwo3"] },
            { chars: ["各","不","留","下","印"], jp: ["gok3","bat1","lau4","haa6","jan3"] },
            { paragraphBreak: true },
            { chars: ["流","水","在","山","谷","下","再","次","分","岔"], jp: ["lau4","seoi2","zoi6","saan1","guk1","haa6","zoi3","ci3","fan1","caa3"] },
            { chars: ["情","感","渐","化","做","淡","然","优","雅"], jp: ["cing4","gam2","zim6","faa3","zou6","daam6","jin4","jau1","ngaa5"] },
            { chars: ["自","觉","心","境","已","有","如","明","镜"], jp: ["zi6","gok3","sam1","ging2","ji5","jau5","jyu4","ming4","geng3"] },
            { chars: ["为","何","为","天","降","的","稀","客","泛","过","一","点","浪","花"], jp: ["wai4","ho4","wai4","tin1","gong3","dik1","hei1","haak3","faan3","gwo3","jat1","dim2","long6","faa1"] },
            { paragraphBreak: true },
            { chars: ["天","下","并","非","只","是","有","这","朵","花"], jp: ["tin1","haa6","bing6","fei1","zi2","si6","jau5","ze5","do2","faa1"] },
            { chars: ["不","用","为","故","事","下","文","牵","挂"], jp: ["bat1","jung6","wai4","gu3","si6","haa6","man4","hin1","gwaa3"] },
            { chars: ["要","是","彼","此","都","有","些","既","定","路","程"], jp: ["jiu3","si6","bei2","ci2","dou1","jau5","se1","gei3","ding6","lou6","cing4"] },
            { chars: ["学","会","洒","脱"], jp: ["hok6","wui6","saa2","tyut3"] },
            { chars: ["好","吗"], jp: ["hou2","maa1"] },
            { paragraphBreak: true },
            { chars: ["流","水","很","清","楚"], jp: ["lau4","seoi2","han2","cing1","co2"] },
            { chars: ["惜","花","这","个","责","任"], jp: ["sik1","faa1","ze5","go3","zaak3","jam6"] },
            { chars: ["真","的","身","份","不","过","送","运"], jp: ["zan1","dik1","san1","fan2","bat1","gwo3","sung3","wan6"] },
            { chars: ["这","趟","旅","行","若","算","开","心","亦","是","无","负","一","生"], jp: ["ze5","tong3","leoi5","hang4","joek6","syun3","hoi1","sam1","jik6","si6","mou4","fu6","jat1","sang1"] },
            { paragraphBreak: true },
            { chars: ["水","点","蒸","发","变","做","白","云"], jp: ["seoi2","dim2","zing1","faat3","bin3","zou6","baak6","wan4"] },
            { chars: ["花","瓣","飘","落","下","游","生","根"], jp: ["faa1","faan2","piu1","lok6","haa6","jau4","saang1","gan1"] },
            { chars: ["命","运","敲","定","了"], jp: ["ming6","wan6","haau1","ding6","liu5"] },
            { chars: ["要","这","么","发","生"], jp: ["jiu3","ze5","mo1","faat3","sang1"] },
            { paragraphBreak: true },
            { chars: ["讲","分","开"], jp: ["gong2","fan1","hoi1"] },
            { chars: ["可","否","不","再","用","憾","事","的","口","吻"], jp: ["ho2","fau2","bat1","zoi3","jung6","ham6","si6","dik1","hau2","man5"] },
            { chars: ["习","惯","无","常","才","会","庆","幸"], jp: ["zaap6","gwaan3","mou4","soeng4","coi4","wui6","hing3","hang6"] },
            { chars: ["讲","真","天","涯","途","上","谁","是","客"], jp: ["gong2","zan1","tin1","ngaai4","tou4","soeng6","seoi4","si6","haak3"] },
            { chars: ["散","席","时","怎","么","分"], jp: ["saan3","zik6","si4","zam2","mo1","fan1"] },
            { paragraphBreak: true },
            { chars: ["流","水","很","清","楚"], jp: ["lau4","seoi2","han2","cing1","co2"] },
            { chars: ["惜","花","这","个","责","任"], jp: ["sik1","faa1","ze5","go3","zaak3","jam6"] },
            { chars: ["真","的","身","份","不","过","送","运"], jp: ["zan1","dik1","san1","fan2","bat1","gwo3","sung3","wan6"] },
            { chars: ["这","趟","旅","行","若","算","开","心","亦","是","无","负","一","生"], jp: ["ze5","tong3","leoi5","hang4","joek6","syun3","hoi1","sam1","jik6","si6","mou4","fu6","jat1","sang1"] },
            { paragraphBreak: true },
            { chars: ["水","点","蒸","发","变","做","白","云"], jp: ["seoi2","dim2","zing1","faat3","bin3","zou6","baak6","wan4"] },
            { chars: ["花","瓣","飘","落","下","游","生","根"], jp: ["faa1","faan2","piu1","lok6","haa6","jau4","saang1","gan1"] },
            { chars: ["淡","淡","交","会","过"], jp: ["daam6","daam6","gaau1","wui6","gwo3"] },
            { chars: ["各","不","留","下","印"], jp: ["gok3","bat1","lau4","haa6","jan3"] },
            { paragraphBreak: true },
            { chars: ["但","是","经","历","过","最","温","柔","共","震"], jp: ["daan6","si6","ging1","lik6","gwo3","zeoi3","wan1","jau4","gung6","zan3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
