// 歌曲：葡萄成熟时

(function() {
    const song = {
        id: 609,
        title: "葡萄成熟时",
        titleJyutping: ["pou4","tou4","sing4","suk6","si4"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "周炳辉/Anfernee Cheung",
        composerJyutping: ["zau1","bing2","fai1","","","","","","","","","","","","","","","",""],
        lyrics: [
            { chars: ["差","不","多","冬","至"], jp: ["caa1","bat1","do1","dung1","zi3"] },
            { chars: ["一","早","一","晚","还","是","有","雨"], jp: ["jat1","zou2","jat1","maan5","waan4","si6","jau5","jyu5"] },
            { chars: ["当","初","的","坚","持"], jp: ["dong1","co1","dik1","gin1","ci4"] },
            { chars: ["现","已","令","你","很","怀","疑"], jp: ["jin6","ji5","ling6","nei5","han2","waai4","ji4"] },
            { chars: ["很","怀","疑"], jp: ["han2","waai4","ji4"] },
            { chars: ["你","最","尾","等","到"], jp: ["nei5","zeoi3","mei1","dang2","dou3"] },
            { chars: ["只","有","这","枯","枝"], jp: ["zi2","jau5","ze5","fu1","zi1"] },
            { paragraphBreak: true },
            { chars: ["苦","恋","几","多","次"], jp: ["fu2","lyun2","gei2","do1","ci3"] },
            { chars: ["悉","心","栽","种","全","力","灌","注"], jp: ["sik1","sam1","zoi1","zung2","cyun4","lik6","gun3","zyu3"] },
            { chars: ["所","得","竟","不","如"], jp: ["so2","dak1","ging2","bat1","jyu4"] },
            { chars: ["别","个","后","辈","收","成","时"], jp: ["bit6","go3","hau6","bui3","sau1","sing4","si4"] },
            { chars: ["这","一","次","你","真","的","很","介","意"], jp: ["ze5","jat1","ci3","nei5","zan1","dik1","han2","gaai3","ji3"] },
            { paragraphBreak: true },
            { chars: ["但","见","旁","人","谈","情","何","引","诱"], jp: ["daan6","gin3","pong4","jan4","taam4","cing4","ho4","jan5","jau5"] },
            { chars: ["问","到","何","时","葡","萄","先","熟","透"], jp: ["man6","dou3","ho4","si4","pou4","tou4","sin1","suk6","tau3"] },
            { chars: ["你","要","静","候"], jp: ["nei5","jiu3","zing6","hau6"] },
            { chars: ["再","静","候"], jp: ["zoi3","zing6","hau6"] },
            { chars: ["就","算","失","收"], jp: ["zau6","syun3","sat1","sau1"] },
            { chars: ["始","终","要","守"], jp: ["ci2","zung1","jiu3","sau2"] },
            { paragraphBreak: true },
            { chars: ["日","后"," ","尽","量","别","教","今","天","的","泪","白","流"], jp: ["jat6","hau6","","zeon6","loeng4","bit6","gaau3","gam1","tin1","dik1","leoi6","baak6","lau4"] },
            { chars: ["留","低"," ","击","伤","你","的","石","头"], jp: ["lau4","dai1","","gik1","soeng1","nei5","dik1","sek6","tau4"] },
            { chars: ["从","错","误","里","吸","收"], jp: ["cung4","co3","ng6","leoi5","kap1","sau1"] },
            { chars: ["也","许"," ","丰","收"," ","月","份","尚","未","到","你","也","得","接","受"], jp: ["jaa5","heoi2","","fung1","sau1","","jyut6","fan6","soeng6","mei6","dou3","nei5","jaa5","dak1","zip3","sau6"] },
            { chars: ["或","者","要","到","你","将","爱","酿","成","醇","酒"], jp: ["waak6","ze2","jiu3","dou3","nei5","zoeng1","ngoi3","joeng6","sing4","seon4","zau2"] },
            { chars: ["时","机","先","至","熟","透"], jp: ["si4","gei1","sin1","zi3","suk6","tau3"] },
            { paragraphBreak: true },
            { chars: ["应","该","怎","么","爱"], jp: ["jing3","goi1","zam2","mo1","ngoi3"] },
            { chars: ["可","惜","书","里","从","没","记","载"], jp: ["ho2","sik1","syu1","leoi5","cung4","mut6","gei3","zoi3"] },
            { chars: ["终","于","摸","出","来"], jp: ["zung1","jyu1","mo2","ceot1","loi4"] },
            { chars: ["但","岁","月","却","不","回","来"], jp: ["daan6","seoi3","jyut6","koek3","bat1","wui4","loi4"] },
            { chars: ["不","回","来"], jp: ["bat1","wui4","loi4"] },
            { chars: ["错","过","了","春","天"], jp: ["co3","gwo3","liu5","ceon1","tin1"] },
            { chars: ["可","会","再","花","开"], jp: ["ho2","wui6","zoi3","faa1","hoi1"] },
            { paragraphBreak: true },
            { chars: ["一","千","种","恋","爱"], jp: ["jat1","cin1","zung2","lyun2","ngoi3"] },
            { chars: ["一","些","需","要","情","泪","灌","溉"], jp: ["jat1","se1","seoi1","jiu3","cing4","leoi6","gun3","koi3"] },
            { chars: ["枯","毁","的","温","柔"], jp: ["fu1","wai2","dik1","wan1","jau4"] },
            { chars: ["在","最","后","会","长","回","来"], jp: ["zoi6","zeoi3","hau6","wui6","coeng4","wui4","loi4"] },
            { chars: ["错","的","爱"], jp: ["co3","dik1","ngoi3"] },
            { chars: ["乃","必","经","的","配","菜"], jp: ["naai5","bit1","ging1","dik1","pui3","coi3"] },
            { paragraphBreak: true },
            { chars: ["但","见","旁","人","谈","情","何","引","诱"], jp: ["daan6","gin3","pong4","jan4","taam4","cing4","ho4","jan5","jau5"] },
            { chars: ["问","到","何","时","葡","萄","先","熟","透"], jp: ["man6","dou3","ho4","si4","pou4","tou4","sin1","suk6","tau3"] },
            { chars: ["你","要","静","候"], jp: ["nei5","jiu3","zing6","hau6"] },
            { chars: ["再","静","候"], jp: ["zoi3","zing6","hau6"] },
            { chars: ["就","算","失","收"], jp: ["zau6","syun3","sat1","sau1"] },
            { chars: ["始","终","要","守"], jp: ["ci2","zung1","jiu3","sau2"] },
            { paragraphBreak: true },
            { chars: ["日","后"," ","尽","量","别","教","今","天","的","泪","白","流"], jp: ["jat6","hau6","","zeon6","loeng4","bit6","gaau3","gam1","tin1","dik1","leoi6","baak6","lau4"] },
            { chars: ["留","低"," ","击","伤","你","的","石","头"], jp: ["lau4","dai1","","gik1","soeng1","nei5","dik1","sek6","tau4"] },
            { chars: ["从","错","误","里","吸","收"], jp: ["cung4","co3","ng6","leoi5","kap1","sau1"] },
            { chars: ["也","许"," ","丰","收"," ","月","份","尚","未","到","你","也","得","接","受"], jp: ["jaa5","heoi2","","fung1","sau1","","jyut6","fan6","soeng6","mei6","dou3","nei5","jaa5","dak1","zip3","sau6"] },
            { chars: ["或","者","要","到","你","将","爱","酿","成","醇","酒"], jp: ["waak6","ze2","jiu3","dou3","nei5","zoeng1","ngoi3","joeng6","sing4","seon4","zau2"] },
            { chars: ["时","机","先","至","熟","透"], jp: ["si4","gei1","sin1","zi3","suk6","tau3"] },
            { paragraphBreak: true },
            { chars: ["想","想","天","的","一","边"], jp: ["soeng2","soeng2","tin1","dik1","jat1","bin1"] },
            { chars: ["亦","有","个","某","某"], jp: ["jik6","jau5","go3","mau5","mau5"] },
            { chars: ["在","等","候"], jp: ["zoi6","dang2","hau6"] },
            { chars: ["一","心","只","等","葡","萄","熟","透"], jp: ["jat1","sam1","zi2","dang2","pou4","tou4","suk6","tau3"] },
            { chars: ["尝","杯","酒"], jp: ["soeng4","bui1","zau2"] },
            { paragraphBreak: true },
            { chars: ["别","让"," ","寂","寞","害","你","想","得","一","夜","白","头"], jp: ["bit6","joeng6","","zik6","mok6","hoi6","nei5","soeng2","dak1","jat1","je6","baak6","tau4"] },
            { chars: ["嬴","得","不","需","要","的","自","由"], jp: ["jing4","dak1","bat1","seoi1","jiu3","dik1","zi6","jau4"] },
            { chars: ["和","最","耀","眼","伤","口"], jp: ["wo4","zeoi3","jiu6","ngaan5","soeng1","hau2"] },
            { chars: ["我","知"," ","日","后"," ","路","上","或","没","有","更","美","的","邂","逅"], jp: ["ngo5","zi1","","jat6","hau6","","lou6","soeng6","waak6","mut6","jau5","gang1","mei5","dik1","haai5","hau6"] },
            { chars: ["但","当","你","智","慧","都","蕴","酿","成","红","酒"], jp: ["daan6","dong1","nei5","zi3","wai3","dou1","wan3","joeng6","sing4","hung4","zau2"] },
            { chars: ["仍","可","一","醉","自","救"], jp: ["jing4","ho2","jat1","zeoi3","zi6","gau3"] },
            { chars: ["谁","都","心","酸","过"], jp: ["seoi4","dou1","sam1","syun1","gwo3"] },
            { chars: ["那","个","没","有"], jp: ["naa5","go3","mut6","jau5"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
