// 歌曲：透视

(function() {
    const song = {
        id: 962,
        title: "透视",
        titleJyutping: ["tau3","si6"],
        artist: "莫文蔚",
        artistJyutping: ["mok6","man4","wai3"],
        lyricist: "周耀辉",
        lyricistJyutping: ["zau1","jiu6","fai1"],
        composer: "谢霆锋",
        composerJyutping: ["ze6","ting4","fung1"],
        lyrics: [
            { chars: ["世","界","没","有","孔","雀"], jp: ["sai3","gaai3","mut6","jau5","hung2","zoek2"] },
            { chars: ["你","会","看","到","知","更","鸟","吗"], jp: ["nei5","wui6","hon3","dou3","zi1","gang1","niu5","maa1"] },
            { chars: ["世","界","厌","弃","钻","石"], jp: ["sai3","gaai3","jim3","hei3","zyun3","sek6"] },
            { chars: ["你","会","发","觉","沙","的","美","好","吗"], jp: ["nei5","wui6","faat3","gok3","saa1","dik1","mei5","hou2","maa1"] },
            { chars: ["若","是","现","在","问","你"], jp: ["joek6","si6","jin6","zoi6","man6","nei5"] },
            { chars: ["欣","赏","我","吗"], jp: ["jan1","soeng2","ngo5","maa1"] },
            { chars: ["或","是","纯","粹"], jp: ["waak6","si6","seon4","seoi6"] },
            { chars: ["观","赏","我","吗"], jp: ["gun1","soeng2","ngo5","maa1"] },
            { chars: ["长","裙","极","黑"], jp: ["coeng4","kwan4","gik6","hak1"] },
            { chars: ["愿","望","极","蓝"], jp: ["jyun6","mong6","gik6","laam4"] },
            { chars: ["不","想","身","边","的","你","看","漏","眼"], jp: ["bat1","soeng2","san1","bin1","dik1","nei5","hon3","lau6","ngaan5"] },
            { chars: ["红","鞋","极","花"], jp: ["hung4","haai4","gik6","faa1"] },
            { chars: ["寂","寞","极","难"], jp: ["zik6","mok6","gik6","naan4"] },
            { chars: ["十","万","件","衫"], jp: ["sap6","maan6","gin6","saam1"] },
            { chars: ["穿","不","上","心","间"], jp: ["cyun1","bat1","soeng5","sam1","gaan1"] },
            { paragraphBreak: true },
            { chars: ["叛","逆","暴","烈","或","要","高","贵","冷","艳"], jp: ["bun6","jik6","bou6","lit6","waak6","jiu3","gou1","gwai3","laang5","jim6"] },
            { chars: ["公","主","的","新","衣","原","来","愿","透","视"], jp: ["gung1","zyu2","dik1","san1","ji1","jyun4","loi4","jyun6","tau3","si6"] },
            { chars: ["如","能","望","着","望","着","便","看","穿","所","有","我","的","心","意"], jp: ["jyu4","nang4","mong6","zoek6","mong6","zoek6","bin6","hon3","cyun1","so2","jau5","ngo5","dik1","sam1","ji3"] },
            { chars: ["要","是","真","的","要","知"], jp: ["jiu3","si6","zan1","dik1","jiu3","zi1"] },
            { chars: ["以","为","不","讲","也","知","会","望","见"], jp: ["ji5","wai4","bat1","gong2","jaa5","zi1","wui6","mong6","gin3"] },
            { paragraphBreak: true },
            { chars: ["世","界","或","有","魔","镜"], jp: ["sai3","gaai3","waak6","jau5","mo1","geng3"] },
            { chars: ["我","会","照","出","真","的","爱","吗"], jp: ["ngo5","wui6","ziu3","ceot1","zan1","dik1","ngoi3","maa1"] },
            { chars: ["你","说","我","最","漂","亮"], jp: ["nei5","syut3","ngo5","zeoi3","piu3","loeng6"] },
            { chars: ["你","有","看","过","不","想","看","的","吗"], jp: ["nei5","jau5","hon3","gwo3","bat1","soeng2","hon3","dik1","maa1"] },
            { chars: ["若","是","现","在","问","你"], jp: ["joek6","si6","jin6","zoi6","man6","nei5"] },
            { chars: ["欣","赏","我","吗"], jp: ["jan1","soeng2","ngo5","maa1"] },
            { chars: ["或","许","是","纯","粹"], jp: ["waak6","heoi2","si6","seon4","seoi6"] },
            { chars: ["观","赏","镜","花"], jp: ["gun1","soeng2","geng3","faa1"] },
            { chars: ["眉","毛","极","黑"], jp: ["mei4","mou4","gik6","hak1"] },
            { chars: ["杂","念","极","烦"], jp: ["zaap6","nim6","gik6","faan4"] },
            { chars: ["不","想","身","边","的","你","看","漏","眼"], jp: ["bat1","soeng2","san1","bin1","dik1","nei5","hon3","lau6","ngaan5"] },
            { chars: ["外","面","是","花"], jp: ["ngoi6","min6","si6","faa1"] },
            { chars: ["入","面","是","谁"], jp: ["jap6","min6","si6","seoi4"] },
            { chars: ["十","万","件","衫"], jp: ["sap6","maan6","gin6","saam1"] },
            { chars: ["穿","得","再","多"], jp: ["cyun1","dak1","zoi3","do1"] },
            { chars: ["穿","不","上","心","间"], jp: ["cyun1","bat1","soeng5","sam1","gaan1"] },
            { paragraphBreak: true },
            { chars: ["叛","逆","暴","烈","或","要","高","贵","冷","艳"], jp: ["bun6","jik6","bou6","lit6","waak6","jiu3","gou1","gwai3","laang5","jim6"] },
            { chars: ["公","主","的","新","衣","原","来","愿","透","视"], jp: ["gung1","zyu2","dik1","san1","ji1","jyun4","loi4","jyun6","tau3","si6"] },
            { chars: ["如","能","望","着","望","着","便","看","穿","所","有","我","的","心","意"], jp: ["jyu4","nang4","mong6","zoek6","mong6","zoek6","bin6","hon3","cyun1","so2","jau5","ngo5","dik1","sam1","ji3"] },
            { chars: ["以","为","很","想","你","知"], jp: ["ji5","wai4","han2","soeng2","nei5","zi1"] },
            { chars: ["最","后","不","讲","也","会","知"], jp: ["zeoi3","hau6","bat1","gong2","jaa5","wui6","zi1"] },
            { paragraphBreak: true },
            { chars: ["傲","慢","荏","弱","或","要","亲","切","自","然"], jp: ["ngou6","maan6","jam5","joek6","waak6","jiu3","can1","cit3","zi6","jin4"] },
            { chars: ["公","主","的","新","衣","原","来","愿","透","视"], jp: ["gung1","zyu2","dik1","san1","ji1","jyun4","loi4","jyun6","tau3","si6"] },
            { chars: ["如","能","望","着","望","着","便","看","穿","所","有","我","的","精","致"], jp: ["jyu4","nang4","mong6","zoek6","mong6","zoek6","bin6","hon3","cyun1","so2","jau5","ngo5","dik1","zing1","zi3"] },
            { chars: ["我","在","你","眼","前"], jp: ["ngo5","zoi6","nei5","ngaan5","cin4"] },
            { chars: ["你","是","否","望","见"], jp: ["nei5","si6","fau2","mong6","gin3"] },
            { paragraphBreak: true },
            { chars: ["叛","逆","暴","烈","或","要","高","贵","冷","艳"], jp: ["bun6","jik6","bou6","lit6","waak6","jiu3","gou1","gwai3","laang5","jim6"] },
            { chars: ["公","主","的","新","衣","原","来","愿","透","视"], jp: ["gung1","zyu2","dik1","san1","ji1","jyun4","loi4","jyun6","tau3","si6"] },
            { chars: ["如","能","望","着","望","着","便","看","穿","所","有","我","的","心","意"], jp: ["jyu4","nang4","mong6","zoek6","mong6","zoek6","bin6","hon3","cyun1","so2","jau5","ngo5","dik1","sam1","ji3"] },
            { chars: ["以","为","很","想","你","知"], jp: ["ji5","wai4","han2","soeng2","nei5","zi1"] },
            { chars: ["最","后","不","讲","也","会","知"], jp: ["zeoi3","hau6","bat1","gong2","jaa5","wui6","zi1"] },
            { paragraphBreak: true },
            { chars: ["傲","慢","荏","弱","或","要","亲","切","自","然"], jp: ["ngou6","maan6","jam5","joek6","waak6","jiu3","can1","cit3","zi6","jin4"] },
            { chars: ["公","主","的","新","衣","从","来","尽","量","透","视"], jp: ["gung1","zyu2","dik1","san1","ji1","cung4","loi4","zeon6","loeng4","tau3","si6"] },
            { chars: ["如","能","望","着","望","着","便","看","穿","所","有","我","的","精","致"], jp: ["jyu4","nang4","mong6","zoek6","mong6","zoek6","bin6","hon3","cyun1","so2","jau5","ngo5","dik1","zing1","zi3"] },
            { chars: ["着","什","么","的","衬","衣"], jp: ["zoek6","sap6","mo1","dik1","can3","ji1"] },
            { chars: ["有","什","么","的","意","思"], jp: ["jau5","sap6","mo1","dik1","ji3","si1"] },
            { chars: ["看","便","见"], jp: ["hon3","bin6","gin3"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
