// 歌曲：阿牛

(function() {
    const song = {
        id: 627,
        title: "阿牛",
        titleJyutping: ["aa3","ngau4"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["不","能","回","头"], jp: ["bat1","nang4","wui4","tau4"] },
            { chars: ["多","年","前"], jp: ["do1","nin4","cin4"] },
            { chars: ["早","明","言","不","能","回","头"], jp: ["zou2","ming4","jin4","bat1","nang4","wui4","tau4"] },
            { chars: ["可","恨","在"], jp: ["ho2","han6","zoi6"] },
            { chars: ["是","我","这","一","头","蛮","牛"], jp: ["si6","ngo5","ze5","jat1","tau4","maan4","ngau4"] },
            { chars: ["几","年","来","无","法","侍","候"], jp: ["gei2","nin4","loi4","mou4","faat3","si6","hau6"] },
            { chars: ["才","和","我","分","手"], jp: ["coi4","wo4","ngo5","fan1","sau2"] },
            { paragraphBreak: true },
            { chars: ["成","婚","之","前","一","刻","才","赶","到"], jp: ["sing4","fan1","zi1","cin4","jat1","haak1","coi4","gon2","dou3"] },
            { chars: ["难","得","你","来","通","报","才","知","道"], jp: ["naan4","dak1","nei5","loi4","tung1","bou3","coi4","zi1","dou3"] },
            { chars: ["往","日","共","你","追","忆","永","远","是","好"], jp: ["wong5","jat6","gung6","nei5","zeoi1","jik1","wing5","jyun5","si6","hou2"] },
            { chars: ["怎","能","预","计","似","这","般","难","共","你","同","揩","共","老"], jp: ["zam2","nang4","jyu6","gai3","ci5","ze5","bun1","naan4","gung6","nei5","tung4","haai1","gung6","lou5"] },
            { paragraphBreak: true },
            { chars: ["你","话","只","需","肯","做"], jp: ["nei5","waa6","zi2","seoi1","hang2","zou6"] },
            { chars: ["差","一","刹","与","我","拾","回","旧","好"], jp: ["caa1","jat1","caat3","jyu5","ngo5","sap6","wui4","gau6","hou2"] },
            { chars: ["不","甘","心"], jp: ["bat1","gam1","sam1"] },
            { chars: ["尤","其","这","新","婚"], jp: ["jau4","kei4","ze5","san1","fan1"] },
            { chars: ["就","像","玩","牺","牲"], jp: ["zau6","zoeng6","wun6","hei1","sang1"] },
            { chars: ["想","过","抢","新","娘"], jp: ["soeng2","gwo3","coeng2","san1","noeng2"] },
            { chars: ["我","差","点","讲","真"], jp: ["ngo5","caa1","dim2","gong2","zan1"] },
            { paragraphBreak: true },
            { chars: ["历","史","一","刻","早","已","将","旧","伴","侣","转","送","别","人"], jp: ["lik6","si2","jat1","haak1","zou2","ji5","zoeng1","gau6","bun6","leoi5","zyun2","sung3","bit6","jan4"] },
            { chars: ["我","说"," ","别","伤","心"], jp: ["ngo5","syut3","","bit6","soeng1","sam1"] },
            { chars: ["仍","能","恰","当","大","方","去","做","人"], jp: ["jing4","nang4","hap1","dong1","daai6","fong1","heoi3","zou6","jan4"] },
            { chars: ["约","定","日","后","你","若","和","他","相","分"], jp: ["joek3","ding6","jat6","hau6","nei5","joek6","wo4","taa1","soeng1","fan1"] },
            { chars: ["拿","来","用","你","尚","有","余","的","恻","隐"], jp: ["naa4","loi4","jung6","nei5","soeng6","jau5","jyu4","dik1","cak1","jan2"] },
            { chars: ["怜","悯","我","此","生","的","不","幸"], jp: ["lin4","man5","ngo5","ci2","sang1","dik1","bat1","hang6"] },
            { chars: ["不","紧","要"], jp: ["bat1","gan2","jiu3"] },
            { chars: ["约","到","明","年","来","生"], jp: ["joek3","dou3","ming4","nin4","loi4","sang1"] },
            { paragraphBreak: true },
            { chars: ["不","甘","心"], jp: ["bat1","gam1","sam1"] },
            { chars: ["人","人","不","开","心"], jp: ["jan4","jan4","bat1","hoi1","sam1"] },
            { chars: ["尤","其","这","新","婚"], jp: ["jau4","kei4","ze5","san1","fan1"] },
            { chars: ["失","去","我","身","份"], jp: ["sat1","heoi3","ngo5","san1","fan2"] },
            { chars: ["不","甘","心"], jp: ["bat1","gam1","sam1"] },
            { chars: ["明","明","不","开","心"], jp: ["ming4","ming4","bat1","hoi1","sam1"] },
            { chars: ["就","是","不","甘","心"], jp: ["zau6","si6","bat1","gam1","sam1"] },
            { chars: ["不","过","我","肯","等"], jp: ["bat1","gwo3","ngo5","hang2","dang2"] },
            { chars: ["等","一","生","都","等"], jp: ["dang2","jat1","sang1","dou1","dang2"] },
            { paragraphBreak: true },
            { chars: ["这","都","好"], jp: ["ze5","dou1","hou2"] },
            { chars: ["自","小","想","拿","到","的","全","得","到"], jp: ["zi6","siu2","soeng2","naa4","dou3","dik1","cyun4","dak1","dou3"] },
            { chars: ["如","今","我","求","不","到","才","知","道"], jp: ["jyu4","gam1","ngo5","kau4","bat1","dou3","coi4","zi1","dou3"] },
            { chars: ["我","命","运","里","虽","则","当","你","是","宝"], jp: ["ngo5","ming6","wan6","leoi5","seoi1","zak1","dong1","nei5","si6","bou2"] },
            { chars: ["天","涯","上","有","更","多","的","好","情","人","仍","然","未","抱"], jp: ["tin1","ngaai4","soeng6","jau5","gang1","do1","dik1","hou2","cing4","jan4","jing4","jin4","mei6","pou5"] },
            { chars: ["要","这","么","的","惨","酷"], jp: ["jiu3","ze5","mo1","dik1","caam2","huk6"] },
            { chars: ["她","不","要","我","再","拾","回","旧","好"], jp: ["taa1","bat1","jiu3","ngo5","zoi3","sap6","wui4","gau6","hou2"] },
            { paragraphBreak: true },
            { chars: ["不","甘","心"], jp: ["bat1","gam1","sam1"] },
            { chars: ["人","人","不","开","心"], jp: ["jan4","jan4","bat1","hoi1","sam1"] },
            { chars: ["尤","其","这","新","婚"], jp: ["jau4","kei4","ze5","san1","fan1"] },
            { chars: ["失","去","我","身","份"], jp: ["sat1","heoi3","ngo5","san1","fan2"] },
            { chars: ["不","甘","心"], jp: ["bat1","gam1","sam1"] },
            { chars: ["明","明","不","开","心"], jp: ["ming4","ming4","bat1","hoi1","sam1"] },
            { chars: ["就","是","不","甘","心"], jp: ["zau6","si6","bat1","gam1","sam1"] },
            { chars: ["不","过","我","肯","等"], jp: ["bat1","gwo3","ngo5","hang2","dang2"] },
            { chars: ["等","一","生","都","等"], jp: ["dang2","jat1","sang1","dou1","dang2"] },
            { paragraphBreak: true },
            { chars: ["一","头","蛮","牛"], jp: ["jat1","tau4","maan4","ngau4"] },
            { chars: ["闯","情","场","竟","成","为","一","头","蛮","牛"], jp: ["cong2","cing4","coeng4","ging2","sing4","wai4","jat1","tau4","maan4","ngau4"] },
            { chars: ["惨","淡","在","是","我","知","不","能","回","头"], jp: ["caam2","daam6","zoi6","si6","ngo5","zi1","bat1","nang4","wui4","tau4"] },
            { chars: ["欺","骗","我","能","约","定","未","来","回","头"], jp: ["hei1","pin3","ngo5","nang4","joek3","ding6","mei6","loi4","wui4","tau4"] },
            { chars: ["我","是","牛"," ","我","是","牛"], jp: ["ngo5","si6","ngau4","","ngo5","si6","ngau4"] }
        ]
    };
    // 【方案A】通过 __songPush 接口注册歌曲数据
    // loadSongLyrics() 会将 __songPush 替换为当前歌曲的唯一数组
    if (typeof window !== 'undefined' && window.__songPush) {
        window.__songPush(song);
    }
})();
