// 歌曲：黄色大门（live）

(function() {
    const song = {
        id: 508,
        title: "黄色大门（live）",
        titleJyutping: ["wong4","sik1","daai6","mun4","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "王双骏",
        composerJyutping: ["wong4","soeng1","zeon3"],
        lyrics: [
            { chars: ["窗","纱","外"], jp: ["coeng1","saa1","ngoi6"] },
            { chars: ["小","鹿","给","我","送","枝","花"], jp: ["siu2","luk6","kap1","ngo5","sung3","zi1","faa1"] },
            { chars: ["梳","化","上"], jp: ["so1","faa3","soeng6"] },
            { chars: ["下","凡","天","使","共","我","喝","著","茶"], jp: ["haa6","faan4","tin1","si2","gung6","ngo5","hot3","zyu3","caa4"] },
            { chars: ["世","间","千","千","万","万","人"], jp: ["sai3","gaan1","cin1","cin1","maan6","maan6","jan4"] },
            { chars: ["未","明","白","我"], jp: ["mei6","ming4","baak6","ngo5"] },
            { chars: ["替","这","位","空","想","家","惊","讶"], jp: ["tai3","ze5","wai6","hung1","soeng2","gaa1","ging1","ngaa6"] },
            { chars: ["孤","单","真","的","不","可","怕"], jp: ["gu1","daan1","zan1","dik1","bat1","ho2","paa3"] },
            { chars: ["能","让","我","画","满","花"], jp: ["nang4","joeng6","ngo5","waak6","mun5","faa1"] },
            { chars: ["还","未","算","是","那","么","差"], jp: ["waan4", "mei6", "syun3", "si6", "naa5", "mo1", "caa1"] },
            { paragraphBreak: true },
            { chars: ["让","那"," ","恐","龙","成","群","行","过","枱","面"], jp: ["joeng6","naa5","","hung2","lung4","sing4","kwan4","hang4","gwo3","toi2","min6"] },
            { chars: ["衣","柜","入","面","藏","著","花","园"], jp: ["ji1","gwai6","jap6","min6","cong4","zyu3","faa1","jyun4"] },
            { chars: ["心","仪","男","孩","长","驻","于","身","边"], jp: ["sam1","ji4","naam4","haai4","coeng4","zyu3","jyu1","san1","bin1"] },
            { chars: ["梦","要","变","真","也","没","那","样","远"], jp: ["mung6","jiu3","bin3","zan1","jaa5","mut6","naa5","joeng6","jyun5"] },
            { chars: ["生","命","从","未","如","乐","园"], jp: ["sang1","ming6","cung4","mei6","jyu4","lok6","jyun4"] },
            { chars: ["也","可","靠","我","创","造","浮","现"], jp: ["jaa5","ho2","kaau3","ngo5","cong3","zou6","fau4","jin6"] },
            { paragraphBreak: true },
            { chars: ["让","那"," ","彩","虹","长","桥","无","限","伸","展"], jp: ["joeng6","naa5","","coi2","hung4","coeng4","kiu4","mou4","haan6","san1","zin2"] },
            { chars: ["飞","象","日","日","云","上","表","演"], jp: ["fei1","zoeng6","jat6","jat6","wan4","soeng6","biu2","jin2"] },
            { chars: ["魔","幻","现","实","寻","到","相","交","点"], jp: ["mo1","waan6","jin6","sat6","cam4","dou3","soeng1","gaau1","dim2"] },
            { chars: ["在","我","心","房","的"], jp: ["zoi6","ngo5","sam1","fong4","dik1"] },
            { chars: ["黄","色"," ","门","里"], jp: ["wong4", "sik1", "", "mun4", "leoi5"] },
            { chars: ["保","存","著"], jp: ["bou2","cyun4","zyu3"] },
            { chars: ["未","坐","那","火","箭"], jp: ["mei6","zo6","naa5","fo2","zin3"] },
            { paragraphBreak: true },
            { chars: ["天","花","上"], jp: ["tin1","faa1","soeng6"] },
            { chars: ["星","星","眨","眼","变","烟","花"], jp: ["sing1","sing1","zaap3","ngaan5","bin3","jin1","faa1"] },
            { chars: ["口","袋","内"], jp: ["hau2","doi6","noi6"] },
            { chars: ["是","前","一","晚","摘","了","那","月","牙"], jp: ["si6","cin4","jat1","maan5","zaak6","liu5","naa5","jyut6","ngaa4"] },
            { chars: ["我","编","绘","的","让","别","人"], jp: ["ngo5","pin1","kui2","dik1","joeng6","bit6","jan4"] },
            { chars: ["视","为","幻","觉"], jp: ["si6","wai4","waan6","gok3"] },
            { chars: ["我","早","知","因","此","不","惊","诧"], jp: ["ngo5","zou2","zi1","jan1","ci2","bat1","ging1","caa3"] },
            { chars: ["今","天","虽","则","长","高","了"], jp: ["gam1","tin1","seoi1","zak1","coeng4","gou1","liu5"] },
            { chars: ["墙","上","继","续","挂","的"], jp: ["coeng4","soeng6","gai3","zuk6","gwaa3","dik1"] },
            { chars: ["还","是","我","六","岁","的","画"], jp: ["waan4","si6","ngo5","luk6","seoi3","dik1","waak6"] },
            { paragraphBreak: true },
            { chars: ["让","那"," ","恐","龙","成","群","行","过","枱","面"], jp: ["joeng6","naa5","","hung2","lung4","sing4","kwan4","hang4","gwo3","toi2","min6"] },
            { chars: ["衣","柜","入","面","藏","著","花","园"], jp: ["ji1","gwai6","jap6","min6","cong4","zyu3","faa1","jyun4"] },
            { chars: ["心","仪","男","孩","长","驻","于","身","边"], jp: ["sam1","ji4","naam4","haai4","coeng4","zyu3","jyu1","san1","bin1"] },
            { chars: ["梦","要","变","真","也","没","那","样","远"], jp: ["mung6","jiu3","bin3","zan1","jaa5","mut6","naa5","joeng6","jyun5"] },
            { chars: ["生","命","从","未","如","乐","园"], jp: ["sang1","ming6","cung4","mei6","jyu4","lok6","jyun4"] },
            { chars: ["也","可","靠","我","创","造","浮","现"], jp: ["jaa5","ho2","kaau3","ngo5","cong3","zou6","fau4","jin6"] },
            { paragraphBreak: true },
            { chars: ["让","那"," ","彩","虹","长","桥","无","限","伸","展"], jp: ["joeng6","naa5","","coi2","hung4","coeng4","kiu4","mou4","haan6","san1","zin2"] },
            { chars: ["飞","象","日","日","云","上","表","演"], jp: ["fei1","zoeng6","jat6","jat6","wan4","soeng6","biu2","jin2"] },
            { chars: ["魔","幻","现","实","寻","到","相","交","点"], jp: ["mo1","waan6","jin6","sat6","cam4","dou3","soeng1","gaau1","dim2"] },
            { chars: ["在","我","心","房","的"], jp: ["zoi6","ngo5","sam1","fong4","dik1"] },
            { chars: ["黄","色"," ","门","里"], jp: ["wong4", "sik1", "", "mun4", "leoi5"] },
            { chars: ["保","存","著"], jp: ["bou2","cyun4","zyu3"] },
            { chars: ["未","坐","那","火","箭"], jp: ["mei6","zo6","naa5","fo2","zin3"] },
            { paragraphBreak: true },
            { chars: ["让","那"," ","海","豚","时","时","游","到","指","尖"], jp: ["joeng6","naa5","","hoi2","tyun4","si4","si4","jau4","dou3","zi2","zim1"] },
            { chars: ["不","由","旁","人","沉","闷","伤","损"], jp: ["bat1","jau4","pong4","jan4","cam4","mun6","soeng1","syun2"] },
            { chars: ["一","人","同","行"], jp: ["jat1","jan4","tung4","hang4"] },
            { chars: ["行","进","卡","通","片"], jp: ["hang4","zeon3","kaa1","tung1","pin3"] },
            { chars: ["在","我","坚","持","的"], jp: ["zoi6","ngo5","gin1","ci4","dik1"] },
            { chars: ["黄","色"," ","门","里"], jp: ["wong4", "sik1", "", "mun4", "leoi5"] },
            { chars: ["珍","藏","著"], jp: ["zan1","cong4","zyu3"] },
            { chars: ["自","制","那","冠","冕"], jp: ["zi6","zai3","naa5","gun1","min5"] },
            { paragraphBreak: true },
            { chars: ["窗","纱","外"], jp: ["coeng1","saa1","ngoi6"] },
            { chars: ["小","鹿","给","我","送","枝","花"], jp: ["siu2","luk6","kap1","ngo5","sung3","zi1","faa1"] },
            { chars: ["想","想","吧"], jp: ["soeng2","soeng2","baa6"] },
            { chars: ["真","想","给","你","见","到","牠"], jp: ["zan1","soeng2","kap1","nei5","gin3","dou3","taa1"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
